In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/12_E066 with 5 common histones/dataset/'
OUTPUT_PATH = '/group/pmc021/amunif/epi-thesis/workflow/12_E066 with 5 common histones/output/'

In [3]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.5533    ┆ 73.9408   ┆ 0.7393    ┆ … ┆ 74.1166   ┆ 0.74      ┆ 74.85     ┆ 0.7466   │
│ H3K9ac    ┆ 0.5429    ┆ 74.5118   ┆ 0.7436    ┆ … ┆ 75.5091   ┆ 0.7544    ┆ 75.9      ┆ 0.7576   │
│ H3K9me3   ┆ 0.6964    ┆ 56.7891   ┆ 0.566     ┆ … ┆ 57.2096   ┆ 0.5651    ┆ 56.84     ┆ 0.561    │
│ H3K27ac   ┆ 0.5455    ┆ 74.5582   ┆ 0.7444    ┆ … ┆ 75.4619   ┆ 0.7532    ┆ 75.61     ┆ 0.7542   │
│ H3K27me3  ┆ 0.6717    ┆ 59.8038   ┆ 0.5932    ┆ … ┆ 60.1242   ┆ 0.5943    ┆ 60.46     ┆ 0.5945   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.5189    ┆ 75.51     ┆ 0.7552    ┆ … ┆ 76.1601   ┆ 0.7605    ┆ 76.25     ┆ 0.762    │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5122    ┆ 76.0781   ┆ 0.7597    ┆ … ┆ 76.7728   ┆ 0.7669    ┆ 76.65     ┆ 0.766    │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5148    ┆ 75.9096   ┆ 0.7595    ┆ … ┆ 76.6654   ┆ 0.7661    ┆ 77.34     ┆ 0.7731   │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5191    ┆ 75.6025   ┆ 0.7564    ┆ … ┆ 76.5195   ┆ 0.765     ┆ 76.52     ┆ 0.764    │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5117    ┆ 76.0672   ┆ 0.7598    ┆ … ┆ 76.7244   ┆ 0.7667    ┆ 76.17     ┆ 0.7614   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the histone number column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.5533    ┆ 73.9408   ┆ 0.7393    ┆ … ┆ 0.74      ┆ 74.85     ┆ 0.7466   ┆ 1         │
│ H3K9ac    ┆ 0.5429    ┆ 74.5118   ┆ 0.7436    ┆ … ┆ 0.7544    ┆ 75.9      ┆ 0.7576   ┆ 1         │
│ H3K9me3   ┆ 0.6964    ┆ 56.7891   ┆ 0.566     ┆ … ┆ 0.5651    ┆ 56.84     ┆ 0.561    ┆ 1         │
│ H3K27ac   ┆ 0.5455    ┆ 74.5582   ┆ 0.7444    ┆ … ┆ 0.7532    ┆ 75.61     ┆ 0.7542   ┆ 1         │
│ H3K27me3  ┆ 0.6717    ┆ 59.8038   ┆ 0.5932    ┆ … ┆ 0.5943    ┆ 60.46     ┆ 0.5945   ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.5189    ┆ 75.51     ┆ 0.7552    ┆ … ┆ 0.7605    ┆ 76.25     ┆ 0.762    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5122    ┆ 76.0781   ┆ 0.7597    ┆ … ┆ 0.7669    ┆ 76.65     ┆ 0.766    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5148    ┆ 75.9096   ┆ 0.7595    ┆ … ┆ 0.7661    ┆ 77.34     ┆ 0.7731   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5191    ┆ 75.6025   ┆ 0.7564    ┆ … ┆ 0.765     ┆ 76.52     ┆ 0.764    ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5117    ┆ 76.0672   ┆ 0.7598    ┆ … ┆ 0.7667    ┆ 76.17     ┆ 0.7614   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by number_of_histones (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5117    ┆ 76.0672   ┆ 0.7598    ┆ … ┆ 0.7667    ┆ 76.17     ┆ 0.7614   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5122    ┆ 76.0781   ┆ 0.7597    ┆ … ┆ 0.7669    ┆ 76.65     ┆ 0.766    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5166    ┆ 76.0472   ┆ 0.7594    ┆ … ┆ 0.7672    ┆ 76.8      ┆ 0.767    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5189    ┆ 75.51     ┆ 0.7552    ┆ … ┆ 0.7605    ┆ 76.25     ┆ 0.762    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5148    ┆ 75.9096   ┆ 0.7595    ┆ … ┆ 0.7661    ┆ 77.34     ┆ 0.7731   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.5455    ┆ 74.5582   ┆ 0.7444    ┆ … ┆ 0.7532    ┆ 75.61     ┆ 0.7542   ┆ 1         │
│ H3K27me3  ┆ 0.6717    ┆ 59.8038   ┆ 0.5932    ┆ … ┆ 0.5943    ┆ 60.46     ┆ 0.5945   ┆ 1         │
│ H3K4me3   ┆ 0.5533    ┆ 73.9408   ┆ 0.7393    ┆ … ┆ 0.74      ┆ 74.85     ┆ 0.7466   ┆ 1         │
│ H3K9ac    ┆ 0.5429    ┆ 74.5118   ┆ 0.7436    ┆ … ┆ 0.7544    ┆ 75.9      ┆ 0.7576   ┆ 1         │
│ H3K9me3   ┆ 0.6964    ┆ 56.7891   ┆ 0.566     ┆ … ┆ 0.5651    ┆ 56.84     ┆ 0.561    ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5117    ┆ 76.0672   ┆ 0.7598    ┆ … ┆ 76.17     ┆ 0.7614   ┆ 5         ┆ 12        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5122    ┆ 76.0781   ┆ 0.7597    ┆ … ┆ 76.65     ┆ 0.766    ┆ 4         ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5166    ┆ 76.0472   ┆ 0.7594    ┆ … ┆ 76.8      ┆ 0.767    ┆ 4         ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5189    ┆ 75.51     ┆ 0.7552    ┆ … ┆ 76.25     ┆ 0.762    ┆ 4         ┆ 10        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5148    ┆ 75.9096   ┆ 0.7595    ┆ … ┆ 77.34     ┆ 0.7731   ┆ 4         ┆ 1         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.5455    ┆ 74.5582   ┆ 0.7444    ┆ … ┆ 75.61     ┆ 0.7542   ┆ 1         ┆ 19        │
│ H3K27me3  ┆ 0.6717    ┆ 59.8038   ┆ 0.5932    ┆ … ┆ 60.46     ┆ 0.5945   ┆ 1         ┆ 30        │
│ H3K4me3   ┆ 0.5533    ┆ 73.9408   ┆ 0.7393    ┆ … ┆ 74.85     ┆ 0.7466   ┆ 1         ┆ 26        │
│ H3K9ac    ┆ 0.5429    ┆ 74.5118   ┆ 0.7436    ┆ … ┆ 75.9      ┆ 0.7576   ┆ 1         ┆ 18        │
│ H3K9me3   ┆ 0.6964    ┆ 56.7891   ┆ 0.566     ┆ … ┆ 56.84     ┆ 0.561    ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save the dataframe as CSV
pl_df.write_csv(os.path.join("E066 ranking.csv"))