In [1]:
import pandas as pd
import numpy as np
from itertools import chain, combinations, permutations
import os
import polars as pl

In [5]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/10_Permutation_Test_Ranking'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/workflow/10_Permutation_Test_Ranking/dataset'

In [3]:
marker_list = ['H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3']

In [4]:
# Get the combination
def powerset(iterable):
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(1, len(s) + 1))

In [5]:
# Get the marker powerset
markers_powerset = list(powerset(marker_list))
markers_powerset

[('H3K4me3',),
 ('H3K9ac',),
 ('H3K9me3',),
 ('H3K27ac',),
 ('H3K27me3',),
 ('H3K4me3', 'H3K9ac'),
 ('H3K4me3', 'H3K9me3'),
 ('H3K4me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3'),
 ('H3K9ac', 'H3K27ac'),
 ('H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3')]

In [6]:
# Permutation of powerset
perm = []

for item in markers_powerset:
    perm.extend(list(permutations(item)))

In [7]:
print(len(perm))
perm

325

[('H3K4me3',),
 ('H3K9ac',),
 ('H3K9me3',),
 ('H3K27ac',),
 ('H3K27me3',),
 ('H3K4me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9me3'),
 ('H3K9me3', 'H3K4me3'),
 ('H3K4me3', 'H3K27ac'),
 ('H3K27ac', 'H3K4me3'),
 ('H3K4me3', 'H3K27me3'),
 ('H3K27me3', 'H3K4me3'),
 ('H3K9ac', 'H3K9me3'),
 ('H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K27ac'),
 ('H3K27ac', 'H3K9ac'),
 ('H3K9ac', 'H3K27me3'),
 ('H3K27me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27ac'),
 ('H3K27ac', 'H3K9me3'),
 ('H3K9me3', 'H3K27me3'),
 ('H3K27me3', 'H3K9me3'),
 ('H3K27ac', 'H3K27me3'),
 ('H3K27me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K9me3'),
 ('H3K9ac', 'H3K9me3', 'H3K4me3'),
 ('H3K9me3', 'H3K4me3', 'H3K9ac'),
 ('H3K9me3', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K27me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27me3', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9me3', 'H3K4me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K27me3', 'H3K9me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27me3'),
 ('H3K9me3', 'H3K27me3', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9me3'),
 ('H3K27me3', 'H3K9me3', 'H3K4me3'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K27me3', 'H3K27ac'),
 ('H3K27ac', 'H3K4me3', 'H3K27me3'),
 ('H3K27ac', 'H3K27me3', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K27ac'),
 ('H3K27me3', 'H3K27ac', 'H3K4me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27ac', 'H3K9me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27ac'),
 ('H3K9me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K9me3'),
 ('H3K27ac', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27me3', 'H3K9me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27me3', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K27me3', 'H3K27ac'),
 ('H3K27ac', 'H3K9ac', 'H3K27me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K27ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27me3', 'H3K27ac'),
 ('H3K27ac', 'H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9me3'),
 ('H3K27me3', 'H3K9me3', 'H3K27ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K9me3'),
 ('H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K9ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K4me3'),
 ('H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K4me3'),
 ('H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27ac'),
 ('H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K4me3'),
 ('H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K4me3'),
 ('H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K9me3'),
 ('H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K9ac'),
 ('H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K9me3'),
 ('H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K4me3'),
 ('H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K4me3'),
 ('H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K9ac'),
 ('H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K4me3'),
 ('H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9ac'),
 ('H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K4me3'),
 ('H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K4me3'),
 ('H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K4me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9me3'),
 ('H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K4me3'),
 ('H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9me3'),
 ('H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K4me3'),
 ('H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K4me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K27ac'),
 ('H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K27me3'),
 ('H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K9ac'),
 ('H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K9me3'),
 ('H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K27ac'),
 ('H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K9me3'),
 ('H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K9ac'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K9me3'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K9me3'),
 ('H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K27ac'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K9ac'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K9ac'),
 ('H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K9me3'),
 ('H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K27me3'),
 ('H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K9ac'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K9ac'),
 ('H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K9me3'),
 ('H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K27ac'),
 ('H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K9ac'),
 ('H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K9me3'),
 ('H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K9ac'),
 ('H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9me3'),
 ('H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K4me3'),
 ('H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K27me3'),
 ('H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K4me3'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K4me3'),
 ('H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9me3'),
 ('H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K4me3'),
 ('H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9me3'),
 ('H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K4me3'),
 ('H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K27ac'),
 ('H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K27me3', 'H3K9ac'),
 ('H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K27ac'),
 ('H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K27me3'),
 ('H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K27ac'),
 ('H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K27ac'),
 ('H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K27ac', 'H3K4me3'),
 ('H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K27me3'),
 ('H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K4me3'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K4me3'),
 ('H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9ac'),
 ('H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K27ac'),
 ('H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K4me3'),
 ('H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9ac'),
 ('H3K9me3', 'H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K4me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K27me3', 'H3K9me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27me3'),
 ('H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K9ac'),
 ('H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27ac', 'H3K4me3', 'H3K27me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K27me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K27me3', 'H3K4me3'),
 ('H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K4me3', 'H3K9me3'),
 ('H3K27ac', 'H3K9ac', 'H3K27me3', 'H3K9me3', 'H3K4me3'),
 ('H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27me3'),
 ('H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K27me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27me3'),
 ('H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K27me3', 'H3K4me3'),
 ('H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27ac', 'H3K9me3', 'H3K27me3', 'H3K9ac', 'H3K4me3'),
 ('H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27ac', 'H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K4me3'),
 ('H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27ac', 'H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K4me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac'),
 ('H3K27me3', 'H3K4me3', 'H3K9ac', 'H3K27ac', 'H3K9me3'),
 ('H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K9ac', 'H3K27ac'),
 ('H3K27me3', 'H3K4me3', 'H3K9me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9ac', 'H3K9me3'),
 ('H3K27me3', 'H3K4me3', 'H3K27ac', 'H3K9me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K9me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9ac', 'H3K4me3', 'H3K27ac', 'H3K9me3'),
 ('H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K4me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K4me3'),
 ('H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27me3', 'H3K9ac', 'H3K27ac', 'H3K9me3', 'H3K4me3'),
 ('H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K9ac', 'H3K27ac'),
 ('H3K27me3', 'H3K9me3', 'H3K4me3', 'H3K27ac', 'H3K9ac'),
 ('H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K4me3', 'H3K27ac'),
 ('H3K27me3', 'H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K4me3'),
 ('H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K4me3', 'H3K9ac'),
 ('H3K27me3', 'H3K9me3', 'H3K27ac', 'H3K9ac', 'H3K4me3'),
 ('H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9ac', 'H3K9me3'),
 ('H3K27me3', 'H3K27ac', 'H3K4me3', 'H3K9me3', 'H3K9ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K4me3', 'H3K9me3'),
 ('H3K27me3', 'H3K27ac', 'H3K9ac', 'H3K9me3', 'H3K4me3'),
 ('H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K4me3', 'H3K9ac'),
 ('H3K27me3', 'H3K27ac', 'H3K9me3', 'H3K9ac', 'H3K4me3')]

In [8]:
df = pd.DataFrame({'markers_perm': perm})
df

                                      markers_perm
0                                       (H3K4me3,)
1                                        (H3K9ac,)
2                                       (H3K9me3,)
3                                       (H3K27ac,)
4                                      (H3K27me3,)
..                                             ...
320  (H3K27me3, H3K27ac, H3K4me3, H3K9me3, H3K9ac)
321  (H3K27me3, H3K27ac, H3K9ac, H3K4me3, H3K9me3)
322  (H3K27me3, H3K27ac, H3K9ac, H3K9me3, H3K4me3)
323  (H3K27me3, H3K27ac, H3K9me3, H3K4me3, H3K9ac)
324  (H3K27me3, H3K27ac, H3K9me3, H3K9ac, H3K4me3)

[325 rows x 1 columns]

In [11]:
# Save the permutation list
df.to_parquet(os.path.join(DATASET_DIR, 'permutation.parquet'))

In [6]:
# Test re-reading the permutation list
test_df = pd.read_parquet(os.path.join(DATASET_DIR, 'permutation.parquet'))

In [7]:
test_df

                                      markers_perm
0                                        [H3K4me3]
1                                         [H3K9ac]
2                                        [H3K9me3]
3                                        [H3K27ac]
4                                       [H3K27me3]
..                                             ...
320  [H3K27me3, H3K27ac, H3K4me3, H3K9me3, H3K9ac]
321  [H3K27me3, H3K27ac, H3K9ac, H3K4me3, H3K9me3]
322  [H3K27me3, H3K27ac, H3K9ac, H3K9me3, H3K4me3]
323  [H3K27me3, H3K27ac, H3K9me3, H3K4me3, H3K9ac]
324  [H3K27me3, H3K27ac, H3K9me3, H3K9ac, H3K4me3]

[325 rows x 1 columns]

In [9]:
test_df.to_csv(os.path.join(DATASET_DIR, 'permutation.csv'))