In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/13_Healthy liver with manual preprocessing/dataset/donor_3"
OUTPUT_PATH  = "/group/pmc021/amunif/epi-thesis/workflow/13_Healthy liver with manual preprocessing/output/donor_3/"

In [3]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.5652    ┆ 73.0129   ┆ 0.7291    ┆ … ┆ 73.3151   ┆ 0.732     ┆ 72.97     ┆ 0.7289   │
│ H3K9ac    ┆ 0.5577    ┆ 73.3201   ┆ 0.7297    ┆ … ┆ 73.7111   ┆ 0.7351    ┆ 73.81     ┆ 0.7359   │
│ H3K9me3   ┆ 0.7151    ┆ 51.2832   ┆ 0.5       ┆ … ┆ 51.7508   ┆ 0.5083    ┆ 51.65     ┆ 0.5063   │
│ H3K27ac   ┆ 0.5485    ┆ 74.3953   ┆ 0.7411    ┆ … ┆ 75.2713   ┆ 0.7514    ┆ 74.79     ┆ 0.7465   │
│ H3K27me3  ┆ 0.693     ┆ 56.3727   ┆ 0.5588    ┆ … ┆ 56.7473   ┆ 0.5595    ┆ 56.31     ┆ 0.5604   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.536     ┆ 74.4833   ┆ 0.7438    ┆ … ┆ 74.773    ┆ 0.7467    ┆ 74.24     ┆ 0.741    │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5233    ┆ 75.4443   ┆ 0.7528    ┆ … ┆ 75.8473   ┆ 0.758     ┆ 75.97     ┆ 0.7586   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5251    ┆ 75.3984   ┆ 0.7524    ┆ … ┆ 75.7558   ┆ 0.7567    ┆ 75.53     ┆ 0.754    │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5299    ┆ 75.0518   ┆ 0.7494    ┆ … ┆ 75.5984   ┆ 0.7545    ┆ 75.39     ┆ 0.7531   │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5212    ┆ 75.5214   ┆ 0.7541    ┆ … ┆ 75.8564   ┆ 0.7575    ┆ 75.84     ┆ 0.7576   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the histone number column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.5652    ┆ 73.0129   ┆ 0.7291    ┆ … ┆ 0.732     ┆ 72.97     ┆ 0.7289   ┆ 1         │
│ H3K9ac    ┆ 0.5577    ┆ 73.3201   ┆ 0.7297    ┆ … ┆ 0.7351    ┆ 73.81     ┆ 0.7359   ┆ 1         │
│ H3K9me3   ┆ 0.7151    ┆ 51.2832   ┆ 0.5       ┆ … ┆ 0.5083    ┆ 51.65     ┆ 0.5063   ┆ 1         │
│ H3K27ac   ┆ 0.5485    ┆ 74.3953   ┆ 0.7411    ┆ … ┆ 0.7514    ┆ 74.79     ┆ 0.7465   ┆ 1         │
│ H3K27me3  ┆ 0.693     ┆ 56.3727   ┆ 0.5588    ┆ … ┆ 0.5595    ┆ 56.31     ┆ 0.5604   ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.536     ┆ 74.4833   ┆ 0.7438    ┆ … ┆ 0.7467    ┆ 74.24     ┆ 0.741    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5233    ┆ 75.4443   ┆ 0.7528    ┆ … ┆ 0.758     ┆ 75.97     ┆ 0.7586   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5251    ┆ 75.3984   ┆ 0.7524    ┆ … ┆ 0.7567    ┆ 75.53     ┆ 0.754    ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5299    ┆ 75.0518   ┆ 0.7494    ┆ … ┆ 0.7545    ┆ 75.39     ┆ 0.7531   ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5212    ┆ 75.5214   ┆ 0.7541    ┆ … ┆ 0.7575    ┆ 75.84     ┆ 0.7576   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by number_of_histones (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5212    ┆ 75.5214   ┆ 0.7541    ┆ … ┆ 0.7575    ┆ 75.84     ┆ 0.7576   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5233    ┆ 75.4443   ┆ 0.7528    ┆ … ┆ 0.758     ┆ 75.97     ┆ 0.7586   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5274    ┆ 75.4188   ┆ 0.7516    ┆ … ┆ 0.756     ┆ 75.54     ┆ 0.7543   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.536     ┆ 74.4833   ┆ 0.7438    ┆ … ┆ 0.7467    ┆ 74.24     ┆ 0.741    ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5251    ┆ 75.3984   ┆ 0.7524    ┆ … ┆ 0.7567    ┆ 75.53     ┆ 0.754    ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.5485    ┆ 74.3953   ┆ 0.7411    ┆ … ┆ 0.7514    ┆ 74.79     ┆ 0.7465   ┆ 1         │
│ H3K27me3  ┆ 0.693     ┆ 56.3727   ┆ 0.5588    ┆ … ┆ 0.5595    ┆ 56.31     ┆ 0.5604   ┆ 1         │
│ H3K4me3   ┆ 0.5652    ┆ 73.0129   ┆ 0.7291    ┆ … ┆ 0.732     ┆ 72.97     ┆ 0.7289   ┆ 1         │
│ H3K9ac    ┆ 0.5577    ┆ 73.3201   ┆ 0.7297    ┆ … ┆ 0.7351    ┆ 73.81     ┆ 0.7359   ┆ 1         │
│ H3K9me3   ┆ 0.7151    ┆ 51.2832   ┆ 0.5       ┆ … ┆ 0.5083    ┆ 51.65     ┆ 0.5063   ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5212    ┆ 75.5214   ┆ 0.7541    ┆ … ┆ 75.84     ┆ 0.7576   ┆ 5         ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5233    ┆ 75.4443   ┆ 0.7528    ┆ … ┆ 75.97     ┆ 0.7586   ┆ 4         ┆ 3         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5274    ┆ 75.4188   ┆ 0.7516    ┆ … ┆ 75.54     ┆ 0.7543   ┆ 4         ┆ 8         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.536     ┆ 74.4833   ┆ 0.7438    ┆ … ┆ 74.24     ┆ 0.741    ┆ 4         ┆ 20        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5251    ┆ 75.3984   ┆ 0.7524    ┆ … ┆ 75.53     ┆ 0.754    ┆ 4         ┆ 10        │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.5485    ┆ 74.3953   ┆ 0.7411    ┆ … ┆ 74.79     ┆ 0.7465   ┆ 1         ┆ 17        │
│ H3K27me3  ┆ 0.693     ┆ 56.3727   ┆ 0.5588    ┆ … ┆ 56.31     ┆ 0.5604   ┆ 1         ┆ 30        │
│ H3K4me3   ┆ 0.5652    ┆ 73.0129   ┆ 0.7291    ┆ … ┆ 72.97     ┆ 0.7289   ┆ 1         ┆ 28        │
│ H3K9ac    ┆ 0.5577    ┆ 73.3201   ┆ 0.7297    ┆ … ┆ 73.81     ┆ 0.7359   ┆ 1         ┆ 24        │
│ H3K9me3   ┆ 0.7151    ┆ 51.2832   ┆ 0.5       ┆ … ┆ 51.65     ┆ 0.5063   ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save the dataframe as CSV
pl_df.write_csv(os.path.join("Donor 3 ranking.csv"))