In [1]:
import polars as pl
import os

In [3]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/dataset"

# Loading the BioMart Dataset

In [28]:
col_names = ['gene_id',
                'external_gene_name',
                'chromosome_name',
                'start_position',
                'end_position',
                'strand']

biomart_df = pl.read_csv(os.path.join(DATASET_PATH, "biomart_response.txt"), new_columns=col_names, separator="\t", has_header=False)

In [29]:
biomart_df

shape: (19_645, 6)
┌─────────────────┬────────────────────┬─────────────────┬────────────────┬──────────────┬────────┐
│ gene_id         ┆ external_gene_name ┆ chromosome_name ┆ start_position ┆ end_position ┆ strand │
│ ---             ┆ ---                ┆ ---             ┆ ---            ┆ ---          ┆ ---    │
│ str             ┆ str                ┆ str             ┆ i64            ┆ i64          ┆ i64    │
╞═════════════════╪════════════════════╪═════════════════╪════════════════╪══════════════╪════════╡
│ ENSG00000000003 ┆ TSPAN6             ┆ X               ┆ 99883667       ┆ 99894988     ┆ -1     │
│ ENSG00000000005 ┆ TNMD               ┆ X               ┆ 99839799       ┆ 99854882     ┆ 1      │
│ ENSG00000000419 ┆ DPM1               ┆ 20              ┆ 49551404       ┆ 49575092     ┆ -1     │
│ ENSG00000000457 ┆ SCYL3              ┆ 1               ┆ 169818772      ┆ 169863408    ┆ -1     │
│ ENSG00000000460 ┆ C1orf112           ┆ 1               ┆ 169631245      ┆ 169823221    ┆ 1      │
│ …               ┆ …                  ┆ …               ┆ …              ┆ …            ┆ …      │
│ ENSG00000259658 ┆ RP11-89K11.1       ┆ 15              ┆ 102277302      ┆ 102285913    ┆ -1     │
│ ENSG00000259664 ┆ CTD-2147F2.2       ┆ 15              ┆ 97913601       ┆ 97971182     ┆ -1     │
│ ENSG00000259680 ┆ RP11-812E19.9      ┆ 16              ┆ 33647044       ┆ 33647696     ┆ -1     │
│ ENSG00000259717 ┆ LINC00677          ┆ 14              ┆ 103587184      ┆ 103589344    ┆ -1     │
│ ENSG00000259752 ┆ FKSG62             ┆ 15              ┆ 47425693       ┆ 47426320     ┆ -1     │
└─────────────────┴────────────────────┴─────────────────┴────────────────┴──────────────┴────────┘

In [30]:
biomart_df.schema

Schema([('gene_id', String),
        ('external_gene_name', String),
        ('chromosome_name', String),
        ('start_position', Int64),
        ('end_position', Int64),
        ('strand', Int64)])

In [31]:
# Calculate the TSS
biomart_df = biomart_df.with_columns(
    pl.when(pl.col("strand") == 1)
      .then(pl.col("start_position"))
      .otherwise(pl.col("end_position"))
      .alias("tss")
)

In [32]:
biomart_df

shape: (19_645, 7)
┌───────────────┬───────────────┬───────────────┬──────────────┬──────────────┬────────┬───────────┐
│ gene_id       ┆ external_gene ┆ chromosome_na ┆ start_positi ┆ end_position ┆ strand ┆ tss       │
│ ---           ┆ _name         ┆ me            ┆ on           ┆ ---          ┆ ---    ┆ ---       │
│ str           ┆ ---           ┆ ---           ┆ ---          ┆ i64          ┆ i64    ┆ i64       │
│               ┆ str           ┆ str           ┆ i64          ┆              ┆        ┆           │
╞═══════════════╪═══════════════╪═══════════════╪══════════════╪══════════════╪════════╪═══════════╡
│ ENSG000000000 ┆ TSPAN6        ┆ X             ┆ 99883667     ┆ 99894988     ┆ -1     ┆ 99894988  │
│ 03            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000000 ┆ TNMD          ┆ X             ┆ 99839799     ┆ 99854882     ┆ 1      ┆ 99839799  │
│ 05            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ DPM1          ┆ 20            ┆ 49551404     ┆ 49575092     ┆ -1     ┆ 49575092  │
│ 19            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ SCYL3         ┆ 1             ┆ 169818772    ┆ 169863408    ┆ -1     ┆ 169863408 │
│ 57            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ C1orf112      ┆ 1             ┆ 169631245    ┆ 169823221    ┆ 1      ┆ 169631245 │
│ 60            ┆               ┆               ┆              ┆              ┆        ┆           │
│ …             ┆ …             ┆ …             ┆ …            ┆ …            ┆ …      ┆ …         │
│ ENSG000002596 ┆ RP11-89K11.1  ┆ 15            ┆ 102277302    ┆ 102285913    ┆ -1     ┆ 102285913 │
│ 58            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002596 ┆ CTD-2147F2.2  ┆ 15            ┆ 97913601     ┆ 97971182     ┆ -1     ┆ 97971182  │
│ 64            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002596 ┆ RP11-812E19.9 ┆ 16            ┆ 33647044     ┆ 33647696     ┆ -1     ┆ 33647696  │
│ 80            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002597 ┆ LINC00677     ┆ 14            ┆ 103587184    ┆ 103589344    ┆ -1     ┆ 103589344 │
│ 17            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002597 ┆ FKSG62        ┆ 15            ┆ 47425693     ┆ 47426320     ┆ -1     ┆ 47426320  │
│ 52            ┆               ┆               ┆              ┆              ┆        ┆           │
└───────────────┴───────────────┴───────────────┴──────────────┴──────────────┴────────┴───────────┘

In [33]:
# Reformat the chromosome name
biomart_df = biomart_df.with_columns(
    pl.format("chr{}", pl.col("chromosome_name")).alias("chromosome_name")
)

In [34]:
biomart_df

shape: (19_645, 7)
┌───────────────┬───────────────┬───────────────┬──────────────┬──────────────┬────────┬───────────┐
│ gene_id       ┆ external_gene ┆ chromosome_na ┆ start_positi ┆ end_position ┆ strand ┆ tss       │
│ ---           ┆ _name         ┆ me            ┆ on           ┆ ---          ┆ ---    ┆ ---       │
│ str           ┆ ---           ┆ ---           ┆ ---          ┆ i64          ┆ i64    ┆ i64       │
│               ┆ str           ┆ str           ┆ i64          ┆              ┆        ┆           │
╞═══════════════╪═══════════════╪═══════════════╪══════════════╪══════════════╪════════╪═══════════╡
│ ENSG000000000 ┆ TSPAN6        ┆ chrX          ┆ 99883667     ┆ 99894988     ┆ -1     ┆ 99894988  │
│ 03            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000000 ┆ TNMD          ┆ chrX          ┆ 99839799     ┆ 99854882     ┆ 1      ┆ 99839799  │
│ 05            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ DPM1          ┆ chr20         ┆ 49551404     ┆ 49575092     ┆ -1     ┆ 49575092  │
│ 19            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ SCYL3         ┆ chr1          ┆ 169818772    ┆ 169863408    ┆ -1     ┆ 169863408 │
│ 57            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000000004 ┆ C1orf112      ┆ chr1          ┆ 169631245    ┆ 169823221    ┆ 1      ┆ 169631245 │
│ 60            ┆               ┆               ┆              ┆              ┆        ┆           │
│ …             ┆ …             ┆ …             ┆ …            ┆ …            ┆ …      ┆ …         │
│ ENSG000002596 ┆ RP11-89K11.1  ┆ chr15         ┆ 102277302    ┆ 102285913    ┆ -1     ┆ 102285913 │
│ 58            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002596 ┆ CTD-2147F2.2  ┆ chr15         ┆ 97913601     ┆ 97971182     ┆ -1     ┆ 97971182  │
│ 64            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002596 ┆ RP11-812E19.9 ┆ chr16         ┆ 33647044     ┆ 33647696     ┆ -1     ┆ 33647696  │
│ 80            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002597 ┆ LINC00677     ┆ chr14         ┆ 103587184    ┆ 103589344    ┆ -1     ┆ 103589344 │
│ 17            ┆               ┆               ┆              ┆              ┆        ┆           │
│ ENSG000002597 ┆ FKSG62        ┆ chr15         ┆ 47425693     ┆ 47426320     ┆ -1     ┆ 47426320  │
│ 52            ┆               ┆               ┆              ┆              ┆        ┆           │
└───────────────┴───────────────┴───────────────┴──────────────┴──────────────┴────────┴───────────┘

# Loading the gene expression dataset

In [35]:
# Read the gene expression dataset
gene_exp_df = pl.read_csv(os.path.join(DATASET_PATH, "57epigenomes.RPKM.pc"), separator='\t', truncate_ragged_lines=True)

In [36]:
gene_exp_df

shape: (19_795, 58)
┌─────────────────┬────────┬────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ gene_id         ┆ E000   ┆ E003   ┆ E004   ┆ … ┆ E122   ┆ E123   ┆ E127   ┆ E128   │
│ ---             ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str             ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64    │
╞═════════════════╪════════╪════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ ENSG00000000003 ┆ 23.265 ┆ 43.985 ┆ 37.413 ┆ … ┆ 43.723 ┆ 0.267  ┆ 13.758 ┆ 15.818 │
│ ENSG00000000005 ┆ 0.872  ┆ 1.642  ┆ 6.498  ┆ … ┆ 0.0    ┆ 0.006  ┆ 0.0    ┆ 0.0    │
│ ENSG00000000419 ┆ 55.208 ┆ 35.259 ┆ 58.308 ┆ … ┆ 16.652 ┆ 73.719 ┆ 56.578 ┆ 56.371 │
│ ENSG00000000457 ┆ 3.237  ┆ 2.596  ┆ 2.345  ┆ … ┆ 2.549  ┆ 7.651  ┆ 4.967  ┆ 3.714  │
│ ENSG00000000460 ┆ 7.299  ┆ 6.649  ┆ 7.838  ┆ … ┆ 4.099  ┆ 22.103 ┆ 3.29   ┆ 2.491  │
│ …               ┆ …      ┆ …      ┆ …      ┆ … ┆ …      ┆ …      ┆ …      ┆ …      │
│ ENSG00000259718 ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ 0.0    │
│ ENSG00000259741 ┆ 17.71  ┆ 10.639 ┆ 22.017 ┆ … ┆ 15.039 ┆ 8.164  ┆ 31.558 ┆ 57.093 │
│ ENSG00000259752 ┆ 0.171  ┆ 0.032  ┆ 0.008  ┆ … ┆ 0.017  ┆ 0.066  ┆ 0.04   ┆ 0.0    │
│ ENSG00000259765 ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ 0.0    │
│ ENSG00000259766 ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ 0.0    │
└─────────────────┴────────┴────────┴────────┴───┴────────┴────────┴────────┴────────┘

In [37]:
# Join with valid gene from biomart
filtered_gene_exp_df = gene_exp_df.join(
    biomart_df,
    on = "gene_id",
    how = "semi"
)

In [38]:
filtered_gene_exp_df

shape: (19_645, 58)
┌─────────────────┬────────┬────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ gene_id         ┆ E000   ┆ E003   ┆ E004   ┆ … ┆ E122   ┆ E123   ┆ E127   ┆ E128   │
│ ---             ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str             ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64    │
╞═════════════════╪════════╪════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ ENSG00000000003 ┆ 23.265 ┆ 43.985 ┆ 37.413 ┆ … ┆ 43.723 ┆ 0.267  ┆ 13.758 ┆ 15.818 │
│ ENSG00000000005 ┆ 0.872  ┆ 1.642  ┆ 6.498  ┆ … ┆ 0.0    ┆ 0.006  ┆ 0.0    ┆ 0.0    │
│ ENSG00000000419 ┆ 55.208 ┆ 35.259 ┆ 58.308 ┆ … ┆ 16.652 ┆ 73.719 ┆ 56.578 ┆ 56.371 │
│ ENSG00000000457 ┆ 3.237  ┆ 2.596  ┆ 2.345  ┆ … ┆ 2.549  ┆ 7.651  ┆ 4.967  ┆ 3.714  │
│ ENSG00000000460 ┆ 7.299  ┆ 6.649  ┆ 7.838  ┆ … ┆ 4.099  ┆ 22.103 ┆ 3.29   ┆ 2.491  │
│ …               ┆ …      ┆ …      ┆ …      ┆ … ┆ …      ┆ …      ┆ …      ┆ …      │
│ ENSG00000259658 ┆ 1.093  ┆ 1.31   ┆ 0.335  ┆ … ┆ 2.024  ┆ 3.524  ┆ 0.19   ┆ 0.824  │
│ ENSG00000259664 ┆ 0.143  ┆ 0.004  ┆ 0.0    ┆ … ┆ 0.0    ┆ 0.004  ┆ 0.0    ┆ 0.0    │
│ ENSG00000259680 ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ 0.0    │
│ ENSG00000259717 ┆ 0.0    ┆ 0.132  ┆ 0.066  ┆ … ┆ 0.007  ┆ 0.074  ┆ 0.0    ┆ 0.011  │
│ ENSG00000259752 ┆ 0.171  ┆ 0.032  ┆ 0.008  ┆ … ┆ 0.017  ┆ 0.066  ┆ 0.04   ┆ 0.0    │
└─────────────────┴────────┴────────┴────────┴───┴────────┴────────┴────────┴────────┘

In [39]:
# Only select the E118 (HepG2)
E118_df = filtered_gene_exp_df.select(["gene_id", "E118"])

In [40]:
E118_df

shape: (19_645, 2)
┌─────────────────┬────────┐
│ gene_id         ┆ E118   │
│ ---             ┆ ---    │
│ str             ┆ f64    │
╞═════════════════╪════════╡
│ ENSG00000000003 ┆ 49.983 │
│ ENSG00000000005 ┆ 0.0    │
│ ENSG00000000419 ┆ 62.811 │
│ ENSG00000000457 ┆ 2.646  │
│ ENSG00000000460 ┆ 3.373  │
│ …               ┆ …      │
│ ENSG00000259658 ┆ 1.842  │
│ ENSG00000259664 ┆ 0.0    │
│ ENSG00000259680 ┆ 0.0    │
│ ENSG00000259717 ┆ 0.0    │
│ ENSG00000259752 ┆ 0.072  │
└─────────────────┴────────┘

# Join with Biomart data

In [41]:
E118_merged_df = E118_df.join(biomart_df, on="gene_id")

In [42]:
E118_merged_df

shape: (19_645, 8)
┌─────────────┬────────┬─────────────┬─────────────┬─────────────┬────────────┬────────┬───────────┐
│ gene_id     ┆ E118   ┆ external_ge ┆ chromosome_ ┆ start_posit ┆ end_positi ┆ strand ┆ tss       │
│ ---         ┆ ---    ┆ ne_name     ┆ name        ┆ ion         ┆ on         ┆ ---    ┆ ---       │
│ str         ┆ f64    ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ i64    ┆ i64       │
│             ┆        ┆ str         ┆ str         ┆ i64         ┆ i64        ┆        ┆           │
╞═════════════╪════════╪═════════════╪═════════════╪═════════════╪════════════╪════════╪═══════════╡
│ ENSG0000000 ┆ 49.983 ┆ TSPAN6      ┆ chrX        ┆ 99883667    ┆ 99894988   ┆ -1     ┆ 99894988  │
│ 0003        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000000 ┆ 0.0    ┆ TNMD        ┆ chrX        ┆ 99839799    ┆ 99854882   ┆ 1      ┆ 99839799  │
│ 0005        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000000 ┆ 62.811 ┆ DPM1        ┆ chr20       ┆ 49551404    ┆ 49575092   ┆ -1     ┆ 49575092  │
│ 0419        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000000 ┆ 2.646  ┆ SCYL3       ┆ chr1        ┆ 169818772   ┆ 169863408  ┆ -1     ┆ 169863408 │
│ 0457        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000000 ┆ 3.373  ┆ C1orf112    ┆ chr1        ┆ 169631245   ┆ 169823221  ┆ 1      ┆ 169631245 │
│ 0460        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ …           ┆ …      ┆ …           ┆ …           ┆ …           ┆ …          ┆ …      ┆ …         │
│ ENSG0000025 ┆ 1.842  ┆ RP11-89K11. ┆ chr15       ┆ 102277302   ┆ 102285913  ┆ -1     ┆ 102285913 │
│ 9658        ┆        ┆ 1           ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000025 ┆ 0.0    ┆ CTD-2147F2. ┆ chr15       ┆ 97913601    ┆ 97971182   ┆ -1     ┆ 97971182  │
│ 9664        ┆        ┆ 2           ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000025 ┆ 0.0    ┆ RP11-812E19 ┆ chr16       ┆ 33647044    ┆ 33647696   ┆ -1     ┆ 33647696  │
│ 9680        ┆        ┆ .9          ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000025 ┆ 0.0    ┆ LINC00677   ┆ chr14       ┆ 103587184   ┆ 103589344  ┆ -1     ┆ 103589344 │
│ 9717        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
│ ENSG0000025 ┆ 0.072  ┆ FKSG62      ┆ chr15       ┆ 47425693    ┆ 47426320   ┆ -1     ┆ 47426320  │
│ 9752        ┆        ┆             ┆             ┆             ┆            ┆        ┆           │
└─────────────┴────────┴─────────────┴─────────────┴─────────────┴────────────┴────────┴───────────┘

# Preparing dataset for bedtools intersect

In [46]:
# Find the +/- 5,000 bp location from TSS
# Make sure that the start is smaller than the end

E118_merged_df = E118_merged_df.with_columns(
    (pl.col("tss") - 5000).alias("start"),
    (pl.col("tss") + 5000).alias("end")
)

In [47]:
E118_merged_df

shape: (19_645, 10)
┌─────────────┬────────┬─────────────┬────────────┬───┬────────┬───────────┬───────────┬───────────┐
│ gene_id     ┆ E118   ┆ external_ge ┆ chromosome ┆ … ┆ strand ┆ tss       ┆ start     ┆ end       │
│ ---         ┆ ---    ┆ ne_name     ┆ _name      ┆   ┆ ---    ┆ ---       ┆ ---       ┆ ---       │
│ str         ┆ f64    ┆ ---         ┆ ---        ┆   ┆ i64    ┆ i64       ┆ i64       ┆ i64       │
│             ┆        ┆ str         ┆ str        ┆   ┆        ┆           ┆           ┆           │
╞═════════════╪════════╪═════════════╪════════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ ENSG0000000 ┆ 49.983 ┆ TSPAN6      ┆ chrX       ┆ … ┆ -1     ┆ 99894988  ┆ 99889988  ┆ 99899988  │
│ 0003        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000000 ┆ 0.0    ┆ TNMD        ┆ chrX       ┆ … ┆ 1      ┆ 99839799  ┆ 99834799  ┆ 99844799  │
│ 0005        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000000 ┆ 62.811 ┆ DPM1        ┆ chr20      ┆ … ┆ -1     ┆ 49575092  ┆ 49570092  ┆ 49580092  │
│ 0419        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000000 ┆ 2.646  ┆ SCYL3       ┆ chr1       ┆ … ┆ -1     ┆ 169863408 ┆ 169858408 ┆ 169868408 │
│ 0457        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000000 ┆ 3.373  ┆ C1orf112    ┆ chr1       ┆ … ┆ 1      ┆ 169631245 ┆ 169626245 ┆ 169636245 │
│ 0460        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ …           ┆ …      ┆ …           ┆ …          ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ ENSG0000025 ┆ 1.842  ┆ RP11-89K11. ┆ chr15      ┆ … ┆ -1     ┆ 102285913 ┆ 102280913 ┆ 102290913 │
│ 9658        ┆        ┆ 1           ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000025 ┆ 0.0    ┆ CTD-2147F2. ┆ chr15      ┆ … ┆ -1     ┆ 97971182  ┆ 97966182  ┆ 97976182  │
│ 9664        ┆        ┆ 2           ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000025 ┆ 0.0    ┆ RP11-812E19 ┆ chr16      ┆ … ┆ -1     ┆ 33647696  ┆ 33642696  ┆ 33652696  │
│ 9680        ┆        ┆ .9          ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000025 ┆ 0.0    ┆ LINC00677   ┆ chr14      ┆ … ┆ -1     ┆ 103589344 ┆ 103584344 ┆ 103594344 │
│ 9717        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
│ ENSG0000025 ┆ 0.072  ┆ FKSG62      ┆ chr15      ┆ … ┆ -1     ┆ 47426320  ┆ 47421320  ┆ 47431320  │
│ 9752        ┆        ┆             ┆            ┆   ┆        ┆           ┆           ┆           │
└─────────────┴────────┴─────────────┴────────────┴───┴────────┴───────────┴───────────┴───────────┘

In [48]:
E118_merged_df.schema

Schema([('gene_id', String),
        ('E118', Float64),
        ('external_gene_name', String),
        ('chromosome_name', String),
        ('start_position', Int64),
        ('end_position', Int64),
        ('strand', Int64),
        ('tss', Int64),
        ('start', Int64),
        ('end', Int64)])

In [49]:
# Reorder the column
E118_merged_df = E118_merged_df.select([
    "chromosome_name",
    "start",
    "end",
    "gene_id",
    "E118",
    "strand",
    "external_gene_name",
    "start_position",
    "end_position",
    "tss"
])

In [50]:
E118_merged_df

shape: (19_645, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chromosom ┆ start     ┆ end       ┆ gene_id   ┆ … ┆ external_ ┆ start_pos ┆ end_posit ┆ tss      │
│ e_name    ┆ ---       ┆ ---       ┆ ---       ┆   ┆ gene_name ┆ ition     ┆ ion       ┆ ---      │
│ ---       ┆ i64       ┆ i64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64      │
│ str       ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chrX      ┆ 99889988  ┆ 99899988  ┆ ENSG00000 ┆ … ┆ TSPAN6    ┆ 99883667  ┆ 99894988  ┆ 99894988 │
│           ┆           ┆           ┆ 000003    ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 99834799  ┆ 99844799  ┆ ENSG00000 ┆ … ┆ TNMD      ┆ 99839799  ┆ 99854882  ┆ 99839799 │
│           ┆           ┆           ┆ 000005    ┆   ┆           ┆           ┆           ┆          │
│ chr20     ┆ 49570092  ┆ 49580092  ┆ ENSG00000 ┆ … ┆ DPM1      ┆ 49551404  ┆ 49575092  ┆ 49575092 │
│           ┆           ┆           ┆ 000419    ┆   ┆           ┆           ┆           ┆          │
│ chr1      ┆ 169858408 ┆ 169868408 ┆ ENSG00000 ┆ … ┆ SCYL3     ┆ 169818772 ┆ 169863408 ┆ 16986340 │
│           ┆           ┆           ┆ 000457    ┆   ┆           ┆           ┆           ┆ 8        │
│ chr1      ┆ 169626245 ┆ 169636245 ┆ ENSG00000 ┆ … ┆ C1orf112  ┆ 169631245 ┆ 169823221 ┆ 16963124 │
│           ┆           ┆           ┆ 000460    ┆   ┆           ┆           ┆           ┆ 5        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chr15     ┆ 102280913 ┆ 102290913 ┆ ENSG00000 ┆ … ┆ RP11-89K1 ┆ 102277302 ┆ 102285913 ┆ 10228591 │
│           ┆           ┆           ┆ 259658    ┆   ┆ 1.1       ┆           ┆           ┆ 3        │
│ chr15     ┆ 97966182  ┆ 97976182  ┆ ENSG00000 ┆ … ┆ CTD-2147F ┆ 97913601  ┆ 97971182  ┆ 97971182 │
│           ┆           ┆           ┆ 259664    ┆   ┆ 2.2       ┆           ┆           ┆          │
│ chr16     ┆ 33642696  ┆ 33652696  ┆ ENSG00000 ┆ … ┆ RP11-812E ┆ 33647044  ┆ 33647696  ┆ 33647696 │
│           ┆           ┆           ┆ 259680    ┆   ┆ 19.9      ┆           ┆           ┆          │
│ chr14     ┆ 103584344 ┆ 103594344 ┆ ENSG00000 ┆ … ┆ LINC00677 ┆ 103587184 ┆ 103589344 ┆ 10358934 │
│           ┆           ┆           ┆ 259717    ┆   ┆           ┆           ┆           ┆ 4        │
│ chr15     ┆ 47421320  ┆ 47431320  ┆ ENSG00000 ┆ … ┆ FKSG62    ┆ 47425693  ┆ 47426320  ┆ 47426320 │
│           ┆           ┆           ┆ 259752    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [52]:
E118_merged_df.write_csv(
    os.path.join(DATASET_PATH, "E118.bed"),
    separator = "\t",
    include_header = False
)