In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/dataset/"
OUTPUT_PATH = '/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/output/'

In [3]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.53      ┆ 75.3025   ┆ 0.7496    ┆ … ┆ 76.504    ┆ 0.7627    ┆ 76.88     ┆ 0.7658   │
│ H3K9ac    ┆ 0.4971    ┆ 77.5583   ┆ 0.7708    ┆ … ┆ 77.9631   ┆ 0.7763    ┆ 78.35     ┆ 0.7816   │
│ H3K9me3   ┆ 0.7114    ┆ 52.6685   ┆ 0.5098    ┆ … ┆ 52.5487   ┆ 0.5104    ┆ 52.67     ┆ 0.5116   │
│ H3K27ac   ┆ 0.5298    ┆ 75.3596   ┆ 0.7496    ┆ … ┆ 76.0448   ┆ 0.7567    ┆ 76.04     ┆ 0.7562   │
│ H3K27me3  ┆ 0.6537    ┆ 64.8831   ┆ 0.6466    ┆ … ┆ 64.5342   ┆ 0.6435    ┆ 64.95     ┆ 0.6474   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.4809    ┆ 77.7566   ┆ 0.7774    ┆ … ┆ 78.3963   ┆ 0.7821    ┆ 78.46     ┆ 0.7827   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.4744    ┆ 78.1409   ┆ 0.7793    ┆ … ┆ 78.5935   ┆ 0.7844    ┆ 78.82     ┆ 0.7858   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.4841    ┆ 77.5903   ┆ 0.7739    ┆ … ┆ 78.2694   ┆ 0.7811    ┆ 77.83     ┆ 0.777    │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.4775    ┆ 77.7801   ┆ 0.7783    ┆ … ┆ 78.3813   ┆ 0.7821    ┆ 78.64     ┆ 0.7834   │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.4764    ┆ 77.964    ┆ 0.7793    ┆ … ┆ 78.6916   ┆ 0.7854    ┆ 79.73     ┆ 0.7964   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the histone number column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.53      ┆ 75.3025   ┆ 0.7496    ┆ … ┆ 0.7627    ┆ 76.88     ┆ 0.7658   ┆ 1         │
│ H3K9ac    ┆ 0.4971    ┆ 77.5583   ┆ 0.7708    ┆ … ┆ 0.7763    ┆ 78.35     ┆ 0.7816   ┆ 1         │
│ H3K9me3   ┆ 0.7114    ┆ 52.6685   ┆ 0.5098    ┆ … ┆ 0.5104    ┆ 52.67     ┆ 0.5116   ┆ 1         │
│ H3K27ac   ┆ 0.5298    ┆ 75.3596   ┆ 0.7496    ┆ … ┆ 0.7567    ┆ 76.04     ┆ 0.7562   ┆ 1         │
│ H3K27me3  ┆ 0.6537    ┆ 64.8831   ┆ 0.6466    ┆ … ┆ 0.6435    ┆ 64.95     ┆ 0.6474   ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.4809    ┆ 77.7566   ┆ 0.7774    ┆ … ┆ 0.7821    ┆ 78.46     ┆ 0.7827   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4744    ┆ 78.1409   ┆ 0.7793    ┆ … ┆ 0.7844    ┆ 78.82     ┆ 0.7858   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4841    ┆ 77.5903   ┆ 0.7739    ┆ … ┆ 0.7811    ┆ 77.83     ┆ 0.777    ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.4775    ┆ 77.7801   ┆ 0.7783    ┆ … ┆ 0.7821    ┆ 78.64     ┆ 0.7834   ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4764    ┆ 77.964    ┆ 0.7793    ┆ … ┆ 0.7854    ┆ 79.73     ┆ 0.7964   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by number_of_histones (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.4764    ┆ 77.964    ┆ 0.7793    ┆ … ┆ 0.7854    ┆ 79.73     ┆ 0.7964   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4744    ┆ 78.1409   ┆ 0.7793    ┆ … ┆ 0.7844    ┆ 78.82     ┆ 0.7858   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4833    ┆ 77.904    ┆ 0.7791    ┆ … ┆ 0.7827    ┆ 78.28     ┆ 0.7816   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4809    ┆ 77.7566   ┆ 0.7774    ┆ … ┆ 0.7821    ┆ 78.46     ┆ 0.7827   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.4841    ┆ 77.5903   ┆ 0.7739    ┆ … ┆ 0.7811    ┆ 77.83     ┆ 0.777    ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.5298    ┆ 75.3596   ┆ 0.7496    ┆ … ┆ 0.7567    ┆ 76.04     ┆ 0.7562   ┆ 1         │
│ H3K27me3  ┆ 0.6537    ┆ 64.8831   ┆ 0.6466    ┆ … ┆ 0.6435    ┆ 64.95     ┆ 0.6474   ┆ 1         │
│ H3K4me3   ┆ 0.53      ┆ 75.3025   ┆ 0.7496    ┆ … ┆ 0.7627    ┆ 76.88     ┆ 0.7658   ┆ 1         │
│ H3K9ac    ┆ 0.4971    ┆ 77.5583   ┆ 0.7708    ┆ … ┆ 0.7763    ┆ 78.35     ┆ 0.7816   ┆ 1         │
│ H3K9me3   ┆ 0.7114    ┆ 52.6685   ┆ 0.5098    ┆ … ┆ 0.5104    ┆ 52.67     ┆ 0.5116   ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.4764    ┆ 77.964    ┆ 0.7793    ┆ … ┆ 79.73     ┆ 0.7964   ┆ 5         ┆ 1         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.4744    ┆ 78.1409   ┆ 0.7793    ┆ … ┆ 78.82     ┆ 0.7858   ┆ 4         ┆ 2         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.4833    ┆ 77.904    ┆ 0.7791    ┆ … ┆ 78.28     ┆ 0.7816   ┆ 4         ┆ 13        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.4809    ┆ 77.7566   ┆ 0.7774    ┆ … ┆ 78.46     ┆ 0.7827   ┆ 4         ┆ 7         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.4841    ┆ 77.5903   ┆ 0.7739    ┆ … ┆ 77.83     ┆ 0.777    ┆ 4         ┆ 20        │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.5298    ┆ 75.3596   ┆ 0.7496    ┆ … ┆ 76.04     ┆ 0.7562   ┆ 1         ┆ 24        │
│ H3K27me3  ┆ 0.6537    ┆ 64.8831   ┆ 0.6466    ┆ … ┆ 64.95     ┆ 0.6474   ┆ 1         ┆ 30        │
│ H3K4me3   ┆ 0.53      ┆ 75.3025   ┆ 0.7496    ┆ … ┆ 76.88     ┆ 0.7658   ┆ 1         ┆ 22        │
│ H3K9ac    ┆ 0.4971    ┆ 77.5583   ┆ 0.7708    ┆ … ┆ 78.35     ┆ 0.7816   ┆ 1         ┆ 10        │
│ H3K9me3   ┆ 0.7114    ┆ 52.6685   ┆ 0.5098    ┆ … ┆ 52.67     ┆ 0.5116   ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [11]:
# Save the dataframe as CSV
pl_df.write_csv(os.path.join("E188 ranking.csv"))