In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/dataset/'
OUTPUT_PATH = '/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/output/'

In [3]:
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.6009    ┆ 69.9298   ┆ 0.6964    ┆ … ┆ 69.7361   ┆ 0.6925    ┆ 69.8      ┆ 0.695    │
│ H3K9ac    ┆ 0.5875    ┆ 71.6901   ┆ 0.7102    ┆ … ┆ 71.3727   ┆ 0.7088    ┆ 71.53     ┆ 0.7099   │
│ H3K9me3   ┆ 0.7115    ┆ 53.1884   ┆ 0.5098    ┆ … ┆ 53.177    ┆ 0.5071    ┆ 52.6      ┆ 0.5035   │
│ H3K27ac   ┆ 0.615     ┆ 69.8582   ┆ 0.6907    ┆ … ┆ 70.4327   ┆ 0.6973    ┆ 70.5      ┆ 0.6988   │
│ H3K27me3  ┆ 0.6762    ┆ 62.2164   ┆ 0.6161    ┆ … ┆ 62.3658   ┆ 0.6179    ┆ 63.24     ┆ 0.6268   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.5737    ┆ 71.8729   ┆ 0.7174    ┆ … ┆ 71.4615   ┆ 0.7109    ┆ 72.07     ┆ 0.7164   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5726    ┆ 71.9379   ┆ 0.7174    ┆ … ┆ 71.6993   ┆ 0.7128    ┆ 71.39     ┆ 0.7097   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5766    ┆ 71.6463   ┆ 0.7134    ┆ … ┆ 71.5348   ┆ 0.7123    ┆ 72.06     ┆ 0.7172   │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5777    ┆ 71.7502   ┆ 0.7132    ┆ … ┆ 71.7139   ┆ 0.7122    ┆ 72.43     ┆ 0.7196   │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5724    ┆ 71.9259   ┆ 0.7172    ┆ … ┆ 71.5849   ┆ 0.7125    ┆ 71.48     ┆ 0.7103   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the number of histones column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.6009    ┆ 69.9298   ┆ 0.6964    ┆ … ┆ 0.6925    ┆ 69.8      ┆ 0.695    ┆ 1         │
│ H3K9ac    ┆ 0.5875    ┆ 71.6901   ┆ 0.7102    ┆ … ┆ 0.7088    ┆ 71.53     ┆ 0.7099   ┆ 1         │
│ H3K9me3   ┆ 0.7115    ┆ 53.1884   ┆ 0.5098    ┆ … ┆ 0.5071    ┆ 52.6      ┆ 0.5035   ┆ 1         │
│ H3K27ac   ┆ 0.615     ┆ 69.8582   ┆ 0.6907    ┆ … ┆ 0.6973    ┆ 70.5      ┆ 0.6988   ┆ 1         │
│ H3K27me3  ┆ 0.6762    ┆ 62.2164   ┆ 0.6161    ┆ … ┆ 0.6179    ┆ 63.24     ┆ 0.6268   ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.5737    ┆ 71.8729   ┆ 0.7174    ┆ … ┆ 0.7109    ┆ 72.07     ┆ 0.7164   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5726    ┆ 71.9379   ┆ 0.7174    ┆ … ┆ 0.7128    ┆ 71.39     ┆ 0.7097   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5766    ┆ 71.6463   ┆ 0.7134    ┆ … ┆ 0.7123    ┆ 72.06     ┆ 0.7172   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5777    ┆ 71.7502   ┆ 0.7132    ┆ … ┆ 0.7122    ┆ 72.43     ┆ 0.7196   ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5724    ┆ 71.9259   ┆ 0.7172    ┆ … ┆ 0.7125    ┆ 71.48     ┆ 0.7103   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by histone_number (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5724    ┆ 71.9259   ┆ 0.7172    ┆ … ┆ 0.7125    ┆ 71.48     ┆ 0.7103   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5726    ┆ 71.9379   ┆ 0.7174    ┆ … ┆ 0.7128    ┆ 71.39     ┆ 0.7097   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5757    ┆ 71.9016   ┆ 0.7156    ┆ … ┆ 0.7115    ┆ 71.31     ┆ 0.7099   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5737    ┆ 71.8729   ┆ 0.7174    ┆ … ┆ 0.7109    ┆ 72.07     ┆ 0.7164   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5766    ┆ 71.6463   ┆ 0.7134    ┆ … ┆ 0.7123    ┆ 72.06     ┆ 0.7172   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.615     ┆ 69.8582   ┆ 0.6907    ┆ … ┆ 0.6973    ┆ 70.5      ┆ 0.6988   ┆ 1         │
│ H3K27me3  ┆ 0.6762    ┆ 62.2164   ┆ 0.6161    ┆ … ┆ 0.6179    ┆ 63.24     ┆ 0.6268   ┆ 1         │
│ H3K4me3   ┆ 0.6009    ┆ 69.9298   ┆ 0.6964    ┆ … ┆ 0.6925    ┆ 69.8      ┆ 0.695    ┆ 1         │
│ H3K9ac    ┆ 0.5875    ┆ 71.6901   ┆ 0.7102    ┆ … ┆ 0.7088    ┆ 71.53     ┆ 0.7099   ┆ 1         │
│ H3K9me3   ┆ 0.7115    ┆ 53.1884   ┆ 0.5098    ┆ … ┆ 0.5071    ┆ 52.6      ┆ 0.5035   ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5724    ┆ 71.9259   ┆ 0.7172    ┆ … ┆ 71.48     ┆ 0.7103   ┆ 5         ┆ 8         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5726    ┆ 71.9379   ┆ 0.7174    ┆ … ┆ 71.39     ┆ 0.7097   ┆ 4         ┆ 10        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5757    ┆ 71.9016   ┆ 0.7156    ┆ … ┆ 71.31     ┆ 0.7099   ┆ 4         ┆ 14        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5737    ┆ 71.8729   ┆ 0.7174    ┆ … ┆ 72.07     ┆ 0.7164   ┆ 4         ┆ 2         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5766    ┆ 71.6463   ┆ 0.7134    ┆ … ┆ 72.06     ┆ 0.7172   ┆ 4         ┆ 3         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.615     ┆ 69.8582   ┆ 0.6907    ┆ … ┆ 70.5      ┆ 0.6988   ┆ 1         ┆ 21        │
│ H3K27me3  ┆ 0.6762    ┆ 62.2164   ┆ 0.6161    ┆ … ┆ 63.24     ┆ 0.6268   ┆ 1         ┆ 29        │
│ H3K4me3   ┆ 0.6009    ┆ 69.9298   ┆ 0.6964    ┆ … ┆ 69.8      ┆ 0.695    ┆ 1         ┆ 27        │
│ H3K9ac    ┆ 0.5875    ┆ 71.6901   ┆ 0.7102    ┆ … ┆ 71.53     ┆ 0.7099   ┆ 1         ┆ 7         │
│ H3K9me3   ┆ 0.7115    ┆ 53.1884   ┆ 0.5098    ┆ … ┆ 52.6      ┆ 0.5035   ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save to CSV
pl_df.write_csv(os.path.join("HepG2 with DeepChrome preprocessing.csv"))