In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/14_E066 with alignment dataset/dataset"
OUTPUT_PATH = '/group/pmc021/amunif/epi-thesis/workflow/14_E066 with alignment dataset/output/'

In [3]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.5502    ┆ 74.1928   ┆ 0.7395    ┆ … ┆ 74.5418   ┆ 0.7441    ┆ 74.31     ┆ 0.7419   │
│ H3K9ac    ┆ 0.5461    ┆ 74.3065   ┆ 0.74      ┆ … ┆ 75.1538   ┆ 0.7501    ┆ 75.15     ┆ 0.7489   │
│ H3K9me3   ┆ 0.7106    ┆ 53.6834   ┆ 0.5304    ┆ … ┆ 54.4341   ┆ 0.5347    ┆ 54.94     ┆ 0.544    │
│ H3K27ac   ┆ 0.5493    ┆ 74.5167   ┆ 0.7424    ┆ … ┆ 75.1157   ┆ 0.7496    ┆ 75.47     ┆ 0.7519   │
│ H3K27me3  ┆ 0.6834    ┆ 58.5656   ┆ 0.5806    ┆ … ┆ 59.2656   ┆ 0.5844    ┆ 60.19     ┆ 0.593    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.5323    ┆ 74.975    ┆ 0.7493    ┆ … ┆ 75.598    ┆ 0.7553    ┆ 75.67     ┆ 0.7555   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5194    ┆ 75.6931   ┆ 0.758     ┆ … ┆ 76.2113   ┆ 0.7612    ┆ 75.99     ┆ 0.7593   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5219    ┆ 75.4747   ┆ 0.7538    ┆ … ┆ 76.0997   ┆ 0.7603    ┆ 76.25     ┆ 0.7607   │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5264    ┆ 75.2001   ┆ 0.7498    ┆ … ┆ 76.0294   ┆ 0.7594    ┆ 76.08     ┆ 0.76     │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.518     ┆ 75.6928   ┆ 0.7579    ┆ … ┆ 76.2617   ┆ 0.7619    ┆ 76.52     ┆ 0.7644   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the histone number column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.5502    ┆ 74.1928   ┆ 0.7395    ┆ … ┆ 0.7441    ┆ 74.31     ┆ 0.7419   ┆ 1         │
│ H3K9ac    ┆ 0.5461    ┆ 74.3065   ┆ 0.74      ┆ … ┆ 0.7501    ┆ 75.15     ┆ 0.7489   ┆ 1         │
│ H3K9me3   ┆ 0.7106    ┆ 53.6834   ┆ 0.5304    ┆ … ┆ 0.5347    ┆ 54.94     ┆ 0.544    ┆ 1         │
│ H3K27ac   ┆ 0.5493    ┆ 74.5167   ┆ 0.7424    ┆ … ┆ 0.7496    ┆ 75.47     ┆ 0.7519   ┆ 1         │
│ H3K27me3  ┆ 0.6834    ┆ 58.5656   ┆ 0.5806    ┆ … ┆ 0.5844    ┆ 60.19     ┆ 0.593    ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.5323    ┆ 74.975    ┆ 0.7493    ┆ … ┆ 0.7553    ┆ 75.67     ┆ 0.7555   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5194    ┆ 75.6931   ┆ 0.758     ┆ … ┆ 0.7612    ┆ 75.99     ┆ 0.7593   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5219    ┆ 75.4747   ┆ 0.7538    ┆ … ┆ 0.7603    ┆ 76.25     ┆ 0.7607   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5264    ┆ 75.2001   ┆ 0.7498    ┆ … ┆ 0.7594    ┆ 76.08     ┆ 0.76     ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.518     ┆ 75.6928   ┆ 0.7579    ┆ … ┆ 0.7619    ┆ 76.52     ┆ 0.7644   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by number_of_histones (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.518     ┆ 75.6928   ┆ 0.7579    ┆ … ┆ 0.7619    ┆ 76.52     ┆ 0.7644   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5194    ┆ 75.6931   ┆ 0.758     ┆ … ┆ 0.7612    ┆ 75.99     ┆ 0.7593   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5195    ┆ 75.761    ┆ 0.7585    ┆ … ┆ 0.763     ┆ 76.2      ┆ 0.7616   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5323    ┆ 74.975    ┆ 0.7493    ┆ … ┆ 0.7553    ┆ 75.67     ┆ 0.7555   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5219    ┆ 75.4747   ┆ 0.7538    ┆ … ┆ 0.7603    ┆ 76.25     ┆ 0.7607   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.5493    ┆ 74.5167   ┆ 0.7424    ┆ … ┆ 0.7496    ┆ 75.47     ┆ 0.7519   ┆ 1         │
│ H3K27me3  ┆ 0.6834    ┆ 58.5656   ┆ 0.5806    ┆ … ┆ 0.5844    ┆ 60.19     ┆ 0.593    ┆ 1         │
│ H3K4me3   ┆ 0.5502    ┆ 74.1928   ┆ 0.7395    ┆ … ┆ 0.7441    ┆ 74.31     ┆ 0.7419   ┆ 1         │
│ H3K9ac    ┆ 0.5461    ┆ 74.3065   ┆ 0.74      ┆ … ┆ 0.7501    ┆ 75.15     ┆ 0.7489   ┆ 1         │
│ H3K9me3   ┆ 0.7106    ┆ 53.6834   ┆ 0.5304    ┆ … ┆ 0.5347    ┆ 54.94     ┆ 0.544    ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.518     ┆ 75.6928   ┆ 0.7579    ┆ … ┆ 76.52     ┆ 0.7644   ┆ 5         ┆ 2         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5194    ┆ 75.6931   ┆ 0.758     ┆ … ┆ 75.99     ┆ 0.7593   ┆ 4         ┆ 10        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5195    ┆ 75.761    ┆ 0.7585    ┆ … ┆ 76.2      ┆ 0.7616   ┆ 4         ┆ 7         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5323    ┆ 74.975    ┆ 0.7493    ┆ … ┆ 75.67     ┆ 0.7555   ┆ 4         ┆ 14        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5219    ┆ 75.4747   ┆ 0.7538    ┆ … ┆ 76.25     ┆ 0.7607   ┆ 4         ┆ 6         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.5493    ┆ 74.5167   ┆ 0.7424    ┆ … ┆ 75.47     ┆ 0.7519   ┆ 1         ┆ 19        │
│ H3K27me3  ┆ 0.6834    ┆ 58.5656   ┆ 0.5806    ┆ … ┆ 60.19     ┆ 0.593    ┆ 1         ┆ 30        │
│ H3K4me3   ┆ 0.5502    ┆ 74.1928   ┆ 0.7395    ┆ … ┆ 74.31     ┆ 0.7419   ┆ 1         ┆ 28        │
│ H3K9ac    ┆ 0.5461    ┆ 74.3065   ┆ 0.74      ┆ … ┆ 75.15     ┆ 0.7489   ┆ 1         ┆ 22        │
│ H3K9me3   ┆ 0.7106    ┆ 53.6834   ┆ 0.5304    ┆ … ┆ 54.94     ┆ 0.544    ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save the dataframe as CSV
pl_df.write_csv(os.path.join("E066 ranking.csv"))