In [1]:
import os
import polars as pl

In [2]:
DATASET_PATH = '/mmfs1/data/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [3]:
DATASET_PATH

'/mmfs1/data/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [4]:
def read_gappedPeak(filename):
    # Define the columns
    cols = [
        "chrom", "chromStart", "chromEnd", "name", "score", "strand",
        "thickStart", "thickEnd", "itemRgb", "blockCount", "blockSizes",
        "blockStarts", "signalValue", "pValue", "qValue"
    ]
    
    # Read the file
    gappedpeak_df = pl.read_csv(
        filename,
        separator="\t",
        has_header=False,
        new_columns=cols
    )
    
    # Return the dataframe
    return gappedpeak_df

In [5]:
def read_histone(filename):
    # Define the columns
    cols = ["chrom", "chromStart", "chromEnd", "name"]
    
    # Read the histone file
    histone_df = pl.read_csv(
        filename,
        separator="\t",
        has_header=False,
        new_columns=cols
    )

    # Return the dataframe
    return histone_df

# Open the original histone peak dataset

In [6]:
current_histone = "H3K9ac"

In [7]:
H3K9ac_gp_df = read_gappedPeak(os.path.join(DATASET_PATH, f'{current_histone}_peaks.gappedPeak'))

In [8]:
H3K9ac_gp_df

shape: (60_172, 15)
┌───────┬────────────┬──────────┬──────────────┬───┬─────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         ┆ … ┆ blockStarts ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---      ┆ ---          ┆   ┆ ---         ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64      ┆ str          ┆   ┆ str         ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪══════════╪══════════════╪═══╪═════════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 10096      ┆ 10603    ┆ H3K9ac_peak_ ┆ … ┆ 0,5,506     ┆ 4.09313     ┆ 6.03177 ┆ 3.96029 │
│       ┆            ┆          ┆ 1            ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 20034      ┆ 20201    ┆ H3K9ac_peak_ ┆ … ┆ 0,5,166     ┆ 5.68434     ┆ 9.82363 ┆ 7.62363 │
│       ┆            ┆          ┆ 2            ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 569825     ┆ 570030   ┆ H3K9ac_peak_ ┆ … ┆ 0,204       ┆ 2.61768     ┆ 4.51941 ┆ 2.52068 │
│       ┆            ┆          ┆ 3            ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 661812     ┆ 662015   ┆ H3K9ac_peak_ ┆ … ┆ 0,1,202     ┆ 7.11663     ┆ 14.0947 ┆ 11.8198 │
│       ┆            ┆          ┆ 4            ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 662503     ┆ 662756   ┆ H3K9ac_peak_ ┆ … ┆ 0,3,252     ┆ 9.41397     ┆ 21.5198 ┆ 19.1332 │
│       ┆            ┆          ┆ 5            ┆   ┆             ┆             ┆         ┆         │
│ …     ┆ …          ┆ …        ┆ …            ┆ … ┆ …           ┆ …           ┆ …       ┆ …       │
│ chrY  ┆ 58827236   ┆ 58827468 ┆ H3K9ac_peak_ ┆ … ┆ 0,1,231     ┆ 7.31989     ┆ 29.9    ┆ 27.3921 │
│       ┆            ┆          ┆ 60168        ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 58848053   ┆ 58848252 ┆ H3K9ac_peak_ ┆ … ┆ 0,3,198     ┆ 7.8313      ┆ 16.2446 ┆ 13.9307 │
│       ┆            ┆          ┆ 60169        ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 58855971   ┆ 58856188 ┆ H3K9ac_peak_ ┆ … ┆ 0,1,216     ┆ 3.55726     ┆ 12.3265 ┆ 10.0759 │
│       ┆            ┆          ┆ 60170        ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 58862614   ┆ 58863092 ┆ H3K9ac_peak_ ┆ … ┆ 0,1,477     ┆ 5.76828     ┆ 15.6004 ┆ 13.3656 │
│       ┆            ┆          ┆ 60171        ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 58979340   ┆ 58979535 ┆ H3K9ac_peak_ ┆ … ┆ 0,194       ┆ 1.96439     ┆ 4.32165 ┆ 2.33589 │
│       ┆            ┆          ┆ 60172        ┆   ┆             ┆             ┆         ┆         │
└───────┴────────────┴──────────┴──────────────┴───┴─────────────┴─────────────┴─────────┴─────────┘

In [9]:
H3K9ac_gp_df.describe()

shape: (9, 16)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ chrom ┆ chromStart ┆ chromEnd   ┆ … ┆ blockStar ┆ signalVal ┆ pValue    ┆ qValue    │
│ ---        ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ts        ┆ ue        ┆ ---       ┆ ---       │
│ str        ┆ str   ┆ f64        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ str       ┆ f64       ┆           ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 60172 ┆ 60172.0    ┆ 60172.0    ┆ … ┆ 60172     ┆ 60172.0   ┆ 60172.0   ┆ 60172.0   │
│ null_count ┆ 0     ┆ 0.0        ┆ 0.0        ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null  ┆ 7.0408e7   ┆ 7.0409e7   ┆ … ┆ null      ┆ 4.230139  ┆ 10.698591 ┆ 8.600536  │
│ std        ┆ null  ┆ 5.6415e7   ┆ 5.6415e7   ┆ … ┆ null      ┆ 2.532428  ┆ 13.304905 ┆ 13.085722 │
│ min        ┆ chr1  ┆ 5754.0     ┆ 5907.0     ┆ … ┆ 0         ┆ 1.43047   ┆ 2.86671   ┆ 1.00556   │
│ 25%        ┆ null  ┆ 2.7444601e ┆ 2.7445766e ┆ … ┆ null      ┆ 2.80789   ┆ 3.69146   ┆ 1.75001   │
│            ┆       ┆ 7          ┆ 7          ┆   ┆           ┆           ┆           ┆           │
│ 50%        ┆ null  ┆ 5.556897e7 ┆ 5.5570601e ┆ … ┆ null      ┆ 3.14846   ┆ 4.61719   ┆ 2.61341   │
│            ┆       ┆            ┆ 7          ┆   ┆           ┆           ┆           ┆           │
│ 75%        ┆ null  ┆ 1.04619548 ┆ 1.0462001e ┆ … ┆ null      ┆ 4.43114   ┆ 10.0849   ┆ 7.90958   │
│            ┆       ┆ e8         ┆ 8          ┆   ┆           ┆           ┆           ┆           │
│ max        ┆ chrY  ┆ 2.49239973 ┆ 2.49240439 ┆ … ┆ 0,999     ┆ 28.2161   ┆ 124.281   ┆ 120.635   │
│            ┆       ┆ e8         ┆ e8         ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Open the HepG2 peak dataset

In [10]:
H3K9ac_df = read_histone(os.path.join(DATASET_PATH, f"HepG2_Male.histone.{current_histone}.peak.bed"))

In [11]:
H3K9ac_df

shape: (76_681, 4)
┌───────┬────────────┬──────────┬──────────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         │
│ ---   ┆ ---        ┆ ---      ┆ ---          │
│ str   ┆ i64        ┆ i64      ┆ str          │
╞═══════╪════════════╪══════════╪══════════════╡
│ chr10 ┆ 119956     ┆ 120102   ┆ chr10_174    │
│ chr10 ┆ 122100     ┆ 122246   ┆ chr10_185    │
│ chr10 ┆ 122308     ┆ 122454   ┆ chr10_186    │
│ chr10 ┆ 180538     ┆ 180684   ┆ chr10_490    │
│ chr10 ┆ 181013     ┆ 181159   ┆ chr10_491    │
│ …     ┆ …          ┆ …        ┆ …            │
│ chr22 ┆ 51195358   ┆ 51195504 ┆ chr22_175255 │
│ chr22 ┆ 51195470   ┆ 51195616 ┆ chr22_175256 │
│ chr22 ┆ 51221538   ┆ 51221684 ┆ chr22_175355 │
│ chr22 ┆ 51222486   ┆ 51222632 ┆ chr22_175357 │
│ chr22 ┆ 51223073   ┆ 51223219 ┆ chr22_175358 │
└───────┴────────────┴──────────┴──────────────┘

In [12]:
H3K9ac_df.describe()

shape: (9, 5)
┌────────────┬───────┬──────────────┬──────────────┬──────────────┐
│ statistic  ┆ chrom ┆ chromStart   ┆ chromEnd     ┆ name         │
│ ---        ┆ ---   ┆ ---          ┆ ---          ┆ ---          │
│ str        ┆ str   ┆ f64          ┆ f64          ┆ str          │
╞════════════╪═══════╪══════════════╪══════════════╪══════════════╡
│ count      ┆ 76681 ┆ 76681.0      ┆ 76681.0      ┆ 76681        │
│ null_count ┆ 0     ┆ 0.0          ┆ 0.0          ┆ 0            │
│ mean       ┆ null  ┆ 7.4143e7     ┆ 7.4143e7     ┆ null         │
│ std        ┆ null  ┆ 5.5659e7     ┆ 5.5659e7     ┆ null         │
│ min        ┆ chr1  ┆ 20048.0      ┆ 20194.0      ┆ chr10_100386 │
│ 25%        ┆ null  ┆ 3.1703403e7  ┆ 3.1703549e7  ┆ null         │
│ 50%        ┆ null  ┆ 6.012111e7   ┆ 6.0121256e7  ┆ null         │
│ 75%        ┆ null  ┆ 1.09627803e8 ┆ 1.09627949e8 ┆ null         │
│ max        ┆ chrY  ┆ 2.49201218e8 ┆ 2.49201364e8 ┆ chrY_9665    │
└────────────┴───────┴──────────────┴──────────────┴──────────────┘

In [13]:
# Make an overlap join
H3K9ac_gp_simple_df = H3K9ac_gp_df.select(["chrom", "chromStart", "chromEnd", "signalValue", "pValue", "qValue"])
H3K9ac_simple_df = H3K9ac_df.select(["chrom", "chromStart", "chromEnd", "name"])

In [14]:
H3K9ac_gp_simple_df

shape: (60_172, 6)
┌───────┬────────────┬──────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---      ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64      ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪══════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 10096      ┆ 10603    ┆ 4.09313     ┆ 6.03177 ┆ 3.96029 │
│ chr1  ┆ 20034      ┆ 20201    ┆ 5.68434     ┆ 9.82363 ┆ 7.62363 │
│ chr1  ┆ 569825     ┆ 570030   ┆ 2.61768     ┆ 4.51941 ┆ 2.52068 │
│ chr1  ┆ 661812     ┆ 662015   ┆ 7.11663     ┆ 14.0947 ┆ 11.8198 │
│ chr1  ┆ 662503     ┆ 662756   ┆ 9.41397     ┆ 21.5198 ┆ 19.1332 │
│ …     ┆ …          ┆ …        ┆ …           ┆ …       ┆ …       │
│ chrY  ┆ 58827236   ┆ 58827468 ┆ 7.31989     ┆ 29.9    ┆ 27.3921 │
│ chrY  ┆ 58848053   ┆ 58848252 ┆ 7.8313      ┆ 16.2446 ┆ 13.9307 │
│ chrY  ┆ 58855971   ┆ 58856188 ┆ 3.55726     ┆ 12.3265 ┆ 10.0759 │
│ chrY  ┆ 58862614   ┆ 58863092 ┆ 5.76828     ┆ 15.6004 ┆ 13.3656 │
│ chrY  ┆ 58979340   ┆ 58979535 ┆ 1.96439     ┆ 4.32165 ┆ 2.33589 │
└───────┴────────────┴──────────┴─────────────┴─────────┴─────────┘

In [15]:
H3K9ac_simple_df

shape: (76_681, 4)
┌───────┬────────────┬──────────┬──────────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         │
│ ---   ┆ ---        ┆ ---      ┆ ---          │
│ str   ┆ i64        ┆ i64      ┆ str          │
╞═══════╪════════════╪══════════╪══════════════╡
│ chr10 ┆ 119956     ┆ 120102   ┆ chr10_174    │
│ chr10 ┆ 122100     ┆ 122246   ┆ chr10_185    │
│ chr10 ┆ 122308     ┆ 122454   ┆ chr10_186    │
│ chr10 ┆ 180538     ┆ 180684   ┆ chr10_490    │
│ chr10 ┆ 181013     ┆ 181159   ┆ chr10_491    │
│ …     ┆ …          ┆ …        ┆ …            │
│ chr22 ┆ 51195358   ┆ 51195504 ┆ chr22_175255 │
│ chr22 ┆ 51195470   ┆ 51195616 ┆ chr22_175256 │
│ chr22 ┆ 51221538   ┆ 51221684 ┆ chr22_175355 │
│ chr22 ┆ 51222486   ┆ 51222632 ┆ chr22_175357 │
│ chr22 ┆ 51223073   ┆ 51223219 ┆ chr22_175358 │
└───────┴────────────┴──────────┴──────────────┘

In [ ]:
# Left join on chromosome
overlap_df = (
    H3K9ac_simple_df.join(
        H3K9ac_gp_simple_df,
        on="chrom",
        how="left",
        suffix="_gapped"
    )
    .filter(
        (pl.col("chromStart") < pl.col("chromEnd_gapped")) &
        (pl.col("chromEnd") > pl.col("chromStart_gapped"))
    )
    .select([
        "chrom",
        "chromStart",
        "chromEnd",
        "name",        # original histone peak name
        "signalValue",
        "pValue",
        "qValue"
    ])
)

In [ ]:
overlap_df