In [3]:
import pandas as pd
import numpy as np
import os
from tqdm.auto import tqdm

In [4]:
# Create a schema
column_names = ['chromosome_name',
                'start',
                'end',
                'gene_id',
                'E066',
                'strand',
                'label',
                'external_gene_name',
                'start_position',
                'end_position',
                'tss' 
                ]

In [5]:
DATASET_PATH = '../dataset/E066/'

In [6]:
E066_df = pd.read_csv(os.path.join(DATASET_PATH, "E066.bed"), sep="\t", names = column_names)

In [7]:
E066_df.head()

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,tss
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,99894988
1,chrX,99834799,99844799,ENSG00000000005,0.191,1,-1,TNMD,99839799,99854882,99839799
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,49575092
3,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,169863408
4,chr1,169626245,169636245,ENSG00000000460,0.942,1,-1,C1orf112,169631245,169823221,169631245

# Reformating the histone

In [8]:
histone_list = ['H3K4me1', 'H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K36me3']

In [9]:
intersect_cols = [  'chromosome_name',
                    'start',
                    'end',
                    'gene_id',
                    'E066',
                    'strand',
                    'label',
                    'external_gene_name',
                    'start_position',
                    'end_position',
                    'tss',
                    'chrom',
                    'chromStart',
                    'chromEnd',
                    'name',
                    'score',
                    'strand_peak',
                    'signalValue',
                    'pValue',
                    'qValue',
                    'peak'
                ]

In [10]:
for name in histone_list:
    print(f"Processing: {name}")
    histone_df = pd.read_csv(os.path.join(DATASET_PATH, "intersect", f"E066_{name}.bed"), sep='\t', names=intersect_cols)
    histone_df.loc[:, 'startBucket'] = (histone_df['chromStart'] - histone_df['start'])/100
    histone_df.loc[:, 'endBucket'] = (histone_df['chromEnd'] - histone_df['start'])/100
    histone_df.to_csv(os.path.join(DATASET_PATH, f"E066_{name}_df.csv"), header=True, index=False)
    print(f"CSV saved!")

Processing: H3K4me1
CSV saved!
Processing: H3K4me3
CSV saved!
Processing: H3K9me3
CSV saved!
Processing: H3K27me3
CSV saved!
Processing: H3K36me3
CSV saved!

# Reading Histone File

In [11]:
H3K4me1_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K4me1_df.csv"))
H3K4me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K4me3_df.csv"))
H3K9me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K9me3_df.csv"))
H3K27me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K27me3_df.csv"))
H3K36me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K36me3_df.csv"))

In [12]:
print(H3K4me1_df.shape)
print(H3K4me3_df.shape)
print(H3K9me3_df.shape)
print(H3K27me3_df.shape)
print(H3K36me3_df.shape)

(62141, 23)
(34303, 23)
(9301, 23)
(15620, 23)
(25044, 23)

In [13]:
H3K4me1_df.head(10)

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,...,chromEnd,name,score,strand_peak,signalValue,pValue,qValue,peak,startBucket,endBucket
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,...,99891002,Rank_68310,106,.,5.92171,10.69175,8.59968,462,2.58,10.14
1,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49577113,Rank_14,734,.,20.49891,73.43851,67.02312,620,55.72,70.21
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49574573,Rank_188,564,.,18.24062,56.41204,51.06926,350,28.60,44.81
3,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49572915,Rank_71909,102,.,5.67759,10.27033,8.20970,169,19.06,28.23
4,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49577379,Rank_159548,51,.,3.58302,5.16452,3.52579,35,70.94,72.87
5,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49571632,Rank_161879,51,.,3.68107,5.10401,3.47041,307,11.52,15.40
6,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49577806,Rank_163065,50,.,3.52959,5.07326,3.44426,40,75.37,77.14
7,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,...,169862186,Rank_14817,234,.,8.21260,23.41891,20.39701,907,11.85,37.78
8,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,...,169859534,Rank_87234,87,.,4.21981,8.76005,6.81517,143,6.90,11.26
9,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,...,169864002,Rank_204875,37,.,2.44085,3.78662,2.27872,149,53.64,55.94

In [14]:
H3K36me3_df.head(10)

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,...,chromEnd,name,score,strand_peak,signalValue,pValue,qValue,peak,startBucket,endBucket
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,...,99890007,Rank_229966,42,.,3.39243,4.23623,2.67813,98,-1.31,0.19
1,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49571815,Rank_5900,240,.,10.55422,24.06517,20.55629,1352,-9.81,17.23
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49579183,Rank_79179,86,.,4.93847,8.62900,6.60337,226,84.85,90.91
3,chr6,143827827,143837827,ENSG00000001036,43.631,-1,1,FUCA2,143815948,143832827,...,143828346,Rank_27634,146,.,6.50787,14.60517,12.00608,233,0.08,5.19
4,chr6,143827827,143837827,ENSG00000001036,43.631,-1,1,FUCA2,143815948,143832827,...,143828941,Rank_91821,80,.,4.96144,8.02898,6.07414,172,8.56,11.14
5,chr6,143827827,143837827,ENSG00000001036,43.631,-1,1,FUCA2,143815948,143832827,...,143829758,Rank_287174,29,.,2.67470,2.97220,1.57166,149,17.51,19.31
6,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,...,41036466,Rank_88206,83,.,4.78412,8.35443,6.37927,777,-5.86,7.82
7,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,...,41037066,Rank_167637,54,.,3.51186,5.49032,3.79690,77,12.31,13.82
8,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,...,41036869,Rank_200860,48,.,3.26101,4.81198,3.19722,211,8.72,11.85
9,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,...,41037444,Rank_206214,47,.,3.01085,4.72265,3.12517,82,15.47,17.60

# Function to encode the gene and histone

In [ ]:
# Load the gene expression data

gene_exp_arr = E066_df.to_numpy()
display(gene_exp_arr)

In [ ]:
gene_exp_arr.shape[0]

In [ ]:
def encode_histone_exp(gene_id, start, end, histone):
    arr = []
    count = 1
    for i in range(start, end, 100):
        histone_df = histone[
                    # The same gene ID
                    (histone['gene_id'] == gene_id) &
                    (
                        # The window is inside the histone
                        ((histone['chromStart'] <= i) & (histone['chromEnd'] >= i + 100)) |
                        # The start of histone is inside the window
                        ((histone['chromStart'] >= i) & (histone['chromStart'] <= i + 100) & (histone['chromEnd'] >= i + 100)) |
                        # The end of histone is inside the window
                        ((histone['chromStart'] <= i) & (histone['chromEnd'] >= i) & (histone['chromEnd'] <= i + 100))
                    )
                    ]
        size = histone_df.shape[0]
        if (size > 0):
            avg = histone_df['signalValue'].mean()
        else:
            avg = 0.0
        
        # print(f"Bin {count}: {i} to {i + 100}: {histone_df.shape[0]}, average: {avg}")
        arr.append(avg)
        count += 1
    return arr

In [16]:
# Use this function for apply()
def encode_histone_exp(row, histone):
    arr = []
    start = row['start']
    end = row['end']
    gene_id = row['gene_id']
    count = 1

    for i in range(start, end, 100):
        histone_df = histone[
                    # The same gene ID
                    (histone['gene_id'] == gene_id) &
                    (
                        # The window is inside the histone
                        ((histone['chromStart'] <= i) & (histone['chromEnd'] >= i + 100)) |
                        # The start of histone is inside the window
                        ((histone['chromStart'] >= i) & (histone['chromStart'] <= i + 100) & (histone['chromEnd'] >= i + 100)) |
                        # The end of histone is inside the window
                        ((histone['chromStart'] <= i) & (histone['chromEnd'] >= i) & (histone['chromEnd'] <= i + 100))
                    )
                    ]
        size = histone_df.shape[0]
        if (size > 0):
            avg = histone_df['signalValue'].mean()
        else:
            avg = 0.0
        
        # print(f"Bin {count}: {i} to {i + 100}: {histone_df.shape[0]}, average: {avg}")
        arr.append(avg)
        count += 1
    return arr

In [ ]:
H3K4me1_stack = np.empty((0, 100))

In [ ]:
samples = gene_exp_arr[0:10, :]

In [ ]:
samples

In [ ]:
count = 1
for row in tqdm(samples, "Processing"):
    gene_id = row[3]
    tss_start = row[1]
    tss_end = row[2]

    print(f"{count} -  {gene_id}")
    arr = encode_histone_exp(gene_id, tss_start, tss_end, E066_H3K4me1_df)
    H3K4me1_stack = np.vstack((H3K4me1_stack, arr))
    count += 1

In [13]:
E066_10_df = E066_df.head(10)
E066_10_df

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,tss
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,99894988
1,chrX,99834799,99844799,ENSG00000000005,0.191,1,-1,TNMD,99839799,99854882,99839799
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,49575092
3,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,169863408
4,chr1,169626245,169636245,ENSG00000000460,0.942,1,-1,C1orf112,169631245,169823221,169631245
5,chr1,27956788,27966788,ENSG00000000938,4.572,-1,1,FGR,27938575,27961788,27961788
6,chr1,196616008,196626008,ENSG00000000971,566.609,1,1,CFH,196621008,196716634,196621008
7,chr6,143827827,143837827,ENSG00000001036,43.631,-1,1,FUCA2,143815948,143832827,143832827
8,chr6,53476768,53486768,ENSG00000001084,25.767,-1,1,GCLC,53362139,53481768,53481768
9,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,41040684

In [19]:
tqdm.pandas()

In [22]:
E066_10_df.loc[:, 'H3K4me1'] = E066_10_df.apply(lambda row: encode_histone_exp(row, H3K4me1_df), axis = 1)

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,tss,H3K4me1
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,99894988,"[0.0, 0.0, 5.92171, 5.92171, 5.92171, 5.92171,..."
1,chrX,99834799,99844799,ENSG00000000005,0.191,1,-1,TNMD,99839799,99854882,99839799,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,49575092,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,169863408,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.21981, 4.2198..."
4,chr1,169626245,169636245,ENSG00000000460,0.942,1,-1,C1orf112,169631245,169823221,169631245,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,chr1,27956788,27966788,ENSG00000000938,4.572,-1,1,FGR,27938575,27961788,27961788,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,chr1,196616008,196626008,ENSG00000000971,566.609,1,1,CFH,196621008,196716634,196621008,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,chr6,143827827,143837827,ENSG00000001036,43.631,-1,1,FUCA2,143815948,143832827,143832827,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,chr6,53476768,53486768,ENSG00000001084,25.767,-1,1,GCLC,53362139,53481768,53481768,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,chr6,41035684,41045684,ENSG00000001167,6.255,1,1,NFYA,41040684,41067715,41040684,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [24]:
E066_10_df.to_parquet(os.path.join(DATASET_PATH, "test.parquet"))

In [25]:
test_df = pd.read_parquet(os.path.join(DATASET_PATH, "test.parquet"))