In [12]:
import pandas as pd
import os
import numpy as np

In [4]:
DATASET_PATH = '../dataset/E066/'

In [5]:
E066_df = pd.read_parquet(os.path.join(DATASET_PATH, "E066_with_histone.parquet"))

In [6]:
E066_df.head()

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,tss,H3K4me1,H3K4me3,H3K9me3,H3K27me3,H3K36me3
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,99894988,"[0.0, 0.0, 5.92171, 5.92171, 5.92171, 5.92171,...","[0.0, 4.19024, 4.19024, 4.19024, 4.19024, 4.19...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.39243, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0..."
1,chrX,99834799,99844799,ENSG00000000005,0.191,1,-1,TNMD,99839799,99854882,99839799,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.337...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,49575092,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10.55422, 10.55422, 10.55422, 10.55422, 10.55..."
3,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,169863408,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.21981, 4.2198...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,chr1,169626245,169636245,ENSG00000000460,0.942,1,-1,C1orf112,169631245,169823221,169631245,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0104, 3.0104, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [10]:
histone_df = E066_df[['H3K4me1', 'H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K36me3']]
label = E066_df[['label']]

In [9]:
histone_df

,H3K4me1,H3K4me3,H3K9me3,H3K27me3,H3K36me3
0,"[0.0, 0.0, 5.92171, 5.92171, 5.92171, 5.92171,...","[0.0, 4.19024, 4.19024, 4.19024, 4.19024, 4.19...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.39243, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0..."
1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.337...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10.55422, 10.55422, 10.55422, 10.55422, 10.55..."
3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.21981, 4.2198...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0104, 3.0104, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...
19640,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
19641,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
19642,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
19643,"[0.0, 3.18223, 3.18223, 3.18223, 3.18223, 3.18...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
19644,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[4.01232, 4.01232, 4.01232, 3.03089, 3.03089, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 2.50847, 2.50847, 2...."

In [11]:
label

       label
0          1
1         -1
2          1
3          1
4         -1
...      ...
19640     -1
19641     -1
19642     -1
19643     -1
19644     -1

[19645 rows x 1 columns]

In [27]:
histone_np = histone_df.head(1).values

In [28]:
histone_np

array([[array([0.     , 0.     , 5.92171, 5.92171, 5.92171, 5.92171, 5.92171,
               5.92171, 5.92171, 5.92171, 5.92171, 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     ])                                            ,
        array([ 0.     ,  4.19024,  4.19024,  4.19024,  4.19024,  4.19024,
               11.91877, 11.91877, 11.91877, 11.91877, 11.91877, 11.91877,
               11.91877, 11.91877, 11.91877, 11.91877, 11.91877, 11.91877,
               11.91877, 11.91877,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
                0.     ,  0.     ,  0.     ,  0.     ])                   ,
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        array([3.39243, 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
               0.     , 0.     ])                                            ]],
      dtype=object)

In [32]:
histone_df['H3K4me1'].head(1).values

array([array([0.     , 0.     , 5.92171, 5.92171, 5.92171, 5.92171, 5.92171,
              5.92171, 5.92171, 5.92171, 5.92171, 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
              0.     , 0.     ])                                            ],
      dtype=object)