In [5]:
import os
import polars as pl

In [6]:
DATASET_PATH = '/mmfs1/data/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [7]:
DATASET_PATH

'/mmfs1/data/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [8]:
def read_gappedPeak(filename):
    # Define the columns
    cols = [
        "chrom", "chromStart", "chromEnd", "name", "score", "strand",
        "thickStart", "thickEnd", "itemRgb", "blockCount", "blockSizes",
        "blockStarts", "signalValue", "pValue", "qValue"
    ]
    
    # Read the file
    gappedpeak_df = pl.read_csv(
        filename,
        separator="\t",
        has_header=False,
        new_columns=cols
    )
    
    # Return the dataframe
    return gappedpeak_df

In [9]:
def read_histone(filename):
    # Define the columns
    cols = ["chrom", "chromStart", "chromEnd", "name"]
    
    # Read the histone file
    histone_df = pl.read_csv(
        filename,
        separator="\t",
        has_header=False,
        new_columns=cols
    )

    # Return the dataframe
    return histone_df

# Open the original histone peak dataset

In [10]:
current_histone = "H3K9me3"

In [11]:
gapped_df = read_gappedPeak(os.path.join(DATASET_PATH, f'{current_histone}_peaks.gappedPeak'))

In [12]:
gapped_df

shape: (50_508, 15)
┌───────┬────────────┬──────────┬──────────────┬───┬─────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         ┆ … ┆ blockStarts ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---      ┆ ---          ┆   ┆ ---         ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64      ┆ str          ┆   ┆ str         ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪══════════╪══════════════╪═══╪═════════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 10025      ┆ 10632    ┆ H3K9me3_peak ┆ … ┆ 0,4,606     ┆ 9.36668     ┆ 21.5877 ┆ 17.2487 │
│       ┆            ┆          ┆ _1           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 569807     ┆ 570045   ┆ H3K9me3_peak ┆ … ┆ 0,4,237     ┆ 4.26881     ┆ 10.5216 ┆ 6.88988 │
│       ┆            ┆          ┆ _2           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 714508     ┆ 714658   ┆ H3K9me3_peak ┆ … ┆ 0,149       ┆ 3.03968     ┆ 3.63911 ┆ 1.14235 │
│       ┆            ┆          ┆ _3           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 724858     ┆ 725591   ┆ H3K9me3_peak ┆ … ┆ 0,18,732    ┆ 4.14188     ┆ 6.51894 ┆ 3.42624 │
│       ┆            ┆          ┆ _4           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 725799     ┆ 726036   ┆ H3K9me3_peak ┆ … ┆ 0,34,236    ┆ 3.61309     ┆ 6.18754 ┆ 3.0949  │
│       ┆            ┆          ┆ _5           ┆   ┆             ┆             ┆         ┆         │
│ …     ┆ …          ┆ …        ┆ …            ┆ … ┆ …           ┆ …           ┆ …       ┆ …       │
│ chrY  ┆ 59027682   ┆ 59027844 ┆ H3K9me3_peak ┆ … ┆ 0,161       ┆ 3.46043     ┆ 5.76123 ┆ 2.73445 │
│       ┆            ┆          ┆ _50504       ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 59028959   ┆ 59029469 ┆ H3K9me3_peak ┆ … ┆ 0,509       ┆ 3.06718     ┆ 4.6891  ┆ 1.91159 │
│       ┆            ┆          ┆ _50505       ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 59029932   ┆ 59030272 ┆ H3K9me3_peak ┆ … ┆ 0,339       ┆ 3.32346     ┆ 4.67402 ┆ 1.90819 │
│       ┆            ┆          ┆ _50506       ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 59031821   ┆ 59032260 ┆ H3K9me3_peak ┆ … ┆ 0,438       ┆ 3.12998     ┆ 4.31614 ┆ 1.64974 │
│       ┆            ┆          ┆ _50507       ┆   ┆             ┆             ┆         ┆         │
│ chrY  ┆ 59032695   ┆ 59033314 ┆ H3K9me3_peak ┆ … ┆ 0,618       ┆ 3.61045     ┆ 5.47167 ┆ 2.5449  │
│       ┆            ┆          ┆ _50508       ┆   ┆             ┆             ┆         ┆         │
└───────┴────────────┴──────────┴──────────────┴───┴─────────────┴─────────────┴─────────┴─────────┘

In [13]:
gapped_df.describe()

shape: (9, 16)
┌────────────┬───────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬──────────┐
│ statistic  ┆ chrom ┆ chromStart ┆ chromEnd   ┆ … ┆ blockStart ┆ signalValu ┆ pValue   ┆ qValue   │
│ ---        ┆ ---   ┆ ---        ┆ ---        ┆   ┆ s          ┆ e          ┆ ---      ┆ ---      │
│ str        ┆ str   ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ f64      ┆ f64      │
│            ┆       ┆            ┆            ┆   ┆ str        ┆ f64        ┆          ┆          │
╞════════════╪═══════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪══════════╡
│ count      ┆ 50508 ┆ 50508.0    ┆ 50508.0    ┆ … ┆ 50508      ┆ 50508.0    ┆ 50508.0  ┆ 50508.0  │
│ null_count ┆ 0     ┆ 0.0        ┆ 0.0        ┆ … ┆ 0          ┆ 0.0        ┆ 0.0      ┆ 0.0      │
│ mean       ┆ null  ┆ 7.1330e7   ┆ 7.1331e7   ┆ … ┆ null       ┆ 3.251204   ┆ 4.509488 ┆ 1.817132 │
│ std        ┆ null  ┆ 5.7609e7   ┆ 5.7609e7   ┆ … ┆ null       ┆ 0.525955   ┆ 1.572998 ┆ 1.35287  │
│ min        ┆ chr1  ┆ 9948.0     ┆ 10198.0    ┆ … ┆ 0,1,182    ┆ 1.34332    ┆ 3.30975  ┆ 1.00086  │
│ 25%        ┆ null  ┆ 2.6104867e ┆ 2.6105017e ┆ … ┆ null       ┆ 2.99995    ┆ 3.75223  ┆ 1.22564  │
│            ┆       ┆ 7          ┆ 7          ┆   ┆            ┆            ┆          ┆          │
│ 50%        ┆ null  ┆ 5.6842542e ┆ 5.6842838e ┆ … ┆ null       ┆ 3.15527    ┆ 4.10345  ┆ 1.47835  │
│            ┆       ┆ 7          ┆ 7          ┆   ┆            ┆            ┆          ┆          │
│ 75%        ┆ null  ┆ 1.09566618 ┆ 1.0956731e ┆ … ┆ null       ┆ 3.38958    ┆ 4.71845  ┆ 1.93474  │
│            ┆       ┆ e8         ┆ 8          ┆   ┆            ┆            ┆          ┆          │
│ max        ┆ chrY  ┆ 2.49239682 ┆ 2.49240474 ┆ … ┆ 0,999      ┆ 15.711     ┆ 55.2935  ┆ 49.7108  │
│            ┆       ┆ e8         ┆ e8         ┆   ┆            ┆            ┆          ┆          │
└────────────┴───────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴──────────┘

# Open the HepG2 peak dataset

In [14]:
histone_df = read_histone(os.path.join(DATASET_PATH, f"HepG2_Male.histone.{current_histone}.peak.bed"))

In [15]:
histone_df

shape: (34_534, 4)
┌───────┬────────────┬──────────┬──────────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         │
│ ---   ┆ ---        ┆ ---      ┆ ---          │
│ str   ┆ i64        ┆ i64      ┆ str          │
╞═══════╪════════════╪══════════╪══════════════╡
│ chr10 ┆ 104133     ┆ 104279   ┆ chr10_97     │
│ chr10 ┆ 149783     ┆ 149929   ┆ chr10_336    │
│ chr10 ┆ 229638     ┆ 229784   ┆ chr10_735    │
│ chr10 ┆ 232118     ┆ 232264   ┆ chr10_748    │
│ chr10 ┆ 234923     ┆ 235069   ┆ chr10_765    │
│ …     ┆ …          ┆ …        ┆ …            │
│ chr22 ┆ 49795316   ┆ 49795462 ┆ chr22_168447 │
│ chr22 ┆ 49905083   ┆ 49905229 ┆ chr22_169016 │
│ chr22 ┆ 50080443   ┆ 50080589 ┆ chr22_169918 │
│ chr22 ┆ 51110578   ┆ 51110724 ┆ chr22_174868 │
│ chr22 ┆ 51180963   ┆ 51181109 ┆ chr22_175199 │
└───────┴────────────┴──────────┴──────────────┘

In [16]:
histone_df.describe()

shape: (9, 5)
┌────────────┬───────┬──────────────┬──────────────┬──────────────┐
│ statistic  ┆ chrom ┆ chromStart   ┆ chromEnd     ┆ name         │
│ ---        ┆ ---   ┆ ---          ┆ ---          ┆ ---          │
│ str        ┆ str   ┆ f64          ┆ f64          ┆ str          │
╞════════════╪═══════╪══════════════╪══════════════╪══════════════╡
│ count      ┆ 34534 ┆ 34534.0      ┆ 34534.0      ┆ 34534        │
│ null_count ┆ 0     ┆ 0.0          ┆ 0.0          ┆ 0            │
│ mean       ┆ null  ┆ 7.9680e7     ┆ 7.9680e7     ┆ null         │
│ std        ┆ null  ┆ 5.5049e7     ┆ 5.5049e7     ┆ null         │
│ min        ┆ chr1  ┆ 10178.0      ┆ 10324.0      ┆ chr10_100473 │
│ 25%        ┆ null  ┆ 3.3335983e7  ┆ 3.3336129e7  ┆ null         │
│ 50%        ┆ null  ┆ 7.107507e7   ┆ 7.1075216e7  ┆ null         │
│ 75%        ┆ null  ┆ 1.14785088e8 ┆ 1.14785234e8 ┆ null         │
│ max        ┆ chrY  ┆ 2.49239033e8 ┆ 2.49239179e8 ┆ chrY_8755    │
└────────────┴───────┴──────────────┴──────────────┴──────────────┘

In [17]:
# Make an overlap join
gapped_simple_df = gapped_df.select(["chrom", "chromStart", "chromEnd", "signalValue", "pValue", "qValue"])
histone_simple_df = histone_df.select(["chrom", "chromStart", "chromEnd", "name"])

In [18]:
gapped_simple_df

shape: (50_508, 6)
┌───────┬────────────┬──────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---      ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64      ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪══════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 10025      ┆ 10632    ┆ 9.36668     ┆ 21.5877 ┆ 17.2487 │
│ chr1  ┆ 569807     ┆ 570045   ┆ 4.26881     ┆ 10.5216 ┆ 6.88988 │
│ chr1  ┆ 714508     ┆ 714658   ┆ 3.03968     ┆ 3.63911 ┆ 1.14235 │
│ chr1  ┆ 724858     ┆ 725591   ┆ 4.14188     ┆ 6.51894 ┆ 3.42624 │
│ chr1  ┆ 725799     ┆ 726036   ┆ 3.61309     ┆ 6.18754 ┆ 3.0949  │
│ …     ┆ …          ┆ …        ┆ …           ┆ …       ┆ …       │
│ chrY  ┆ 59027682   ┆ 59027844 ┆ 3.46043     ┆ 5.76123 ┆ 2.73445 │
│ chrY  ┆ 59028959   ┆ 59029469 ┆ 3.06718     ┆ 4.6891  ┆ 1.91159 │
│ chrY  ┆ 59029932   ┆ 59030272 ┆ 3.32346     ┆ 4.67402 ┆ 1.90819 │
│ chrY  ┆ 59031821   ┆ 59032260 ┆ 3.12998     ┆ 4.31614 ┆ 1.64974 │
│ chrY  ┆ 59032695   ┆ 59033314 ┆ 3.61045     ┆ 5.47167 ┆ 2.5449  │
└───────┴────────────┴──────────┴─────────────┴─────────┴─────────┘

In [19]:
histone_simple_df

shape: (34_534, 4)
┌───────┬────────────┬──────────┬──────────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         │
│ ---   ┆ ---        ┆ ---      ┆ ---          │
│ str   ┆ i64        ┆ i64      ┆ str          │
╞═══════╪════════════╪══════════╪══════════════╡
│ chr10 ┆ 104133     ┆ 104279   ┆ chr10_97     │
│ chr10 ┆ 149783     ┆ 149929   ┆ chr10_336    │
│ chr10 ┆ 229638     ┆ 229784   ┆ chr10_735    │
│ chr10 ┆ 232118     ┆ 232264   ┆ chr10_748    │
│ chr10 ┆ 234923     ┆ 235069   ┆ chr10_765    │
│ …     ┆ …          ┆ …        ┆ …            │
│ chr22 ┆ 49795316   ┆ 49795462 ┆ chr22_168447 │
│ chr22 ┆ 49905083   ┆ 49905229 ┆ chr22_169016 │
│ chr22 ┆ 50080443   ┆ 50080589 ┆ chr22_169918 │
│ chr22 ┆ 51110578   ┆ 51110724 ┆ chr22_174868 │
│ chr22 ┆ 51180963   ┆ 51181109 ┆ chr22_175199 │
└───────┴────────────┴──────────┴──────────────┘

In [20]:
# Find unique chromosome
chroms = histone_simple_df["chrom"].unique().to_list()
print(len(chroms))

24

In [21]:
chrom = 'chr1'

In [22]:
# Subset by chromosome
gapped_chr = gapped_simple_df.filter(pl.col("chrom") == chrom)
histone_chr = histone_simple_df.filter(pl.col("chrom") == chrom)

In [23]:
gapped_chr

shape: (4_071, 6)
┌───────┬────────────┬───────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd  ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---       ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64       ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪═══════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 10025      ┆ 10632     ┆ 9.36668     ┆ 21.5877 ┆ 17.2487 │
│ chr1  ┆ 569807     ┆ 570045    ┆ 4.26881     ┆ 10.5216 ┆ 6.88988 │
│ chr1  ┆ 714508     ┆ 714658    ┆ 3.03968     ┆ 3.63911 ┆ 1.14235 │
│ chr1  ┆ 724858     ┆ 725591    ┆ 4.14188     ┆ 6.51894 ┆ 3.42624 │
│ chr1  ┆ 725799     ┆ 726036    ┆ 3.61309     ┆ 6.18754 ┆ 3.0949  │
│ …     ┆ …          ┆ …         ┆ …           ┆ …       ┆ …       │
│ chr1  ┆ 248855238  ┆ 248855388 ┆ 2.99995     ┆ 3.46759 ┆ 1.0087  │
│ chr1  ┆ 249097456  ┆ 249097802 ┆ 3.13583     ┆ 3.77013 ┆ 1.27189 │
│ chr1  ┆ 249132449  ┆ 249132832 ┆ 2.5572      ┆ 4.09911 ┆ 1.4915  │
│ chr1  ┆ 249152117  ┆ 249152432 ┆ 2.52985     ┆ 3.69044 ┆ 1.20015 │
│ chr1  ┆ 249239682  ┆ 249240474 ┆ 6.40786     ┆ 12.0728 ┆ 8.29898 │
└───────┴────────────┴───────────┴─────────────┴─────────┴─────────┘

In [24]:
histone_chr

shape: (2_691, 4)
┌───────┬────────────┬───────────┬──────────────┐
│ chrom ┆ chromStart ┆ chromEnd  ┆ name         │
│ ---   ┆ ---        ┆ ---       ┆ ---          │
│ str   ┆ i64        ┆ i64       ┆ str          │
╞═══════╪════════════╪═══════════╪══════════════╡
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425     │
│ chr1  ┆ 726918     ┆ 727064    ┆ chr1_426     │
│ chr1  ┆ 773863     ┆ 774009    ┆ chr1_596     │
│ chr1  ┆ 1778078    ┆ 1778224   ┆ chr1_5299    │
│ chr1  ┆ 2009508    ┆ 2009654   ┆ chr1_6455    │
│ …     ┆ …          ┆ …         ┆ …            │
│ chr1  ┆ 248834918  ┆ 248835064 ┆ chr1_1128451 │
│ chr1  ┆ 248875103  ┆ 248875249 ┆ chr1_1128652 │
│ chr1  ┆ 248890138  ┆ 248890284 ┆ chr1_1128720 │
│ chr1  ┆ 249072368  ┆ 249072514 ┆ chr1_1128874 │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_1129668 │
└───────┴────────────┴───────────┴──────────────┘

In [25]:
# Cross join per chromosome
joined = histone_chr.join(gapped_chr, how="cross", suffix="_gapped")

In [26]:
joined

shape: (10_955_061, 10)
┌───────┬────────────┬───────────┬─────────────┬───┬─────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd  ┆ name        ┆ … ┆ chromEnd_ga ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---       ┆ ---         ┆   ┆ pped        ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64       ┆ str         ┆   ┆ ---         ┆ f64         ┆ f64     ┆ f64     │
│       ┆            ┆           ┆             ┆   ┆ i64         ┆             ┆         ┆         │
╞═══════╪════════════╪═══════════╪═════════════╪═══╪═════════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425    ┆ … ┆ 10632       ┆ 9.36668     ┆ 21.5877 ┆ 17.2487 │
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425    ┆ … ┆ 570045      ┆ 4.26881     ┆ 10.5216 ┆ 6.88988 │
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425    ┆ … ┆ 714658      ┆ 3.03968     ┆ 3.63911 ┆ 1.14235 │
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425    ┆ … ┆ 725591      ┆ 4.14188     ┆ 6.51894 ┆ 3.42624 │
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425    ┆ … ┆ 726036      ┆ 3.61309     ┆ 6.18754 ┆ 3.0949  │
│ …     ┆ …          ┆ …         ┆ …           ┆ … ┆ …           ┆ …           ┆ …       ┆ …       │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_112966 ┆ … ┆ 248855388   ┆ 2.99995     ┆ 3.46759 ┆ 1.0087  │
│       ┆            ┆           ┆ 8           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_112966 ┆ … ┆ 249097802   ┆ 3.13583     ┆ 3.77013 ┆ 1.27189 │
│       ┆            ┆           ┆ 8           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_112966 ┆ … ┆ 249132832   ┆ 2.5572      ┆ 4.09911 ┆ 1.4915  │
│       ┆            ┆           ┆ 8           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_112966 ┆ … ┆ 249152432   ┆ 2.52985     ┆ 3.69044 ┆ 1.20015 │
│       ┆            ┆           ┆ 8           ┆   ┆             ┆             ┆         ┆         │
│ chr1  ┆ 249239033  ┆ 249239179 ┆ chr1_112966 ┆ … ┆ 249240474   ┆ 6.40786     ┆ 12.0728 ┆ 8.29898 │
│       ┆            ┆           ┆ 8           ┆   ┆             ┆             ┆         ┆         │
└───────┴────────────┴───────────┴─────────────┴───┴─────────────┴─────────────┴─────────┴─────────┘

In [27]:
# Vectorized interval overlap
overlap = joined.filter(
    (pl.col("chromStart") < pl.col("chromEnd_gapped")) &
    (pl.col("chromEnd") > pl.col("chromStart_gapped"))
).select([
    "chrom",
    "chromStart",
    "chromEnd",
    "name",           # histone name
    "signalValue",
    "pValue",
    "qValue"
])

In [28]:
overlap

shape: (472, 7)
┌───────┬────────────┬───────────┬──────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd  ┆ name         ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---       ┆ ---          ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64       ┆ str          ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪═══════════╪══════════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 726798     ┆ 726944    ┆ chr1_425     ┆ 3.73266     ┆ 5.10695 ┆ 2.2332  │
│ chr1  ┆ 726918     ┆ 727064    ┆ chr1_426     ┆ 3.73266     ┆ 5.10695 ┆ 2.2332  │
│ chr1  ┆ 2009508    ┆ 2009654   ┆ chr1_6455    ┆ 3.60849     ┆ 5.26136 ┆ 2.34448 │
│ chr1  ┆ 2360750    ┆ 2360896   ┆ chr1_8208    ┆ 4.34891     ┆ 6.57124 ┆ 3.4466  │
│ chr1  ┆ 4318680    ┆ 4318826   ┆ chr1_17179   ┆ 3.73825     ┆ 5.44926 ┆ 2.50409 │
│ …     ┆ …          ┆ …         ┆ …            ┆ …           ┆ …       ┆ …       │
│ chr1  ┆ 248266598  ┆ 248266744 ┆ chr1_1126137 ┆ 3.58352     ┆ 5.03239 ┆ 2.19083 │
│ chr1  ┆ 248266770  ┆ 248266916 ┆ chr1_1126138 ┆ 3.58352     ┆ 5.03239 ┆ 2.19083 │
│ chr1  ┆ 248392680  ┆ 248392826 ┆ chr1_1126742 ┆ 3.2975      ┆ 4.06629 ┆ 1.42857 │
│ chr1  ┆ 248392818  ┆ 248392964 ┆ chr1_1126743 ┆ 3.2975      ┆ 4.06629 ┆ 1.42857 │
│ chr1  ┆ 248481253  ┆ 248481399 ┆ chr1_1127166 ┆ 3.13371     ┆ 3.76818 ┆ 1.21722 │
└───────┴────────────┴───────────┴──────────────┴─────────────┴─────────┴─────────┘

In [29]:
chroms = histone_df["chrom"].unique().to_list()
overlap_list = []

In [30]:
print(chroms)

['chr8', 'chr20', 'chrX', 'chrY', 'chr19', 'chr3', 'chr16', 'chr2', 'chr7', 'chr15', 'chr11', 'chr17', 'chr6', 'chr9', 'chr18', 'chr22', 'chr14', 'chr1', 'chr5', 'chr10', 'chr4', 'chr13', 'chr12', 'chr21']

In [31]:
for chrom in chroms:
    print(f"Processing {chrom}...")
    gapped_chr = gapped_df.filter(pl.col("chrom") == chrom)
    histone_chr = histone_df.filter(pl.col("chrom") == chrom)
    
    if gapped_chr.height == 0:
        # No gappedPeak for this chromosome → mark all histone peaks as null
        overlap_list.append(
            histone_chr.with_columns([
                pl.lit(None).alias("signalValue"),
                pl.lit(None).alias("pValue"),
                pl.lit(None).alias("qValue"),
                pl.lit("no_overlap").alias("status")
            ])
        )
        continue
    
    # Cross join per chromosome
    joined = histone_chr.join(gapped_chr, how="cross", suffix="_gapped")
    
    # Vectorized interval overlap
    overlap = joined.filter(
        (pl.col("chromStart") < pl.col("chromEnd_gapped")) &
        (pl.col("chromEnd") > pl.col("chromStart_gapped"))
    ).select([
        "chrom",
        "chromStart",
        "chromEnd",
        "name",           # histone name
        "signalValue",
        "pValue",
        "qValue"
    ])
    
    overlap_list.append(overlap)

# Final result
overlap_df = pl.concat(overlap_list)

Processing chr8...
Processing chr20...
Processing chrX...
Processing chrY...
Processing chr19...
Processing chr3...
Processing chr16...
Processing chr2...
Processing chr7...
Processing chr15...
Processing chr11...
Processing chr17...
Processing chr6...
Processing chr9...
Processing chr18...
Processing chr22...
Processing chr14...
Processing chr1...
Processing chr5...
Processing chr10...
Processing chr4...
Processing chr13...
Processing chr12...
Processing chr21...

In [32]:
overlap_df

shape: (6_551, 7)
┌───────┬────────────┬──────────┬──────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ name         ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---        ┆ ---      ┆ ---          ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64        ┆ i64      ┆ str          ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪════════════╪══════════╪══════════════╪═════════════╪═════════╪═════════╡
│ chr8  ┆ 710738     ┆ 710884   ┆ chr8_2820    ┆ 4.03925     ┆ 5.99958 ┆ 2.94105 │
│ chr8  ┆ 953543     ┆ 953689   ┆ chr8_4027    ┆ 3.80019     ┆ 5.20381 ┆ 2.29285 │
│ chr8  ┆ 1123960    ┆ 1124106  ┆ chr8_4829    ┆ 3.06326     ┆ 3.73756 ┆ 1.21271 │
│ chr8  ┆ 1241125    ┆ 1241271  ┆ chr8_5414    ┆ 3.2459      ┆ 4.02458 ┆ 1.41632 │
│ chr8  ┆ 1360783    ┆ 1360929  ┆ chr8_5934    ┆ 3.07613     ┆ 3.8879  ┆ 1.31878 │
│ …     ┆ …          ┆ …        ┆ …            ┆ …           ┆ …       ┆ …       │
│ chr21 ┆ 43482838   ┆ 43482984 ┆ chr21_152355 ┆ 3.16698     ┆ 3.84008 ┆ 1.26508 │
│ chr21 ┆ 45324128   ┆ 45324274 ┆ chr21_161715 ┆ 3.1577      ┆ 3.91986 ┆ 1.35521 │
│ chr21 ┆ 46247358   ┆ 46247504 ┆ chr21_166495 ┆ 3.23259     ┆ 4.30524 ┆ 1.63628 │
│ chr21 ┆ 47774948   ┆ 47775094 ┆ chr21_174289 ┆ 3.34895     ┆ 4.25471 ┆ 1.5713  │
│ chr21 ┆ 48014428   ┆ 48014574 ┆ chr21_175557 ┆ 3.03079     ┆ 3.6308  ┆ 1.12371 │
└───────┴────────────┴──────────┴──────────────┴─────────────┴─────────┴─────────┘

Using bedtools intersect to assign the peak value

 95886 HepG2_Male.histone.H3K27ac.peak.bed
 56670 H3K27ac_peaks.gappedPeak
 91863 H3K27ac.bed

 26271 HepG2_Male.histone.H3K27me3.peak.bed
132101 H3K27me3_peaks.gappedPeak
  9145 H3K27me3.bed

 85714 HepG2_Male.histone.H3K4me3.peak.bed
 26824 H3K4me3_peaks.gappedPeak
 84115 H3K4me3.bed

 76681 HepG2_Male.histone.H3K9ac.peak.bed
 60172 H3K9ac_peaks.gappedPeak
 70784 H3K9ac.bed

 34534 HepG2_Male.histone.H3K9me3.peak.bed
 50508 H3K9me3_peaks.gappedPeak
  6551 H3K9me3.bed