In [1]:
import os
import polars as pl

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

# Read the ensembl dataset

In [3]:
# Define the schema
schema = pl.Schema({
    # The ensembl_top1.csv
    'chrom': pl.String,
    'tss -2kb': pl.Int64,
    'tss +2kb': pl.Int64, 
    'test_id': pl.String,
    'gene_id': pl.String,
    'chrom_name': pl.String,
    'gene_start': pl.Int64,
    'gene_end': pl.Int64,
    'strand': pl.Int64,
    'gene_name': pl.String,
    'gene_stable_id': pl.String,
    'gene_type': pl.String,
    'tss': pl.Int64,
    'locus': pl.String,
    'orig_start': pl.Int64, 
    'orig_end': pl.Int64,
})

In [4]:
# Load the ensembl dataset using declared schema
df = pl.read_csv(
    os.path.join(DATASET_PATH, 'ensembl_top1.csv'),
    separator="\t",
    has_header=False,
    new_columns=list(schema.keys()),
    schema_overrides=schema
)

In [5]:
df

shape: (22_154, 16)
┌───────┬──────────┬──────────┬─────────────┬───┬──────────┬───────────────┬────────────┬──────────┐
│ chrom ┆ tss -2kb ┆ tss +2kb ┆ test_id     ┆ … ┆ tss      ┆ locus         ┆ orig_start ┆ orig_end │
│ ---   ┆ ---      ┆ ---      ┆ ---         ┆   ┆ ---      ┆ ---           ┆ ---        ┆ ---      │
│ str   ┆ i64      ┆ i64      ┆ str         ┆   ┆ i64      ┆ str           ┆ i64        ┆ i64      │
╞═══════╪══════════╪══════════╪═════════════╪═══╪══════════╪═══════════════╪════════════╪══════════╡
│ chr1  ┆ 67091    ┆ 71091    ┆ XLOC_000001 ┆ … ┆ 69091    ┆ chr1:69090-70 ┆ 69090      ┆ 70008    │
│       ┆          ┆          ┆             ┆   ┆          ┆ 008           ┆            ┆          │
│ chr1  ┆ 365640   ┆ 369640   ┆ XLOC_000003 ┆ … ┆ 367640   ┆ chr1:367658-3 ┆ 367658     ┆ 368597   │
│       ┆          ┆          ┆             ┆   ┆          ┆ 68597         ┆            ┆          │
│ chr1  ┆ 858260   ┆ 862260   ┆ XLOC_000006 ┆ … ┆ 860260   ┆ chr1:851135-9 ┆ 851135     ┆ 917473   │
│       ┆          ┆          ┆             ┆   ┆          ┆ 17473         ┆            ┆          │
│ chr1  ┆ 858260   ┆ 862260   ┆ XLOC_000007 ┆ … ┆ 860260   ┆ chr1:851135-9 ┆ 851135     ┆ 917473   │
│       ┆          ┆          ┆             ┆   ┆          ┆ 17473         ┆            ┆          │
│ chr1  ┆ 946803   ┆ 950803   ┆ XLOC_000008 ┆ … ┆ 948803   ┆ chr1:948846-9 ┆ 948846     ┆ 949919   │
│       ┆          ┆          ┆             ┆   ┆          ┆ 49919         ┆            ┆          │
│ …     ┆ …        ┆ …        ┆ …           ┆ … ┆ …        ┆ …             ┆ …          ┆ …        │
│ chrY  ┆ 24327129 ┆ 24331129 ┆ XLOC_030009 ┆ … ┆ 24329129 ┆ chrY:24314688 ┆ 24314688   ┆ 24329089 │
│       ┆          ┆          ┆             ┆   ┆          ┆ -24329089     ┆            ┆          │
│ chrY  ┆ 25343241 ┆ 25347241 ┆ XLOC_030012 ┆ … ┆ 25345241 ┆ chrY:25275501 ┆ 25275501   ┆ 25345239 │
│       ┆          ┆          ┆             ┆   ┆          ┆ -25345239     ┆            ┆          │
│ chrY  ┆ 26192166 ┆ 26196166 ┆ XLOC_030014 ┆ … ┆ 26194166 ┆ chrY:26191376 ┆ 26191376   ┆ 26194161 │
│       ┆          ┆          ┆             ┆   ┆          ┆ -26194161     ┆            ┆          │
│ chrY  ┆ 26957626 ┆ 26961626 ┆ XLOC_030017 ┆ … ┆ 26959626 ┆ chrY:26909221 ┆ 26909221   ┆ 26959517 │
│       ┆          ┆          ┆             ┆   ┆          ┆ -26959517     ┆            ┆          │
│ chrY  ┆ 27206695 ┆ 27210695 ┆ XLOC_030018 ┆ … ┆ 27208695 ┆ chrY:27177049 ┆ 27177049   ┆ 27198251 │
│       ┆          ┆          ┆             ┆   ┆          ┆ -27198251     ┆            ┆          │
└───────┴──────────┴──────────┴─────────────┴───┴──────────┴───────────────┴────────────┴──────────┘

In [6]:
# Remove the previous tss -2k and tss +2k
df = df.drop(["tss -2kb", "tss +2kb"])

In [7]:
df

shape: (22_154, 14)
┌───────┬────────────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬──────────┐
│ chrom ┆ test_id    ┆ gene_id    ┆ chrom_name ┆ … ┆ tss      ┆ locus      ┆ orig_start ┆ orig_end │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---        ┆ ---      │
│ str   ┆ str        ┆ str        ┆ str        ┆   ┆ i64      ┆ str        ┆ i64        ┆ i64      │
╞═══════╪════════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪══════════╡
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 69091    ┆ chr1:69090 ┆ 69090      ┆ 70008    │
│       ┆ 1          ┆ 1          ┆            ┆   ┆          ┆ -70008     ┆            ┆          │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 367640   ┆ chr1:36765 ┆ 367658     ┆ 368597   │
│       ┆ 3          ┆ 3          ┆            ┆   ┆          ┆ 8-368597   ┆            ┆          │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 860260   ┆ chr1:85113 ┆ 851135     ┆ 917473   │
│       ┆ 6          ┆ 6          ┆            ┆   ┆          ┆ 5-917473   ┆            ┆          │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 860260   ┆ chr1:85113 ┆ 851135     ┆ 917473   │
│       ┆ 7          ┆ 7          ┆            ┆   ┆          ┆ 5-917473   ┆            ┆          │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 948803   ┆ chr1:94884 ┆ 948846     ┆ 949919   │
│       ┆ 8          ┆ 8          ┆            ┆   ┆          ┆ 6-949919   ┆            ┆          │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …          ┆ …          ┆ …        │
│ chrY  ┆ XLOC_03000 ┆ XLOC_03000 ┆ Y          ┆ … ┆ 24329129 ┆ chrY:24314 ┆ 24314688   ┆ 24329089 │
│       ┆ 9          ┆ 9          ┆            ┆   ┆          ┆ 688-243290 ┆            ┆          │
│       ┆            ┆            ┆            ┆   ┆          ┆ 89         ┆            ┆          │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 25345241 ┆ chrY:25275 ┆ 25275501   ┆ 25345239 │
│       ┆ 2          ┆ 2          ┆            ┆   ┆          ┆ 501-253452 ┆            ┆          │
│       ┆            ┆            ┆            ┆   ┆          ┆ 39         ┆            ┆          │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26194166 ┆ chrY:26191 ┆ 26191376   ┆ 26194161 │
│       ┆ 4          ┆ 4          ┆            ┆   ┆          ┆ 376-261941 ┆            ┆          │
│       ┆            ┆            ┆            ┆   ┆          ┆ 61         ┆            ┆          │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26959626 ┆ chrY:26909 ┆ 26909221   ┆ 26959517 │
│       ┆ 7          ┆ 7          ┆            ┆   ┆          ┆ 221-269595 ┆            ┆          │
│       ┆            ┆            ┆            ┆   ┆          ┆ 17         ┆            ┆          │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 27208695 ┆ chrY:27177 ┆ 27177049   ┆ 27198251 │
│       ┆ 8          ┆ 8          ┆            ┆   ┆          ┆ 049-271982 ┆            ┆          │
│       ┆            ┆            ┆            ┆   ┆          ┆ 51         ┆            ┆          │
└───────┴────────────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴──────────┘

In [8]:
# Add the column for +/- 5kb from TSS
df = df.with_columns(
    (pl.col('tss') - 5000).alias('tss_minus_5k'),
    (pl.col('tss') + 5000).alias('tss_plus_5k')
)

In [9]:
df

shape: (22_154, 16)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ chrom ┆ test_id    ┆ gene_id    ┆ chrom_name ┆ … ┆ orig_start ┆ orig_end ┆ tss_minus ┆ tss_plus_ │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ _5k       ┆ 5k        │
│ str   ┆ str        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64      ┆ ---       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆            ┆          ┆ i64       ┆ i64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 69090      ┆ 70008    ┆ 64091     ┆ 74091     │
│       ┆ 1          ┆ 1          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 367658     ┆ 368597   ┆ 362640    ┆ 372640    │
│       ┆ 3          ┆ 3          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 851135     ┆ 917473   ┆ 855260    ┆ 865260    │
│       ┆ 6          ┆ 6          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 851135     ┆ 917473   ┆ 855260    ┆ 865260    │
│       ┆ 7          ┆ 7          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 948846     ┆ 949919   ┆ 943803    ┆ 953803    │
│       ┆ 8          ┆ 8          ┆            ┆   ┆            ┆          ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …         ┆ …         │
│ chrY  ┆ XLOC_03000 ┆ XLOC_03000 ┆ Y          ┆ … ┆ 24314688   ┆ 24329089 ┆ 24324129  ┆ 24334129  │
│       ┆ 9          ┆ 9          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 25275501   ┆ 25345239 ┆ 25340241  ┆ 25350241  │
│       ┆ 2          ┆ 2          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26191376   ┆ 26194161 ┆ 26189166  ┆ 26199166  │
│       ┆ 4          ┆ 4          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26909221   ┆ 26959517 ┆ 26954626  ┆ 26964626  │
│       ┆ 7          ┆ 7          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 27177049   ┆ 27198251 ┆ 27203695  ┆ 27213695  │
│       ┆ 8          ┆ 8          ┆            ┆   ┆            ┆          ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

In [10]:
# Save to parquet
filename = os.path.join(DATASET_PATH, 'ensembl.parquet')
df.write_parquet(filename)

In [11]:
# Test reopen the parquet file
test_df = pl.read_parquet(filename)
test_df

shape: (22_154, 16)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ chrom ┆ test_id    ┆ gene_id    ┆ chrom_name ┆ … ┆ orig_start ┆ orig_end ┆ tss_minus ┆ tss_plus_ │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ _5k       ┆ 5k        │
│ str   ┆ str        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64      ┆ ---       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆            ┆          ┆ i64       ┆ i64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 69090      ┆ 70008    ┆ 64091     ┆ 74091     │
│       ┆ 1          ┆ 1          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 367658     ┆ 368597   ┆ 362640    ┆ 372640    │
│       ┆ 3          ┆ 3          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 851135     ┆ 917473   ┆ 855260    ┆ 865260    │
│       ┆ 6          ┆ 6          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 851135     ┆ 917473   ┆ 855260    ┆ 865260    │
│       ┆ 7          ┆ 7          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chr1  ┆ XLOC_00000 ┆ XLOC_00000 ┆ 1          ┆ … ┆ 948846     ┆ 949919   ┆ 943803    ┆ 953803    │
│       ┆ 8          ┆ 8          ┆            ┆   ┆            ┆          ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …         ┆ …         │
│ chrY  ┆ XLOC_03000 ┆ XLOC_03000 ┆ Y          ┆ … ┆ 24314688   ┆ 24329089 ┆ 24324129  ┆ 24334129  │
│       ┆ 9          ┆ 9          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 25275501   ┆ 25345239 ┆ 25340241  ┆ 25350241  │
│       ┆ 2          ┆ 2          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26191376   ┆ 26194161 ┆ 26189166  ┆ 26199166  │
│       ┆ 4          ┆ 4          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 26909221   ┆ 26959517 ┆ 26954626  ┆ 26964626  │
│       ┆ 7          ┆ 7          ┆            ┆   ┆            ┆          ┆           ┆           │
│ chrY  ┆ XLOC_03001 ┆ XLOC_03001 ┆ Y          ┆ … ┆ 27177049   ┆ 27198251 ┆ 27203695  ┆ 27213695  │
│       ┆ 8          ┆ 8          ┆            ┆   ┆            ┆          ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

In [12]:
# Open the HepG2 expression file
hepg2_df = pl.read_csv(
    os.path.join(DATASET_PATH, 'GSM3718064_HepG2_exp.txt'),
    separator="\t"
)

In [13]:
hepg2_df

shape: (30_032, 14)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬─────────┬──────────┬───────────┐
│ test_id    ┆ gene_id    ┆ gene      ┆ locus     ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significa │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---      ┆ nt        │
│ str        ┆ str        ┆ str       ┆ str       ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---       │
│            ┆            ┆           ┆           ┆   ┆           ┆         ┆          ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪══════════╪═══════════╡
│ XLOC_00000 ┆ XLOC_00000 ┆ OR4F5     ┆ chr1:6909 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 1          ┆ 1          ┆           ┆ 0-70008   ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ LOC100132 ┆ chr1:3238 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 2          ┆ 2          ┆ 062,LOC10 ┆ 91-328581 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆ 0133331   ┆           ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ OR4F29    ┆ chr1:3676 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 3          ┆ 3          ┆           ┆ 58-368597 ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ LOC643837 ┆ chr1:7615 ┆ … ┆ 0.455074  ┆ 0.63585 ┆ 0.999565 ┆ no        │
│ 4          ┆ 4          ┆           ┆ 85-794889 ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ -         ┆ chr1:8402 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 5          ┆ 5          ┆           ┆ 63-843900 ┆   ┆           ┆         ┆          ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …        ┆ …         │
│ XLOC_03002 ┆ XLOC_03002 ┆ -         ┆ chrY:1331 ┆ … ┆ 1.13793   ┆ 0.25685 ┆ 0.999565 ┆ no        │
│ 8          ┆ 8          ┆           ┆ 9431-1332 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 4829      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03002 ┆ XLOC_03002 ┆ -         ┆ chrY:1332 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 9          ┆ 9          ┆           ┆ 5034-1332 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 6120      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:1333 ┆ … ┆ -1.86192  ┆ 0.1249  ┆ 0.999565 ┆ no        │
│ 0          ┆ 0          ┆           ┆ 1089-1333 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 2358      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:1505 ┆ … ┆ -2.11604  ┆ 0.04075 ┆ 0.999565 ┆ no        │
│ 1          ┆ 1          ┆           ┆ 3270-1505 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 3343      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:5900 ┆ … ┆ -0.291421 ┆ 0.7684  ┆ 0.999565 ┆ no        │
│ 2          ┆ 2          ┆           ┆ 1259-5900 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 3893      ┆   ┆           ┆         ┆          ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴─────────┴──────────┴───────────┘

In [14]:
# Join the ensembl and the HepG2 expression
ensembl_HepG2exp_df = df.join(
    hepg2_df,
    left_on = 'gene_id',
    right_on = 'gene_id',
    how = 'left'
)

In [15]:
ensembl_HepG2exp_df

shape: (22_154, 29)
┌───────┬─────────────┬─────────────┬────────────┬───┬───────────┬─────────┬──────────┬────────────┐
│ chrom ┆ test_id     ┆ gene_id     ┆ chrom_name ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significan │
│ ---   ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---       ┆ ---     ┆ ---      ┆ t          │
│ str   ┆ str         ┆ str         ┆ str        ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---        │
│       ┆             ┆             ┆            ┆   ┆           ┆         ┆          ┆ str        │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪═══════════╪═════════╪══════════╪════════════╡
│ chr1  ┆ XLOC_000001 ┆ XLOC_000001 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000003 ┆ XLOC_000003 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000006 ┆ XLOC_000006 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000007 ┆ XLOC_000007 ┆ 1          ┆ … ┆ 0.0707864 ┆ 0.94475 ┆ 0.999565 ┆ no         │
│ chr1  ┆ XLOC_000008 ┆ XLOC_000008 ┆ 1          ┆ … ┆ 0.797534  ┆ 0.42445 ┆ 0.999565 ┆ no         │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …         ┆ …       ┆ …        ┆ …          │
│ chrY  ┆ XLOC_030009 ┆ XLOC_030009 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030012 ┆ XLOC_030012 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030014 ┆ XLOC_030014 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030017 ┆ XLOC_030017 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030018 ┆ XLOC_030018 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
└───────┴─────────────┴─────────────┴────────────┴───┴───────────┴─────────┴──────────┴────────────┘

In [16]:
# Drop the unnecessary column
ensembl_HepG2exp_df = ensembl_HepG2exp_df.drop(['test_id_right', 'locus_right', 'gene', 'sample_1', 'sample_2'])

In [17]:
ensembl_HepG2exp_df

shape: (22_154, 24)
┌───────┬─────────────┬─────────────┬────────────┬───┬───────────┬─────────┬──────────┬────────────┐
│ chrom ┆ test_id     ┆ gene_id     ┆ chrom_name ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significan │
│ ---   ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---       ┆ ---     ┆ ---      ┆ t          │
│ str   ┆ str         ┆ str         ┆ str        ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---        │
│       ┆             ┆             ┆            ┆   ┆           ┆         ┆          ┆ str        │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪═══════════╪═════════╪══════════╪════════════╡
│ chr1  ┆ XLOC_000001 ┆ XLOC_000001 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000003 ┆ XLOC_000003 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000006 ┆ XLOC_000006 ┆ 1          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chr1  ┆ XLOC_000007 ┆ XLOC_000007 ┆ 1          ┆ … ┆ 0.0707864 ┆ 0.94475 ┆ 0.999565 ┆ no         │
│ chr1  ┆ XLOC_000008 ┆ XLOC_000008 ┆ 1          ┆ … ┆ 0.797534  ┆ 0.42445 ┆ 0.999565 ┆ no         │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …         ┆ …       ┆ …        ┆ …          │
│ chrY  ┆ XLOC_030009 ┆ XLOC_030009 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030012 ┆ XLOC_030012 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030014 ┆ XLOC_030014 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030017 ┆ XLOC_030017 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│ chrY  ┆ XLOC_030018 ┆ XLOC_030018 ┆ Y          ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
└───────┴─────────────┴─────────────┴────────────┴───┴───────────┴─────────┴──────────┴────────────┘

In [20]:
ensembl_HepG2exp_df.select(['chrom', 'tss_minus_5k', 'test_id', 'value_1'])

shape: (22_154, 4)
┌───────┬──────────────┬─────────────┬───────────┐
│ chrom ┆ tss_minus_5k ┆ test_id     ┆ value_1   │
│ ---   ┆ ---          ┆ ---         ┆ ---       │
│ str   ┆ i64          ┆ str         ┆ f64       │
╞═══════╪══════════════╪═════════════╪═══════════╡
│ chr1  ┆ 64091        ┆ XLOC_000001 ┆ 0.0       │
│ chr1  ┆ 362640       ┆ XLOC_000003 ┆ 0.0       │
│ chr1  ┆ 855260       ┆ XLOC_000006 ┆ 0.0888452 │
│ chr1  ┆ 855260       ┆ XLOC_000007 ┆ 4.04743   │
│ chr1  ┆ 943803       ┆ XLOC_000008 ┆ 26.7934   │
│ …     ┆ …            ┆ …           ┆ …         │
│ chrY  ┆ 24324129     ┆ XLOC_030009 ┆ 0.0       │
│ chrY  ┆ 25340241     ┆ XLOC_030012 ┆ 0.0       │
│ chrY  ┆ 26189166     ┆ XLOC_030014 ┆ 0.0       │
│ chrY  ┆ 26954626     ┆ XLOC_030017 ┆ 0.0       │
│ chrY  ┆ 27203695     ┆ XLOC_030018 ┆ 0.0       │
└───────┴──────────────┴─────────────┴───────────┘

In [21]:
ensembl_HepG2exp_df.write_parquet(os.path.join(DATASET_PATH, 'ensembl_HepG2exp.parquet'))

In [23]:
# Find the column list
ensembl_HepG2exp_df.columns

['chrom',
 'test_id',
 'gene_id',
 'chrom_name',
 'gene_start',
 'gene_end',
 'strand',
 'gene_name',
 'gene_stable_id',
 'gene_type',
 'tss',
 'locus',
 'orig_start',
 'orig_end',
 'tss_minus_5k',
 'tss_plus_5k',
 'status',
 'value_1',
 'value_2',
 'log2(fold_change)',
 'test_stat',
 'p_value',
 'q_value',
 'significant']

In [41]:
reordered_columns = ['chrom',
 'tss_minus_5k',
 'tss_plus_5k',
 'test_id',
 'gene_id',
 'chrom_name',
 'gene_start',
 'gene_end',
 'strand',
 'gene_name',
 'gene_stable_id',
 'gene_type',
 'tss',
 'locus',
 'orig_start',
 'orig_end',
 'status',
 'value_1',
 'value_2',
 'log2(fold_change)',
 'test_stat',
 'p_value',
 'q_value',
 'significant'
]

In [42]:
ensembl_HepG2exp_reordered_df = ensembl_HepG2exp_df.select(reordered_columns)

In [43]:
ensembl_HepG2exp_reordered_df

shape: (22_154, 24)
┌───────┬─────────────┬─────────────┬────────────┬───┬───────────┬─────────┬──────────┬────────────┐
│ chrom ┆ tss_minus_5 ┆ tss_plus_5k ┆ test_id    ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significan │
│ ---   ┆ k           ┆ ---         ┆ ---        ┆   ┆ ---       ┆ ---     ┆ ---      ┆ t          │
│ str   ┆ ---         ┆ i64         ┆ str        ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---        │
│       ┆ i64         ┆             ┆            ┆   ┆           ┆         ┆          ┆ str        │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪═══════════╪═════════╪══════════╪════════════╡
│ chr1  ┆ 64091       ┆ 74091       ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 1          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 362640      ┆ 372640      ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 3          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 6          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0.0707864 ┆ 0.94475 ┆ 0.999565 ┆ no         │
│       ┆             ┆             ┆ 7          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 943803      ┆ 953803      ┆ XLOC_00000 ┆ … ┆ 0.797534  ┆ 0.42445 ┆ 0.999565 ┆ no         │
│       ┆             ┆             ┆ 8          ┆   ┆           ┆         ┆          ┆            │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …         ┆ …       ┆ …        ┆ …          │
│ chrY  ┆ 24324129    ┆ 24334129    ┆ XLOC_03000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 9          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 25340241    ┆ 25350241    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 2          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 26189166    ┆ 26199166    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 4          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 26954626    ┆ 26964626    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 7          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 27203695    ┆ 27213695    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 8          ┆   ┆           ┆         ┆          ┆            │
└───────┴─────────────┴─────────────┴────────────┴───┴───────────┴─────────┴──────────┴────────────┘

In [46]:
# Save the dataset
ensembl_HepG2exp_reordered_df.write_parquet(os.path.join(DATASET_PATH, 'ensembl_HepG2exp.parquet'))

In [47]:
# Save the dataset for bedtools intersection
ensembl_HepG2exp_reordered_df.write_csv(os.path.join(DATASET_PATH, 'ensembl_top1.csv'), include_header=False, separator='\t')