In [1]:
import os
import polars as pl

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [3]:
# Define the schema
intersect_schema = pl.Schema({
    # The ensembl_top1.csv columns
    'chrom': pl.String,
    'tss -2kb': pl.Int64,
    'tss +2kb': pl.Int64, 
    'test_id': pl.String,
    'gene_id': pl.String,
    'chrom_name': pl.String,
    'gene_start': pl.Int64,
    'gene_end': pl.Int64,
    'strand': pl.Int64,
    'gene_name': pl.String,
    'gene_stable_id': pl.String,
    'gene_type': pl.String,
    'tss': pl.Int64,
    'locus': pl.String,
    'orig_start': pl.Int64, 
    'orig_end': pl.Int64,

    # The HepG2 histone columns
    'chrom_h': pl.String,
    'start_h': pl.Int64,
    'end_h': pl.Int64,
    'name_h': pl.String,

    # gappedPeak columns
    "chrom_p": pl.String,
    "chromStart_p": pl.Int64, 
    "chromEnd_p": pl.Int64, 
    "name_p": pl.String, 
    "score_p": pl.Float64, 
    "strand_p": pl.String,
    "thickStart": pl.Int64,
    "thickEnd": pl.Int64,
    "itemRgb": pl.Int64,
    "blockCount": pl.Int64,
    "blockSizes": pl.String,
    "blockStarts": pl.String,
    "signalValue": pl.Float64,
    "pValue": pl.Float64,
    "qValue": pl.Float64
})

In [4]:
# Load the ensembl dataset using declared schema
df = pl.read_csv(
    os.path.join(DATASET_PATH, 'ensembl_H3K9me3.bed'),
    separator="\t",
    has_header=False,
    schema = intersect_schema
)

In [5]:
df

shape: (441, 35)
┌───────┬───────────┬───────────┬─────────────┬───┬─────────────┬─────────────┬─────────┬─────────┐
│ chrom ┆ tss -2kb  ┆ tss +2kb  ┆ test_id     ┆ … ┆ blockStarts ┆ signalValue ┆ pValue  ┆ qValue  │
│ ---   ┆ ---       ┆ ---       ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---     ┆ ---     │
│ str   ┆ i64       ┆ i64       ┆ str         ┆   ┆ str         ┆ f64         ┆ f64     ┆ f64     │
╞═══════╪═══════════╪═══════════╪═════════════╪═══╪═════════════╪═════════════╪═════════╪═════════╡
│ chr1  ┆ 8084368   ┆ 8088368   ┆ XLOC_000068 ┆ … ┆ 0,180,2005  ┆ 4.1465      ┆ 9.34128 ┆ 5.92356 │
│ chr1  ┆ 27646651  ┆ 27650651  ┆ XLOC_000231 ┆ … ┆ 0,164       ┆ 2.87371     ┆ 5.2025  ┆ 2.30996 │
│ chr1  ┆ 27646651  ┆ 27650651  ┆ XLOC_000232 ┆ … ┆ 0,164       ┆ 2.87371     ┆ 5.2025  ┆ 2.30996 │
│ chr1  ┆ 36271773  ┆ 36275773  ┆ XLOC_000296 ┆ … ┆ 0,409       ┆ 3.09149     ┆ 4.16467 ┆ 1.5459  │
│ chr1  ┆ 153649113 ┆ 153653113 ┆ XLOC_000793 ┆ … ┆ 0,186       ┆ 2.65554     ┆ 3.7538  ┆ 1.25569 │
│ …     ┆ …         ┆ …         ┆ …           ┆ … ┆ …           ┆ …           ┆ …       ┆ …       │
│ chrX  ┆ 30669476  ┆ 30673476  ┆ XLOC_028866 ┆ … ┆ 0,395       ┆ 3.32175     ┆ 4.44313 ┆ 1.72356 │
│ chrX  ┆ 149105029 ┆ 149109029 ┆ XLOC_029233 ┆ … ┆ 0,338       ┆ 3.34067     ┆ 4.64775 ┆ 1.88922 │
│ chrX  ┆ 133117922 ┆ 133121922 ┆ XLOC_029663 ┆ … ┆ 0,157       ┆ 3.16462     ┆ 3.95825 ┆ 1.38578 │
│ chrX  ┆ 133117922 ┆ 133121922 ┆ XLOC_029663 ┆ … ┆ 0,165,754   ┆ 4.87501     ┆ 8.12474 ┆ 4.73597 │
│ chrX  ┆ 149105029 ┆ 149109029 ┆ XLOC_029738 ┆ … ┆ 0,338       ┆ 3.34067     ┆ 4.64775 ┆ 1.88922 │
└───────┴───────────┴───────────┴─────────────┴───┴─────────────┴─────────────┴─────────┴─────────┘

In [6]:
# Remove the previous tss -2k and tss +2k
df = df.drop(["tss -2kb", "tss +2kb"])

In [7]:
df

shape: (441, 33)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬────────────┬─────────┬─────────┐
│ chrom ┆ test_id     ┆ gene_id     ┆ chrom_name ┆ … ┆ blockStart ┆ signalValu ┆ pValue  ┆ qValue  │
│ ---   ┆ ---         ┆ ---         ┆ ---        ┆   ┆ s          ┆ e          ┆ ---     ┆ ---     │
│ str   ┆ str         ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ f64     │
│       ┆             ┆             ┆            ┆   ┆ str        ┆ f64        ┆         ┆         │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪════════════╪═════════╪═════════╡
│ chr1  ┆ XLOC_000068 ┆ XLOC_000068 ┆ 1          ┆ … ┆ 0,180,2005 ┆ 4.1465     ┆ 9.34128 ┆ 5.92356 │
│ chr1  ┆ XLOC_000231 ┆ XLOC_000231 ┆ 1          ┆ … ┆ 0,164      ┆ 2.87371    ┆ 5.2025  ┆ 2.30996 │
│ chr1  ┆ XLOC_000232 ┆ XLOC_000232 ┆ 1          ┆ … ┆ 0,164      ┆ 2.87371    ┆ 5.2025  ┆ 2.30996 │
│ chr1  ┆ XLOC_000296 ┆ XLOC_000296 ┆ 1          ┆ … ┆ 0,409      ┆ 3.09149    ┆ 4.16467 ┆ 1.5459  │
│ chr1  ┆ XLOC_000793 ┆ XLOC_000793 ┆ 1          ┆ … ┆ 0,186      ┆ 2.65554    ┆ 3.7538  ┆ 1.25569 │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …       │
│ chrX  ┆ XLOC_028866 ┆ XLOC_028866 ┆ X          ┆ … ┆ 0,395      ┆ 3.32175    ┆ 4.44313 ┆ 1.72356 │
│ chrX  ┆ XLOC_029233 ┆ XLOC_029233 ┆ X          ┆ … ┆ 0,338      ┆ 3.34067    ┆ 4.64775 ┆ 1.88922 │
│ chrX  ┆ XLOC_029663 ┆ XLOC_029663 ┆ X          ┆ … ┆ 0,157      ┆ 3.16462    ┆ 3.95825 ┆ 1.38578 │
│ chrX  ┆ XLOC_029663 ┆ XLOC_029663 ┆ X          ┆ … ┆ 0,165,754  ┆ 4.87501    ┆ 8.12474 ┆ 4.73597 │
│ chrX  ┆ XLOC_029738 ┆ XLOC_029738 ┆ X          ┆ … ┆ 0,338      ┆ 3.34067    ┆ 4.64775 ┆ 1.88922 │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴────────────┴─────────┴─────────┘