In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [3]:
# Function to read histone file and returns the data frame
def load_histone(filename):
    # Declare the intersect file schema
    # Define the schema for ensembl and gappedPeak dataset
    intersect_schema = pl.Schema({
        # The ensembl_top1.csv columns
        'chrom': pl.String,
        'tss_minus_5k': pl.Int64,
        'tss_plus_5k': pl.Int64, 
        'test_id': pl.String,
        'gene_id': pl.String,
        'chrom_name': pl.String,
        'gene_start': pl.Int64,
        'gene_end': pl.Int64,
        'strand': pl.Int64,
        'gene_name': pl.String,
        'gene_stable_id': pl.String,
        'gene_type': pl.String,
        'tss': pl.Int64,
        'locus': pl.String,
        'orig_start': pl.Int64, 
        'orig_end': pl.Int64,
        
        # gappedPeak columns
        "chrom_p": pl.String,
        "chromStart_p": pl.Int64, 
        "chromEnd_p": pl.Int64, 
        "name_p": pl.String, 
        "score_p": pl.Float64, 
        "strand_p": pl.String,
        "thickStart": pl.Int64,
        "thickEnd": pl.Int64,
        "itemRgb": pl.Int64,
        "blockCount": pl.Int64,
        "blockSizes": pl.String,
        "blockStarts": pl.String,
        "signalValue": pl.Float64,
        "pValue": pl.Float64,
        "qValue": pl.Float64
    })

    # Open file
    histone_df = pl.read_csv(
            filename,
            separator="\t",
            has_header = False,
            schema = intersect_schema   
        )
    
    return histone_df

In [4]:
def create_empty_dataframe(histone_name):
    schema = pl.Schema({
        'gene_id': pl.String,
        histone_name: pl.List(pl.Float64),
        f'{histone_name}_wc': pl.UInt32,
        f'{histone_name}_len': pl.UInt32
    })

    df = pl.DataFrame(schema=schema)

    return df

In [33]:
def build_matrix(genes_df, histone_df, histone_name):
    # Build the dataframe with window
    genes_with_windows = genes_df.with_columns([
        pl.int_ranges(pl.col('tss_minus_5k'), pl.col('tss_plus_5k'), 100).alias('window_start')
    ]).explode('window_start')

    genes_with_windows = genes_with_windows.with_columns([
            (pl.col('window_start') + 100).alias('window_end')
    ])

    # Join genes with histone data
    joined_df = genes_with_windows.join(
        histone_df,
        left_on='gene_id',
        right_on='gene_id',
        how='left'
    )

    # Filter and calculate average signal value
    result_df = joined_df.filter(
        (pl.col('chromStart_p') < pl.col('window_end')) &
        (pl.col('chromEnd_p') > pl.col('window_start'))
    ).group_by(['gene_id', 'window_start'], maintain_order=True).agg([
        pl.col('signalValue').mean().alias(histone_name)
    ]).sort(['gene_id', 'window_start'])

    # Find the gene without histone match
    genes_wo_histone = genes_with_windows.join(
        result_df,
        on=["gene_id", "window_start"],
        how="anti"
    )

    # Add the signalValue column so it can be merged
    genes_wo_histone = genes_wo_histone.with_columns(
        signalValue = pl.lit(0.0).cast(pl.Float64)
    )

    # Aggregate the genes without histone result
    genes_wo_histone = genes_wo_histone.group_by(['gene_id', 'window_start'], maintain_order=True).agg([
            pl.col('signalValue').mean().alias(histone_name)
        ]).sort(['gene_id', 'window_start'])

    # Merge both (results and genes without histone)
    result_df.extend(genes_wo_histone)

    # Sort the result dataframe by gene_id and window start for aggregation
    sorted_result_df = result_df.sort(['gene_id', 'window_start'])
    
    # Group by to make array of features
    matrix_df = (
        sorted_result_df
        .with_columns(pl.col(histone_name).fill_null(0))
        .group_by(['gene_id'], maintain_order=True)
        .agg(pl.col(histone_name))
        .sort('gene_id')
    )

    # Add the count and length of array feature for checking
    matrix_control_df = matrix_df.with_columns(
        pl.col(histone_name)
        .list.eval(pl.element().is_not_null() & (pl.element() > 0))
        .list.sum()
        .alias(f"{histone_name}_wc")
    )

    matrix_control_df = matrix_control_df.with_columns(
        pl.col(histone_name).list.len().alias(f"{histone_name}_len")
    )

    # Finally, return the gene_id with its histone features
    return matrix_control_df

In [34]:
# Getting histone in chunk
def get_histone_features(genes_df, histone_df, histone_name):
    
    genes_w_histone = create_empty_dataframe(histone_name)
    
    for i, chunk in enumerate(genes_df.iter_slices(n_rows=100)):
        if i % 100 == 0:
            print(f"Processing {histone_name}: {i*100}/{genes_df.height}")
        
        result = build_matrix(chunk, histone_df, histone_name)
        genes_w_histone.extend(result)

    print(f"Processing {histone_name} features finished.")
    return genes_w_histone

In [35]:
# Load the HepG2 expression file
genes_df = pl.read_parquet(os.path.join(DATASET_PATH, 'ensembl_HepG2exp.parquet'))

In [36]:
genes_df

shape: (22_154, 24)
┌───────┬─────────────┬─────────────┬────────────┬───┬───────────┬─────────┬──────────┬────────────┐
│ chrom ┆ tss_minus_5 ┆ tss_plus_5k ┆ test_id    ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significan │
│ ---   ┆ k           ┆ ---         ┆ ---        ┆   ┆ ---       ┆ ---     ┆ ---      ┆ t          │
│ str   ┆ ---         ┆ i64         ┆ str        ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---        │
│       ┆ i64         ┆             ┆            ┆   ┆           ┆         ┆          ┆ str        │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪═══════════╪═════════╪══════════╪════════════╡
│ chr1  ┆ 64091       ┆ 74091       ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 1          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 362640      ┆ 372640      ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 3          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 6          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0.0707864 ┆ 0.94475 ┆ 0.999565 ┆ no         │
│       ┆             ┆             ┆ 7          ┆   ┆           ┆         ┆          ┆            │
│ chr1  ┆ 943803      ┆ 953803      ┆ XLOC_00000 ┆ … ┆ 0.797534  ┆ 0.42445 ┆ 0.999565 ┆ no         │
│       ┆             ┆             ┆ 8          ┆   ┆           ┆         ┆          ┆            │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …         ┆ …       ┆ …        ┆ …          │
│ chrY  ┆ 24324129    ┆ 24334129    ┆ XLOC_03000 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 9          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 25340241    ┆ 25350241    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 2          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 26189166    ┆ 26199166    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 4          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 26954626    ┆ 26964626    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 7          ┆   ┆           ┆         ┆          ┆            │
│ chrY  ┆ 27203695    ┆ 27213695    ┆ XLOC_03001 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no         │
│       ┆             ┆             ┆ 8          ┆   ┆           ┆         ┆          ┆            │
└───────┴─────────────┴─────────────┴────────────┴───┴───────────┴─────────┴──────────┴────────────┘

In [37]:
# Load the histone dataset
H3K9ac_df = load_histone(os.path.join(DATASET_PATH, 'H3K9ac.bed'))
H3K9me3_df = load_histone(os.path.join(DATASET_PATH, 'H3K9me3.bed'))
H3K4me3_df = load_histone(os.path.join(DATASET_PATH, 'H3K4me3.bed'))
H3K27ac_df = load_histone(os.path.join(DATASET_PATH, 'H3K27ac.bed'))
H3K27me3_df = load_histone(os.path.join(DATASET_PATH, 'H3K27me3.bed'))

In [38]:
# Build the matrix
genes_w_H3K9ac_df = get_histone_features(genes_df, H3K9ac_df, 'H3K9ac')
genes_w_H3K9me3_df = get_histone_features(genes_df, H3K9me3_df, 'H3K9me3')
genes_w_H3K4me3_df = get_histone_features(genes_df, H3K4me3_df, 'H3K4me3')
genes_w_H3K27ac_df = get_histone_features(genes_df, H3K27ac_df, 'H3K27ac')
genes_w_H3K27me3_df = get_histone_features(genes_df, H3K27me3_df, 'H3K27me3')

Processing H3K9ac: 0/22154
Processing H3K9ac: 10000/22154
Processing H3K9ac: 20000/22154
Processing H3K9ac features finished.
Processing H3K9me3: 0/22154
Processing H3K9me3: 10000/22154
Processing H3K9me3: 20000/22154
Processing H3K9me3 features finished.
Processing H3K4me3: 0/22154
Processing H3K4me3: 10000/22154
Processing H3K4me3: 20000/22154
Processing H3K4me3 features finished.
Processing H3K27ac: 0/22154
Processing H3K27ac: 10000/22154
Processing H3K27ac: 20000/22154
Processing H3K27ac features finished.
Processing H3K27me3: 0/22154
Processing H3K27me3: 10000/22154
Processing H3K27me3: 20000/22154
Processing H3K27me3 features finished.

# Checking the generated features

In [39]:
genes_w_H3K9ac_df.filter(pl.col('H3K9ac_wc') > 0).sort(['H3K9ac_wc'], descending=True)

shape: (16_628, 4)
┌─────────────┬───────────────────────────────┬───────────┬────────────┐
│ gene_id     ┆ H3K9ac                        ┆ H3K9ac_wc ┆ H3K9ac_len │
│ ---         ┆ ---                           ┆ ---       ┆ ---        │
│ str         ┆ list[f64]                     ┆ u32       ┆ u32        │
╞═════════════╪═══════════════════════════════╪═══════════╪════════════╡
│ XLOC_018174 ┆ [6.76952, 6.76952, … 6.76952] ┆ 100       ┆ 100        │
│ XLOC_026220 ┆ [20.8229, 20.8229, … 20.8229] ┆ 100       ┆ 100        │
│ XLOC_016670 ┆ [6.31747, 6.31747, … 0.0]     ┆ 99        ┆ 100        │
│ XLOC_017014 ┆ [6.31747, 6.31747, … 0.0]     ┆ 99        ┆ 100        │
│ XLOC_012112 ┆ [13.6032, 13.6032, … 5.20025] ┆ 98        ┆ 100        │
│ …           ┆ …                             ┆ …         ┆ …          │
│ XLOC_014577 ┆ [0.0, 0.0, … 2.34153]         ┆ 1         ┆ 100        │
│ XLOC_016974 ┆ [3.36934, 0.0, … 0.0]         ┆ 1         ┆ 100        │
│ XLOC_017925 ┆ [4.22743, 0.0, … 0.0]         ┆ 1         ┆ 100        │
│ XLOC_022766 ┆ [3.65852, 0.0, … 0.0]         ┆ 1         ┆ 100        │
│ XLOC_022939 ┆ [3.90491, 0.0, … 0.0]         ┆ 1         ┆ 100        │
└─────────────┴───────────────────────────────┴───────────┴────────────┘

In [40]:
genes_w_H3K9ac_df.filter(pl.col('H3K9ac_len') < 100).sort(['H3K9ac_wc'], descending=True)

shape: (0, 4)
┌─────────┬───────────┬───────────┬────────────┐
│ gene_id ┆ H3K9ac    ┆ H3K9ac_wc ┆ H3K9ac_len │
│ ---     ┆ ---       ┆ ---       ┆ ---        │
│ str     ┆ list[f64] ┆ u32       ┆ u32        │
╞═════════╪═══════════╪═══════════╪════════════╡
└─────────┴───────────┴───────────┴────────────┘

In [41]:
genes_w_H3K9me3_df.filter(pl.col('H3K9me3_wc') > 0).sort(['H3K9me3_wc'], descending=True)

shape: (11_681, 4)
┌─────────────┬──────────────────────────────┬────────────┬─────────────┐
│ gene_id     ┆ H3K9me3                      ┆ H3K9me3_wc ┆ H3K9me3_len │
│ ---         ┆ ---                          ┆ ---        ┆ ---         │
│ str         ┆ list[f64]                    ┆ u32        ┆ u32         │
╞═════════════╪══════════════════════════════╪════════════╪═════════════╡
│ XLOC_015764 ┆ [3.87003, 3.87003, … 0.0]    ┆ 56         ┆ 100         │
│ XLOC_015765 ┆ [3.87003, 3.87003, … 0.0]    ┆ 56         ┆ 100         │
│ XLOC_026220 ┆ [4.03214, 4.03214, … 2.9126] ┆ 53         ┆ 100         │
│ XLOC_016736 ┆ [0.0, 2.8677, … 0.0]         ┆ 52         ┆ 100         │
│ XLOC_016737 ┆ [0.0, 2.8677, … 0.0]         ┆ 52         ┆ 100         │
│ …           ┆ …                            ┆ …          ┆ …           │
│ XLOC_020357 ┆ [2.97696, 0.0, … 0.0]        ┆ 1          ┆ 100         │
│ XLOC_021908 ┆ [3.21938, 0.0, … 0.0]        ┆ 1          ┆ 100         │
│ XLOC_027689 ┆ [5.93701, 0.0, … 0.0]        ┆ 1          ┆ 100         │
│ XLOC_028132 ┆ [2.60381, 0.0, … 0.0]        ┆ 1          ┆ 100         │
│ XLOC_028196 ┆ [5.93701, 0.0, … 0.0]        ┆ 1          ┆ 100         │
└─────────────┴──────────────────────────────┴────────────┴─────────────┘

In [42]:
genes_w_H3K9me3_df.filter(pl.col('H3K9me3_len') < 100).sort(['H3K9me3_wc'], descending=True)

shape: (0, 4)
┌─────────┬───────────┬────────────┬─────────────┐
│ gene_id ┆ H3K9me3   ┆ H3K9me3_wc ┆ H3K9me3_len │
│ ---     ┆ ---       ┆ ---        ┆ ---         │
│ str     ┆ list[f64] ┆ u32        ┆ u32         │
╞═════════╪═══════════╪════════════╪═════════════╡
└─────────┴───────────┴────────────┴─────────────┘

In [43]:
genes_w_H3K4me3_df.filter(pl.col('H3K4me3_wc') > 0).sort(['H3K4me3_wc'], descending=True)

shape: (15_699, 4)
┌─────────────┬───────────────────────────────┬────────────┬─────────────┐
│ gene_id     ┆ H3K4me3                       ┆ H3K4me3_wc ┆ H3K4me3_len │
│ ---         ┆ ---                           ┆ ---        ┆ ---         │
│ str         ┆ list[f64]                     ┆ u32        ┆ u32         │
╞═════════════╪═══════════════════════════════╪════════════╪═════════════╡
│ XLOC_026220 ┆ [37.7847, 37.7847, … 37.7847] ┆ 100        ┆ 100         │
│ XLOC_016496 ┆ [10.8953, 10.8953, … 3.13488] ┆ 96         ┆ 100         │
│ XLOC_016856 ┆ [10.8953, 10.8953, … 3.13488] ┆ 96         ┆ 100         │
│ XLOC_016857 ┆ [10.8953, 10.8953, … 3.13488] ┆ 96         ┆ 100         │
│ XLOC_015059 ┆ [0.0, 0.0, … 23.5672]         ┆ 95         ┆ 100         │
│ …           ┆ …                             ┆ …          ┆ …           │
│ XLOC_000836 ┆ [0.0, 0.0, … 4.3937]          ┆ 1          ┆ 100         │
│ XLOC_016974 ┆ [3.79334, 0.0, … 0.0]         ┆ 1          ┆ 100         │
│ XLOC_017674 ┆ [0.0, 0.0, … 5.41996]         ┆ 1          ┆ 100         │
│ XLOC_017947 ┆ [0.0, 0.0, … 5.41996]         ┆ 1          ┆ 100         │
│ XLOC_022433 ┆ [6.69632, 0.0, … 0.0]         ┆ 1          ┆ 100         │
└─────────────┴───────────────────────────────┴────────────┴─────────────┘

In [44]:
genes_w_H3K4me3_df.filter(pl.col('H3K4me3_len') < 100).sort(['H3K4me3_wc'], descending=True)

shape: (0, 4)
┌─────────┬───────────┬────────────┬─────────────┐
│ gene_id ┆ H3K4me3   ┆ H3K4me3_wc ┆ H3K4me3_len │
│ ---     ┆ ---       ┆ ---        ┆ ---         │
│ str     ┆ list[f64] ┆ u32        ┆ u32         │
╞═════════╪═══════════╪════════════╪═════════════╡
└─────────┴───────────┴────────────┴─────────────┘

In [45]:
genes_w_H3K27ac_df.filter(pl.col('H3K27ac_wc') > 0).sort(['H3K27ac_wc'], descending=True)

shape: (14_344, 4)
┌─────────────┬───────────────────────────────┬────────────┬─────────────┐
│ gene_id     ┆ H3K27ac                       ┆ H3K27ac_wc ┆ H3K27ac_len │
│ ---         ┆ ---                           ┆ ---        ┆ ---         │
│ str         ┆ list[f64]                     ┆ u32        ┆ u32         │
╞═════════════╪═══════════════════════════════╪════════════╪═════════════╡
│ XLOC_012112 ┆ [14.2545, 14.2545, … 14.2545] ┆ 100        ┆ 100         │
│ XLOC_012331 ┆ [14.2545, 14.2545, … 14.2545] ┆ 100        ┆ 100         │
│ XLOC_026220 ┆ [28.8464, 28.8464, … 28.8464] ┆ 100        ┆ 100         │
│ XLOC_026926 ┆ [15.0089, 15.0089, … 15.0089] ┆ 100        ┆ 100         │
│ XLOC_029663 ┆ [11.9058, 11.9058, … 11.9058] ┆ 100        ┆ 100         │
│ …           ┆ …                             ┆ …          ┆ …           │
│ XLOC_020059 ┆ [0.0, 0.0, … 2.83778]         ┆ 1          ┆ 100         │
│ XLOC_020060 ┆ [0.0, 0.0, … 2.83778]         ┆ 1          ┆ 100         │
│ XLOC_022939 ┆ [3.95771, 0.0, … 0.0]         ┆ 1          ┆ 100         │
│ XLOC_027075 ┆ [0.0, 0.0, … 6.56804]         ┆ 1          ┆ 100         │
│ XLOC_027076 ┆ [0.0, 0.0, … 6.56804]         ┆ 1          ┆ 100         │
└─────────────┴───────────────────────────────┴────────────┴─────────────┘

In [46]:
genes_w_H3K27ac_df.filter(pl.col('H3K27ac_len') < 100).sort(['H3K27ac_wc'], descending=True)

shape: (0, 4)
┌─────────┬───────────┬────────────┬─────────────┐
│ gene_id ┆ H3K27ac   ┆ H3K27ac_wc ┆ H3K27ac_len │
│ ---     ┆ ---       ┆ ---        ┆ ---         │
│ str     ┆ list[f64] ┆ u32        ┆ u32         │
╞═════════╪═══════════╪════════════╪═════════════╡
└─────────┴───────────┴────────────┴─────────────┘

In [47]:
genes_w_H3K27me3_df.filter(pl.col('H3K27me3_wc') > 0).sort(['H3K27me3_wc'], descending=True)

shape: (8_278, 4)
┌─────────────┬───────────────────────────────┬─────────────┬──────────────┐
│ gene_id     ┆ H3K27me3                      ┆ H3K27me3_wc ┆ H3K27me3_len │
│ ---         ┆ ---                           ┆ ---         ┆ ---          │
│ str         ┆ list[f64]                     ┆ u32         ┆ u32          │
╞═════════════╪═══════════════════════════════╪═════════════╪══════════════╡
│ XLOC_000006 ┆ [5.37483, 5.37483, … 5.37483] ┆ 100         ┆ 100          │
│ XLOC_000007 ┆ [5.37483, 5.37483, … 5.37483] ┆ 100         ┆ 100          │
│ XLOC_001258 ┆ [5.37483, 5.37483, … 5.37483] ┆ 100         ┆ 100          │
│ XLOC_001259 ┆ [5.37483, 5.37483, … 5.37483] ┆ 100         ┆ 100          │
│ XLOC_001260 ┆ [5.37483, 5.37483, … 5.37483] ┆ 100         ┆ 100          │
│ …           ┆ …                             ┆ …           ┆ …            │
│ XLOC_023588 ┆ [3.04137, 0.0, … 0.0]         ┆ 1           ┆ 100          │
│ XLOC_025157 ┆ [2.72621, 0.0, … 0.0]         ┆ 1           ┆ 100          │
│ XLOC_025573 ┆ [0.0, 0.0, … 2.90024]         ┆ 1           ┆ 100          │
│ XLOC_025826 ┆ [0.0, 0.0, … 3.06001]         ┆ 1           ┆ 100          │
│ XLOC_028263 ┆ [0.0, 0.0, … 3.52397]         ┆ 1           ┆ 100          │
└─────────────┴───────────────────────────────┴─────────────┴──────────────┘

In [48]:
genes_w_H3K27me3_df.filter(pl.col('H3K27me3_len') < 100).sort(['H3K27me3_wc'], descending=True)

shape: (0, 4)
┌─────────┬───────────┬─────────────┬──────────────┐
│ gene_id ┆ H3K27me3  ┆ H3K27me3_wc ┆ H3K27me3_len │
│ ---     ┆ ---       ┆ ---         ┆ ---          │
│ str     ┆ list[f64] ┆ u32         ┆ u32          │
╞═════════╪═══════════╪═════════════╪══════════════╡
└─────────┴───────────┴─────────────┴──────────────┘

# Join all histones into single data frame

In [49]:
# Join all histone into single dataframe
genes_histone_df = genes_w_H3K9ac_df \
                    .join(genes_w_H3K9me3_df, on='gene_id') \
                    .join(genes_w_H3K4me3_df, on='gene_id') \
                    .join(genes_w_H3K27ac_df, on='gene_id') \
                    .join(genes_w_H3K27me3_df, on='gene_id')

In [50]:
genes_histone_df

shape: (22_154, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K9ac    ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27ac_l ┆ H3K27me3  ┆ H3K27me3_ ┆ H3K27me3 │
│ ---       ┆ ---       ┆ ---       ┆ n         ┆   ┆ en        ┆ ---       ┆ wc        ┆ _len     │
│ str       ┆ list[f64] ┆ u32       ┆ ---       ┆   ┆ ---       ┆ list[f64] ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ u32       ┆   ┆ u32       ┆           ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 01        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 03        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ [5.37483, ┆ 100       ┆ 100      │
│ 06        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 5.37483,  ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.37483]  ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ [5.37483, ┆ 100       ┆ 100      │
│ 07        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 5.37483,  ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5.37483]  ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 25        ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 08        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 09        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 12        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 14        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 17        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 100       ┆ [0.0,     ┆ 0         ┆ 100      │
│ 18        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆ 0.0]      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Join genes with the value and histone features

In [51]:
genes_values_df = genes_df.select(['gene_id', 'value_1', 'value_2'])
genes_values_df

shape: (22_154, 3)
┌─────────────┬───────────┬──────────┐
│ gene_id     ┆ value_1   ┆ value_2  │
│ ---         ┆ ---       ┆ ---      │
│ str         ┆ f64       ┆ f64      │
╞═════════════╪═══════════╪══════════╡
│ XLOC_000001 ┆ 0.0       ┆ 0.0      │
│ XLOC_000003 ┆ 0.0       ┆ 0.0      │
│ XLOC_000006 ┆ 0.0888452 ┆ 0.136965 │
│ XLOC_000007 ┆ 4.04743   ┆ 4.16567  │
│ XLOC_000008 ┆ 26.7934   ┆ 30.2747  │
│ …           ┆ …         ┆ …        │
│ XLOC_030009 ┆ 0.0       ┆ 0.0      │
│ XLOC_030012 ┆ 0.0       ┆ 0.0      │
│ XLOC_030014 ┆ 0.0       ┆ 0.0      │
│ XLOC_030017 ┆ 0.0       ┆ 0.0      │
│ XLOC_030018 ┆ 0.0       ┆ 0.0      │
└─────────────┴───────────┴──────────┘

In [52]:
genes_histone_values_df = genes_histone_df.join(
    genes_values_df,
    on = 'gene_id'
)

In [53]:
genes_histone_values_df

shape: (22_154, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K9ac    ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3_ ┆ H3K27me3_ ┆ value_1   ┆ value_2  │
│ ---       ┆ ---       ┆ ---       ┆ n         ┆   ┆ wc        ┆ len       ┆ ---       ┆ ---      │
│ str       ┆ list[f64] ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 01        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 03        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 0.0888452 ┆ 0.136965 │
│ 06        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 4.04743   ┆ 4.16567  │
│ 07        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 25        ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 26.7934   ┆ 30.2747  │
│ 08        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 09        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 12        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 14        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 17        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 18        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [54]:
# Save to parquet
genes_histone_values_df.write_parquet(os.path.join(DATASET_PATH, 'HepG2_exp_histones.parquet'))

In [55]:
test_df = pl.read_parquet(os.path.join(DATASET_PATH, 'HepG2_exp_histones.parquet'))
test_df

shape: (22_154, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K9ac    ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3_ ┆ H3K27me3_ ┆ value_1   ┆ value_2  │
│ ---       ┆ ---       ┆ ---       ┆ n         ┆   ┆ wc        ┆ len       ┆ ---       ┆ ---      │
│ str       ┆ list[f64] ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 01        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 03        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 0.0888452 ┆ 0.136965 │
│ 06        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 4.04743   ┆ 4.16567  │
│ 07        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 25        ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 26.7934   ┆ 30.2747  │
│ 08        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 09        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 12        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 14        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 17        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 18        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘