In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'
OUTPUT_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/output/'

In [3]:
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.6057    ┆ 69.8869   ┆ 0.6934    ┆ … ┆ 69.5996   ┆ 0.6909    ┆ 69.49     ┆ 0.6892   │
│ H3K9ac    ┆ 0.6132    ┆ 69.2628   ┆ 0.6894    ┆ … ┆ 68.8463   ┆ 0.6837    ┆ 69.32     ┆ 0.6889   │
│ H3K9me3   ┆ 0.7004    ┆ 58.1032   ┆ 0.5687    ┆ … ┆ 58.5621   ┆ 0.5742    ┆ 59.54     ┆ 0.583    │
│ H3K27ac   ┆ 0.6028    ┆ 70.2555   ┆ 0.6986    ┆ … ┆ 70.1083   ┆ 0.6956    ┆ 69.9      ┆ 0.6937   │
│ H3K27me3  ┆ 0.6839    ┆ 59.6183   ┆ 0.5833    ┆ … ┆ 60.0461   ┆ 0.5869    ┆ 60.12     ┆ 0.5844   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.5862    ┆ 70.6351   ┆ 0.7008    ┆ … ┆ 70.2557   ┆ 0.697     ┆ 70.94     ┆ 0.7052   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5868    ┆ 70.5876   ┆ 0.7008    ┆ … ┆ 70.294    ┆ 0.699     ┆ 69.88     ┆ 0.6955   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5866    ┆ 70.624    ┆ 0.7008    ┆ … ┆ 70.1946   ┆ 0.6971    ┆ 69.3      ┆ 0.6891   │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5876    ┆ 70.5765   ┆ 0.7003    ┆ … ┆ 70.2502   ┆ 0.6967    ┆ 70.61     ┆ 0.6978   │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5799    ┆ 70.9738   ┆ 0.7081    ┆ … ┆ 70.6105   ┆ 0.7028    ┆ 70.86     ┆ 0.7048   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the number of histones column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.6057    ┆ 69.8869   ┆ 0.6934    ┆ … ┆ 0.6909    ┆ 69.49     ┆ 0.6892   ┆ 1         │
│ H3K9ac    ┆ 0.6132    ┆ 69.2628   ┆ 0.6894    ┆ … ┆ 0.6837    ┆ 69.32     ┆ 0.6889   ┆ 1         │
│ H3K9me3   ┆ 0.7004    ┆ 58.1032   ┆ 0.5687    ┆ … ┆ 0.5742    ┆ 59.54     ┆ 0.583    ┆ 1         │
│ H3K27ac   ┆ 0.6028    ┆ 70.2555   ┆ 0.6986    ┆ … ┆ 0.6956    ┆ 69.9      ┆ 0.6937   ┆ 1         │
│ H3K27me3  ┆ 0.6839    ┆ 59.6183   ┆ 0.5833    ┆ … ┆ 0.5869    ┆ 60.12     ┆ 0.5844   ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.5862    ┆ 70.6351   ┆ 0.7008    ┆ … ┆ 0.697     ┆ 70.94     ┆ 0.7052   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5868    ┆ 70.5876   ┆ 0.7008    ┆ … ┆ 0.699     ┆ 69.88     ┆ 0.6955   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5866    ┆ 70.624    ┆ 0.7008    ┆ … ┆ 0.6971    ┆ 69.3      ┆ 0.6891   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5876    ┆ 70.5765   ┆ 0.7003    ┆ … ┆ 0.6967    ┆ 70.61     ┆ 0.6978   ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5799    ┆ 70.9738   ┆ 0.7081    ┆ … ┆ 0.7028    ┆ 70.86     ┆ 0.7048   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by histone_number (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5799    ┆ 70.9738   ┆ 0.7081    ┆ … ┆ 0.7028    ┆ 70.86     ┆ 0.7048   ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5868    ┆ 70.5876   ┆ 0.7008    ┆ … ┆ 0.699     ┆ 69.88     ┆ 0.6955   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5916    ┆ 70.5286   ┆ 0.7001    ┆ … ┆ 0.696     ┆ 70.14     ┆ 0.6973   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5862    ┆ 70.6351   ┆ 0.7008    ┆ … ┆ 0.697     ┆ 70.94     ┆ 0.7052   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5866    ┆ 70.624    ┆ 0.7008    ┆ … ┆ 0.6971    ┆ 69.3      ┆ 0.6891   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.6028    ┆ 70.2555   ┆ 0.6986    ┆ … ┆ 0.6956    ┆ 69.9      ┆ 0.6937   ┆ 1         │
│ H3K27me3  ┆ 0.6839    ┆ 59.6183   ┆ 0.5833    ┆ … ┆ 0.5869    ┆ 60.12     ┆ 0.5844   ┆ 1         │
│ H3K4me3   ┆ 0.6057    ┆ 69.8869   ┆ 0.6934    ┆ … ┆ 0.6909    ┆ 69.49     ┆ 0.6892   ┆ 1         │
│ H3K9ac    ┆ 0.6132    ┆ 69.2628   ┆ 0.6894    ┆ … ┆ 0.6837    ┆ 69.32     ┆ 0.6889   ┆ 1         │
│ H3K9me3   ┆ 0.7004    ┆ 58.1032   ┆ 0.5687    ┆ … ┆ 0.5742    ┆ 59.54     ┆ 0.583    ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5799    ┆ 70.9738   ┆ 0.7081    ┆ … ┆ 70.86     ┆ 0.7048   ┆ 5         ┆ 2         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5868    ┆ 70.5876   ┆ 0.7008    ┆ … ┆ 69.88     ┆ 0.6955   ┆ 4         ┆ 18        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5916    ┆ 70.5286   ┆ 0.7001    ┆ … ┆ 70.14     ┆ 0.6973   ┆ 4         ┆ 11        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5862    ┆ 70.6351   ┆ 0.7008    ┆ … ┆ 70.94     ┆ 0.7052   ┆ 4         ┆ 1         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5866    ┆ 70.624    ┆ 0.7008    ┆ … ┆ 69.3      ┆ 0.6891   ┆ 4         ┆ 26        │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.6028    ┆ 70.2555   ┆ 0.6986    ┆ … ┆ 69.9      ┆ 0.6937   ┆ 1         ┆ 17        │
│ H3K27me3  ┆ 0.6839    ┆ 59.6183   ┆ 0.5833    ┆ … ┆ 60.12     ┆ 0.5844   ┆ 1         ┆ 30        │
│ H3K4me3   ┆ 0.6057    ┆ 69.8869   ┆ 0.6934    ┆ … ┆ 69.49     ┆ 0.6892   ┆ 1         ┆ 24        │
│ H3K9ac    ┆ 0.6132    ┆ 69.2628   ┆ 0.6894    ┆ … ┆ 69.32     ┆ 0.6889   ┆ 1         ┆ 25        │
│ H3K9me3   ┆ 0.7004    ┆ 58.1032   ┆ 0.5687    ┆ … ┆ 59.54     ┆ 0.583    ┆ 1         ┆ 31        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save to CSV
pl_df.write_csv(os.path.join("HepG2 with DeepChrome preprocessing.csv"))