In [1]:
import polars as pl
from pybiomart import Server
import os
import numpy as np
import pandas as pd

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/dataset'

# Loading Data

## Define schema and load data

In [3]:
schema = pl.Schema({
    "Chromosome/scaffold name"  : pl.String(),
    "Gene start (bp)"           : pl.Int64(),
    "Gene end (bp)"             : pl.Int64(),
    "Strand"                    : pl.Int64(),
    "Gene name"                 : pl.String(),
    "Gene stable ID"            : pl.String(),
    "Gene type"                 : pl.String(),
    "tss"                       : pl.Int64(),
    "tss -2kb"                  : pl.Int64(),
    "tss +2kb"                  : pl.Int64(),
    "test_id"                   : pl.String(),
    "orig_gene_name"            : pl.String(),
    "locus"                     : pl.String(),
    "orig_start"                : pl.Int64(),
    "orig_end"                  : pl.Int64(),
})

In [4]:
ensembl_pl = pl.read_csv(os.path.join(WORKING_DIR, "dataset", "ensembl.csv"), schema=schema)

In [5]:
ensembl_pl

shape: (80_860, 15)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Chromosome ┆ Gene start ┆ Gene end   ┆ Strand ┆ … ┆ orig_gene ┆ locus     ┆ orig_star ┆ orig_end │
│ /scaffold  ┆ (bp)       ┆ (bp)       ┆ ---    ┆   ┆ _name     ┆ ---       ┆ t         ┆ ---      │
│ name       ┆ ---        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ str       ┆ ---       ┆ i64      │
│ ---        ┆ i64        ┆ i64        ┆        ┆   ┆ str       ┆           ┆ i64       ┆          │
│ str        ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1          ┆ 69091      ┆ 70008      ┆ 1      ┆ … ┆ OR4F5     ┆ chr1:6909 ┆ 69090     ┆ 70008    │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0-70008   ┆           ┆          │
│ 1          ┆ 317720     ┆ 453948     ┆ 1      ┆ … ┆ LOC100132 ┆ chr1:3238 ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 062       ┆ 91-328581 ┆           ┆          │
│ 1          ┆ 326096     ┆ 328112     ┆ 1      ┆ … ┆ LOC100132 ┆ chr1:3238 ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 062       ┆ 91-328581 ┆           ┆          │
│ 1          ┆ 317720     ┆ 453948     ┆ 1      ┆ … ┆ LOC100133 ┆ chr1:3238 ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 331       ┆ 91-328581 ┆           ┆          │
│ 1          ┆ 326096     ┆ 328112     ┆ 1      ┆ … ┆ LOC100133 ┆ chr1:3238 ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 331       ┆ 91-328581 ┆           ┆          │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1          ┆ 70671365   ┆ 70718735   ┆ 1      ┆ … ┆ SRSF11    ┆ chr1:7061 ┆ 70610388  ┆ 70717701 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0388-7071 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 7701      ┆           ┆          │
│ 1          ┆ 70684272   ┆ 70686706   ┆ -1     ┆ … ┆ SRSF11    ┆ chr1:7061 ┆ 70610388  ┆ 70717701 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0388-7071 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 7701      ┆           ┆          │
│ 1          ┆ 70726271   ┆ 70820417   ┆ -1     ┆ … ┆ HHLA3     ┆ chr1:7072 ┆ 70724684  ┆ 70834148 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4684-7083 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4148      ┆           ┆          │
│ 1          ┆ 70820488   ┆ 70851022   ┆ 1      ┆ … ┆ HHLA3     ┆ chr1:7072 ┆ 70724684  ┆ 70834148 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4684-7083 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4148      ┆           ┆          │
│ 1          ┆ 70825245   ┆ 70826120   ┆ -1     ┆ … ┆ HHLA3     ┆ chr1:7072 ┆ 70724684  ┆ 70834148 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4684-7083 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4148      ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Data Filtering

## Filter where gene name equals to original gene_name

In [ ]:
ensembl_match = ensembl_pl.filter(pl.col('Gene name') == pl.col('orig_gene_name'))
ensembl_match

In [ ]:
ensembl_match.write_csv(os.path.join(WORKING_DIR, "dataset", "ensembl_match.csv"))

## Gene with '-' which are not matched

In [ ]:
ensembl_without_name = ensembl_pl.unique(subset = ['locus', 'Gene name', 'test_id']).filter(pl.col('orig_gene_name') == '-')
ensembl_without_name

## All data without gene name checking

In [ ]:
ensembl_unique = ensembl_pl.unique(subset = ['locus', 'Gene name', 'test_id']).sort(['test_id']).select(pl.exclude(['orig_gene_name', 'orig_start', 'orig_end']))

In [ ]:
ensembl_unique

In [ ]:
ensembl_unique.write_csv(os.path.join(WORKING_DIR, "dataset", "ensembl_unique.csv"))

## Filter the data by gene type with 'protein_coding'

In [7]:
ensembl_protein_coding = ensembl_pl.filter(pl.col('Gene type') == 'protein_coding')
ensembl_protein_coding

shape: (40_655, 15)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Chromosome ┆ Gene start ┆ Gene end   ┆ Strand ┆ … ┆ orig_gene ┆ locus     ┆ orig_star ┆ orig_end │
│ /scaffold  ┆ (bp)       ┆ (bp)       ┆ ---    ┆   ┆ _name     ┆ ---       ┆ t         ┆ ---      │
│ name       ┆ ---        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ str       ┆ ---       ┆ i64      │
│ ---        ┆ i64        ┆ i64        ┆        ┆   ┆ str       ┆           ┆ i64       ┆          │
│ str        ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1          ┆ 69091      ┆ 70008      ┆ 1      ┆ … ┆ OR4F5     ┆ chr1:6909 ┆ 69090     ┆ 70008    │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0-70008   ┆           ┆          │
│ 1          ┆ 367640     ┆ 368634     ┆ 1      ┆ … ┆ OR4F29    ┆ chr1:3676 ┆ 367658    ┆ 368597   │
│            ┆            ┆            ┆        ┆   ┆           ┆ 58-368597 ┆           ┆          │
│ 1          ┆ 860260     ┆ 879955     ┆ 1      ┆ … ┆ SAMD11    ┆ chr1:8511 ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆           ┆ 35-917473 ┆           ┆          │
│ 1          ┆ 861264     ┆ 866445     ┆ -1     ┆ … ┆ SAMD11    ┆ chr1:8511 ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆           ┆ 35-917473 ┆           ┆          │
│ 1          ┆ 879584     ┆ 894689     ┆ -1     ┆ … ┆ SAMD11    ┆ chr1:8511 ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆           ┆ 35-917473 ┆           ┆          │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1          ┆ 70034081   ┆ 70617628   ┆ 1      ┆ … ┆ SRSF11    ┆ chr1:7061 ┆ 70610388  ┆ 70717701 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0388-7071 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 7701      ┆           ┆          │
│ 1          ┆ 70610488   ┆ 70671303   ┆ -1     ┆ … ┆ SRSF11    ┆ chr1:7061 ┆ 70610388  ┆ 70717701 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0388-7071 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 7701      ┆           ┆          │
│ 1          ┆ 70671365   ┆ 70718735   ┆ 1      ┆ … ┆ SRSF11    ┆ chr1:7061 ┆ 70610388  ┆ 70717701 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 0388-7071 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 7701      ┆           ┆          │
│ 1          ┆ 70726271   ┆ 70820417   ┆ -1     ┆ … ┆ HHLA3     ┆ chr1:7072 ┆ 70724684  ┆ 70834148 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4684-7083 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4148      ┆           ┆          │
│ 1          ┆ 70820488   ┆ 70851022   ┆ 1      ┆ … ┆ HHLA3     ┆ chr1:7072 ┆ 70724684  ┆ 70834148 │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4684-7083 ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ 4148      ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘