In [1]:
import polars as pl
from pybiomart import Server
import os
import numpy as np
import pandas as pd

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/dataset'

In [3]:
# Load the matrix without label
gene_w_histone = pl.read_parquet(os.path.join(WORKING_DIR, 'dataset', 'gene_w_histone.parquet'))

In [4]:
gene_w_histone

shape: (22_154, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K4me3   ┆ H3K4me3_c ┆ H3K9ac    ┆ … ┆ H3K27ac   ┆ H3K27ac_c ┆ H3K27me3  ┆ H3K27me3 │
│ ---       ┆ ---       ┆ ount      ┆ ---       ┆   ┆ ---       ┆ ount      ┆ ---       ┆ _count   │
│ str       ┆ list[f64] ┆ ---       ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ list[f64] ┆ ---      │
│           ┆           ┆ i64       ┆           ┆   ┆           ┆ i64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 01        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 03        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 06        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 07        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 6         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 2         ┆ [0.0,     ┆ 0        │
│ 08        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 09        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 12        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 14        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 17        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ 0        │
│ 18        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆ 0.0, …    ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆ 0.0]      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Load HepG2 expression dataset
hepg2_pl = pl.read_csv(os.path.join(DATASET_DIR, 'GSM3718064_HepG2_exp.txt'), separator="\t")

In [6]:
hepg2_pl

shape: (30_032, 14)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬─────────┬──────────┬───────────┐
│ test_id    ┆ gene_id    ┆ gene      ┆ locus     ┆ … ┆ test_stat ┆ p_value ┆ q_value  ┆ significa │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---      ┆ nt        │
│ str        ┆ str        ┆ str       ┆ str       ┆   ┆ f64       ┆ f64     ┆ f64      ┆ ---       │
│            ┆            ┆           ┆           ┆   ┆           ┆         ┆          ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪══════════╪═══════════╡
│ XLOC_00000 ┆ XLOC_00000 ┆ OR4F5     ┆ chr1:6909 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 1          ┆ 1          ┆           ┆ 0-70008   ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ LOC100132 ┆ chr1:3238 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 2          ┆ 2          ┆ 062,LOC10 ┆ 91-328581 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆ 0133331   ┆           ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ OR4F29    ┆ chr1:3676 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 3          ┆ 3          ┆           ┆ 58-368597 ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ LOC643837 ┆ chr1:7615 ┆ … ┆ 0.455074  ┆ 0.63585 ┆ 0.999565 ┆ no        │
│ 4          ┆ 4          ┆           ┆ 85-794889 ┆   ┆           ┆         ┆          ┆           │
│ XLOC_00000 ┆ XLOC_00000 ┆ -         ┆ chr1:8402 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 5          ┆ 5          ┆           ┆ 63-843900 ┆   ┆           ┆         ┆          ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …        ┆ …         │
│ XLOC_03002 ┆ XLOC_03002 ┆ -         ┆ chrY:1331 ┆ … ┆ 1.13793   ┆ 0.25685 ┆ 0.999565 ┆ no        │
│ 8          ┆ 8          ┆           ┆ 9431-1332 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 4829      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03002 ┆ XLOC_03002 ┆ -         ┆ chrY:1332 ┆ … ┆ 0.0       ┆ 1.0     ┆ 1.0      ┆ no        │
│ 9          ┆ 9          ┆           ┆ 5034-1332 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 6120      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:1333 ┆ … ┆ -1.86192  ┆ 0.1249  ┆ 0.999565 ┆ no        │
│ 0          ┆ 0          ┆           ┆ 1089-1333 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 2358      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:1505 ┆ … ┆ -2.11604  ┆ 0.04075 ┆ 0.999565 ┆ no        │
│ 1          ┆ 1          ┆           ┆ 3270-1505 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 3343      ┆   ┆           ┆         ┆          ┆           │
│ XLOC_03003 ┆ XLOC_03003 ┆ -         ┆ chrY:5900 ┆ … ┆ -0.291421 ┆ 0.7684  ┆ 0.999565 ┆ no        │
│ 2          ┆ 2          ┆           ┆ 1259-5900 ┆   ┆           ┆         ┆          ┆           │
│            ┆            ┆           ┆ 3893      ┆   ┆           ┆         ┆          ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴─────────┴──────────┴───────────┘

In [7]:
hepg2_pl = hepg2_pl.select(["gene_id", "value_1"])

In [8]:
hepg2_pl

shape: (30_032, 2)
┌─────────────┬───────────┐
│ gene_id     ┆ value_1   │
│ ---         ┆ ---       │
│ str         ┆ f64       │
╞═════════════╪═══════════╡
│ XLOC_000001 ┆ 0.0       │
│ XLOC_000002 ┆ 0.0473925 │
│ XLOC_000003 ┆ 0.0       │
│ XLOC_000004 ┆ 2.46857   │
│ XLOC_000005 ┆ 0.0       │
│ …           ┆ …         │
│ XLOC_030028 ┆ 0.337879  │
│ XLOC_030029 ┆ 0.396888  │
│ XLOC_030030 ┆ 0.477227  │
│ XLOC_030031 ┆ 123998.0  │
│ XLOC_030032 ┆ 0.456876  │
└─────────────┴───────────┘

In [9]:
# Join with histone dataset
gene_joined = gene_w_histone.join(hepg2_pl, on='gene_id')

In [10]:
gene_joined

shape: (22_154, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K4me3   ┆ H3K4me3_c ┆ H3K9ac    ┆ … ┆ H3K27ac_c ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1  │
│ ---       ┆ ---       ┆ ount      ┆ ---       ┆   ┆ ount      ┆ ---       ┆ count     ┆ ---      │
│ str       ┆ list[f64] ┆ ---       ┆ list[f64] ┆   ┆ ---       ┆ list[f64] ┆ ---       ┆ f64      │
│           ┆           ┆ i64       ┆           ┆   ┆ i64       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 01        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 03        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.088845 │
│ 06        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆ 2        │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 4.04743  │
│ 07        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 6         ┆ [0.0,     ┆ … ┆ 2         ┆ [0.0,     ┆ 0         ┆ 26.7934  │
│ 08        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 09        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 12        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 14        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 17        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ [0.0,     ┆ … ┆ 0         ┆ [0.0,     ┆ 0         ┆ 0.0      │
│ 18        ┆ 0.0, …    ┆           ┆ 0.0, …    ┆   ┆           ┆ 0.0, …    ┆           ┆          │
│           ┆ 0.0]      ┆           ┆ 0.0]      ┆   ┆           ┆ 0.0]      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# Convert into labels using quantile value
# Define the quartile boundaries
quartiles = [0.25, 0.5, 0.75]

In [13]:
# Create the quartile labels
gene_w_label = gene_joined.with_columns([
    pl.col('value_1')
    .qcut(quartiles, labels=['0', '1', '2', '3'])
    .alias('label')
])

In [14]:
gene_w_label

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ cat   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 1     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 2     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 3     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [15]:
gene_w_label = gene_w_label.with_columns(pl.col('label').cast(pl.Int64))

In [16]:
gene_w_label

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i64   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 1     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 2     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 3     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [17]:
# Check the label distribution
gene_w_label.group_by("label").len()

shape: (4, 2)
┌───────┬──────┐
│ label ┆ len  │
│ ---   ┆ ---  │
│ i64   ┆ u32  │
╞═══════╪══════╡
│ 0     ┆ 5539 │
│ 1     ┆ 5538 │
│ 3     ┆ 5539 │
│ 2     ┆ 5538 │
└───────┴──────┘

In [18]:
# Save to parquet
gene_w_label.write_parquet(os.path.join(WORKING_DIR, 'dataset', f'gene_w_qlabel.parquet'))

In [19]:
test_pl = pl.read_parquet(os.path.join(WORKING_DIR, 'dataset', f'gene_w_qlabel.parquet'))

In [20]:
test_pl

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i64   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 1     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 2     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 3     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘