In [1]:
import polars as pl
import os
import numpy as np
import pandas as pd
import random

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc, precision_recall_fscore_support, confusion_matrix, classification_report

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/10_Permutation Test Ranking/E066/notebook/E066'
DATASET_DIR = "/group/pmc021/amunif/epi-thesis/workflow/07_deepchrome/dataset/E066"

In [3]:
# Load the dataset
E066_w_histone_pl = pl.read_parquet(os.path.join(DATASET_DIR, 'E066_w_histone_pl.parquet'))

In [7]:
E066_w_histone_pl.head()

shape: (5, 19)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬───────┬────────────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_wc ┆ H3K4me3_le ┆ … ┆ H3K27me3_l ┆ E066   ┆ label ┆ all_histon │
│ ---        ┆ ---        ┆ ---        ┆ n          ┆   ┆ en         ┆ ---    ┆ ---   ┆ e          │
│ str        ┆ list[f64]  ┆ u32        ┆ ---        ┆   ┆ ---        ┆ f64    ┆ i64   ┆ ---        │
│            ┆            ┆            ┆ u32        ┆   ┆ u32        ┆        ┆       ┆ list[list[ │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ f64]]      │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════╪════════════╡
│ ENSG000000 ┆ [0.0,      ┆ 19         ┆ 100        ┆ … ┆ 100        ┆ 73.205 ┆ 1     ┆ [[0.0,     │
│ 00003      ┆ 4.19024, … ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆ 0.0]       ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 4.19…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.191  ┆ 0     ┆ [[0.0,     │
│ 00005      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 36         ┆ 100        ┆ … ┆ 100        ┆ 52.609 ┆ 1     ┆ [[0.0,     │
│ 00419      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 35         ┆ 100        ┆ … ┆ 100        ┆ 4.733  ┆ 1     ┆ [[0.0,     │
│ 00457      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.942  ┆ 0     ┆ [[0.0,     │
│ 00460      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴───────┴────────────┘

In [8]:
# Add index to dataframe
E066_w_histone_pl = E066_w_histone_pl.with_row_index("index")
E066_w_histone_pl

shape: (19_645, 20)
┌───────┬──────────────┬─────────────┬────────────┬───┬─────────────┬────────┬───────┬─────────────┐
│ index ┆ gene_id      ┆ H3K4me3     ┆ H3K4me3_wc ┆ … ┆ H3K27me3_le ┆ E066   ┆ label ┆ all_histone │
│ ---   ┆ ---          ┆ ---         ┆ ---        ┆   ┆ n           ┆ ---    ┆ ---   ┆ ---         │
│ u32   ┆ str          ┆ list[f64]   ┆ u32        ┆   ┆ ---         ┆ f64    ┆ i64   ┆ list[list[f │
│       ┆              ┆             ┆            ┆   ┆ u32         ┆        ┆       ┆ 64]]        │
╞═══════╪══════════════╪═════════════╪════════════╪═══╪═════════════╪════════╪═══════╪═════════════╡
│ 0     ┆ ENSG00000000 ┆ [0.0,       ┆ 19         ┆ … ┆ 100         ┆ 73.205 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 003          ┆ 4.19024, …  ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆ 0.0]        ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 4.19… │
│ 1     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.191  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 005          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 2     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 36         ┆ … ┆ 100         ┆ 52.609 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 419          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 3     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 35         ┆ … ┆ 100         ┆ 4.733  ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 457          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 4     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.942  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 460          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ …     ┆ …            ┆ …           ┆ …          ┆ … ┆ …           ┆ …      ┆ …     ┆ …           │
│ 19640 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.212  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 658          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19641 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 664          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19642 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.071  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 680          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19643 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 18         ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0,      │
│       ┆ 717          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ 3.18223, …  │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ 0.0], [0.0, │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ …           │
│ 19644 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 752          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
└───────┴──────────────┴─────────────┴────────────┴───┴─────────────┴────────┴───────┴─────────────┘

In [11]:
# Convert to numpy array
all_features_np = E066_w_histone_pl.to_numpy()
print(all_features_np.shape)

(19645, 20)

In [12]:
# Split train, test, validation by index
data_indices = np.arange(len(all_features_np))
print(data_indices)

[    0     1     2 ... 19642 19643 19644]

In [13]:
# First split: 80% train, 20% temporary (for test + validation)
train_idx, temp_idx = train_test_split(
    data_indices, 
    test_size=0.2, 
    random_state=42  # For reproducibility
)

In [14]:
# Second split: Split temp_idx into 50% test and 50% validation
val_idx, test_idx = train_test_split(
    temp_idx, 
    test_size=0.5, 
    random_state=42  # Same random_state for consistency
)

In [15]:
print(train_idx)
print(val_idx)
print(test_idx)

[ 1795  9363 14610 ...  5390   860 15795]
[11446 15912 16343 ...   251 15521   668]
[18530 11682  3062 ... 17579 15568 17851]

In [16]:
# Save train, val, and test into parquet file
train_idx_df = pd.DataFrame(train_idx, columns=['values'])
train_idx_df.to_parquet(os.path.join(DATASET_DIR, 'train_idx.parquet'))

val_idx_df = pd.DataFrame(val_idx, columns=['values'])
val_idx_df.to_parquet(os.path.join(DATASET_DIR, 'val_idx.parquet'))

test_idx_df = pd.DataFrame(test_idx, columns=['values'])
val_idx_df.to_parquet(os.path.join(DATASET_DIR, 'test_idx.parquet'))

In [17]:
# Test re-reading the files
train_idx_df = pd.read_parquet(os.path.join(DATASET_DIR, 'train_idx.parquet'))
len(train_idx_df["values"].to_list())

15716

In [18]:
val_idx_df = pd.read_parquet(os.path.join(DATASET_DIR, 'val_idx.parquet'))
len(val_idx_df["values"].to_list())

1964

In [19]:
test_idx_df = pd.read_parquet(os.path.join(DATASET_DIR, 'test_idx.parquet'))
len(test_idx_df["values"].to_list())

1964