In [1]:
import sys

sys.path.insert(0, '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib')
print(sys.path)

['/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib', '/group/pmc021/amunif/epi-thesis/workflow/10_Permutation_Test_Ranking/notebook', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python312.zip', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/lib-dynload', '', '/home/amunif/.local/lib/python3.12/site-packages', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/site-packages']

In [2]:
import os
import random
from datetime import datetime

import pandas as pd
import polars as pl
import numpy as np

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
from torch.utils.data import Dataset, DataLoader, TensorDataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc, precision_recall_fscore_support, confusion_matrix, classification_report
from sklearn.metrics import ConfusionMatrixDisplay

import BinaryClassifier as BC
import HepG2Dataset as HG2D
import my_util

In [4]:
DATASET_DIR = "/group/pmc021/amunif/epi-thesis/workflow/07_deepchrome/dataset/E066"
markers = ['H3K4me3', 'H3K4me1','H3K36me3',  'H3K9me3', 'H3K27me3']

In [5]:
device = my_util.get_device()

Using device: cuda
Current CUDA device: 0
CUDA device name: Tesla P100-SXM2-16GB

In [6]:
# Custom dataset for E066

class E066Dataset(Dataset):
    def __init__(self, total_samples, features, indexes):
        self.total_samples = total_samples
        self.features = features
        self.indexes = indexes

    def __len__(self):
        return self.total_samples

    def __getitem__(self, idx):
        r1 = random.choice(self.indexes)
        r2 = random.choice(self.indexes)
        
        feature_1 = self.features[r1, 2]
        feature_2 = self.features[r2, 2]
        feature = np.concatenate((feature_1, feature_2), axis=0)
        
        val_1 = self.features[r1, 3]
        val_2 = self.features[r2, 3]

        y = 1 if val_1 > val_2 else 0
        
        return feature, y

In [9]:
# Declare  variables, working directory and dataset directory
MODE = 'E066'
NUM_EPOCHS = 100
START_EPOCH = 0
NUM_ITEMS = 1000
BATCH_SIZE = 64
DROPOUT_RATE = 0.2

L1_lambda = 0.005
L2_lambda = 0.001
# L1_lambda = 0.0
# L2_lambda = 0.0

WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/10_Permutation_Test_Ranking'
# DATASET_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/dataset'

MODEL_MODE = "dol1l2" # regular (reg), dropout (do), dropout + l1l2 (dol1l2)
PREFIX = f"{MODEL_MODE}-{DROPOUT_RATE}"
SUFFIX = f"{NUM_ITEMS}-{NUM_EPOCHS}-{BATCH_SIZE}-{L1_lambda}-{L2_lambda}"

CHECKPOINT_NAME = os.path.join(WORKING_DIR, 'output', MODE, "model", f'{PREFIX}-checkpoint-{SUFFIX}.pt')

TEST_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'test', f"{PREFIX}-test-results-{SUFFIX}.txt")
TRAINING_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'train', f"{PREFIX}-train-validation-metrics-{SUFFIX}.csv")
TEST_RESULT_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'test', f"{PREFIX}-test-metrics-{SUFFIX}.csv")
ROC_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'img', 'roc', f"{PREFIX}-roc-{SUFFIX}.png")
IMAGE_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'img', 'train', f"{PREFIX}-ranking-{SUFFIX}.png")
CM_FILE = os.path.join(WORKING_DIR, 'output', MODE, 'img', 'confusion_matrix', f"{PREFIX}-cm-{SUFFIX}.png")

print(CHECKPOINT_NAME)

/group/pmc021/amunif/epi-thesis/workflow/10_Permutation_Test_Ranking/output/E066/model/dol1l2-0.2-checkpoint-1000-100-64-0.005-0.001.pt

In [10]:
# Load the dataset
E066_w_histone_pl = pl.read_parquet(os.path.join(DATASET_PATH, 'E066_w_histone_pl.parquet'))

In [11]:
E066_w_histone_pl

shape: (19_645, 19)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬───────┬────────────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_wc ┆ H3K4me3_le ┆ … ┆ H3K27me3_l ┆ E066   ┆ label ┆ all_histon │
│ ---        ┆ ---        ┆ ---        ┆ n          ┆   ┆ en         ┆ ---    ┆ ---   ┆ e          │
│ str        ┆ list[f64]  ┆ u32        ┆ ---        ┆   ┆ ---        ┆ f64    ┆ i64   ┆ ---        │
│            ┆            ┆            ┆ u32        ┆   ┆ u32        ┆        ┆       ┆ list[list[ │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ f64]]      │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════╪════════════╡
│ ENSG000000 ┆ [0.0,      ┆ 19         ┆ 100        ┆ … ┆ 100        ┆ 73.205 ┆ 1     ┆ [[0.0,     │
│ 00003      ┆ 4.19024, … ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆ 0.0]       ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 4.19…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.191  ┆ 0     ┆ [[0.0,     │
│ 00005      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 36         ┆ 100        ┆ … ┆ 100        ┆ 52.609 ┆ 1     ┆ [[0.0,     │
│ 00419      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 35         ┆ 100        ┆ … ┆ 100        ┆ 4.733  ┆ 1     ┆ [[0.0,     │
│ 00457      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.942  ┆ 0     ┆ [[0.0,     │
│ 00460      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …     ┆ …          │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.212  ┆ 0     ┆ [[0.0,     │
│ 59658      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.0    ┆ 0     ┆ [[0.0,     │
│ 59664      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.071  ┆ 0     ┆ [[0.0,     │
│ 59680      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 18         ┆ 100        ┆ … ┆ 100        ┆ 0.0    ┆ 0     ┆ [[0.0,     │
│ 59717      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 3.18223, … │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0, …    │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0          ┆ 100        ┆ … ┆ 100        ┆ 0.0    ┆ 0     ┆ [[0.0,     │
│ 59752      ┆ … 0.0]     ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0, …     │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0],      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ [0.0,      │
│            ┆            ┆            ┆            ┆   ┆            ┆        ┆       ┆ 0.0,…      │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴───────┴────────────┘

In [8]:
# Load the permutation list
perm_pl = pl.read_parquet(os.path.join(DATASET_PATH, 'permutation.parquet'))
perm_lst = perm_pl['markers_perm'].to_list()

In [12]:
# Add index to dataframe
E066_w_histone_pl = E066_w_histone_pl.with_row_index("index")
E066_w_histone_pl

shape: (19_645, 20)
┌───────┬──────────────┬─────────────┬────────────┬───┬─────────────┬────────┬───────┬─────────────┐
│ index ┆ gene_id      ┆ H3K4me3     ┆ H3K4me3_wc ┆ … ┆ H3K27me3_le ┆ E066   ┆ label ┆ all_histone │
│ ---   ┆ ---          ┆ ---         ┆ ---        ┆   ┆ n           ┆ ---    ┆ ---   ┆ ---         │
│ u32   ┆ str          ┆ list[f64]   ┆ u32        ┆   ┆ ---         ┆ f64    ┆ i64   ┆ list[list[f │
│       ┆              ┆             ┆            ┆   ┆ u32         ┆        ┆       ┆ 64]]        │
╞═══════╪══════════════╪═════════════╪════════════╪═══╪═════════════╪════════╪═══════╪═════════════╡
│ 0     ┆ ENSG00000000 ┆ [0.0,       ┆ 19         ┆ … ┆ 100         ┆ 73.205 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 003          ┆ 4.19024, …  ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆ 0.0]        ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 4.19… │
│ 1     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.191  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 005          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 2     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 36         ┆ … ┆ 100         ┆ 52.609 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 419          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 3     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 35         ┆ … ┆ 100         ┆ 4.733  ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 457          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 4     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.942  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 460          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ …     ┆ …            ┆ …           ┆ …          ┆ … ┆ …           ┆ …      ┆ …     ┆ …           │
│ 19640 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.212  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 658          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19641 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 664          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19642 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.071  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 680          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19643 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 18         ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0,      │
│       ┆ 717          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ 3.18223, …  │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ 0.0], [0.0, │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ …           │
│ 19644 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 752          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
└───────┴──────────────┴─────────────┴────────────┴───┴─────────────┴────────┴───────┴─────────────┘

In [15]:
# Load the permutation list
perm_pl = pl.read_parquet(os.path.join(DATASET_PATH, 'permutation.parquet'))
perm_lst = perm_pl['markers_perm'].to_list()