# Import the required libraries

In [9]:
import os

import pandas as pd
import polars as pl
import itertools
import numpy as np

import pyarrow as pa
import pyarrow.parquet as pq

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc, precision_recall_fscore_support, confusion_matrix, classification_report

In [10]:
# Declare the working directory and dataset directory
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/dataset'

In [11]:
def get_device():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    if device.type == "cuda":
        print(f"Current CUDA device: {torch.cuda.current_device()}")
        print(f"CUDA device name: {torch.cuda.get_device_name(0)}")

    return device

In [12]:
device = get_device()

Using device: cuda
Current CUDA device: 0
CUDA device name: Tesla P100-SXM2-16GB

# Loading Data and Preprocessing

In [13]:
# Load dataset
gene_pl = pl.read_parquet(os.path.join(DATASET_DIR, 'gene_w_label_value_1.parquet'))
gene_pl

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i32   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 0     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 1     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 1     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [14]:
# Combine all histones into single features
marker_list = ['H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3']

gene_features = gene_pl.with_columns(
    pl.concat_list(marker_list).alias("combined_features")
)

gene_features

shape: (22_154, 14)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────┬───────────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3_ ┆ value_1   ┆ label ┆ combined_ │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ count     ┆ ---       ┆ ---   ┆ features  │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ ---       ┆ f64       ┆ i32   ┆ ---       │
│            ┆            ┆ i64        ┆           ┆   ┆ i64       ┆           ┆       ┆ list[f64] │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════╪═══════════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0888452 ┆ 0     ┆ [0.0,     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 4.04743   ┆ 1     ┆ [0.0,     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ 0         ┆ 26.7934   ┆ 1     ┆ [0.0,     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …     ┆ …         │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ 0         ┆ 0.0       ┆ 0     ┆ [0.0,     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆           ┆           ┆       ┆ 0.0, …    │
│            ┆            ┆            ┆ 0.0]      ┆   ┆           ┆           ┆       ┆ 0.0]      │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────┴───────────┘

In [16]:
# Generate the dataframe index
gene_features = gene_features.with_row_index("index")
gene_features

shape: (22_154, 15)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬───────────┬───────┬────────────┐
│ index ┆ gene_id     ┆ H3K4me3     ┆ H3K4me3_co ┆ … ┆ H3K27me3_c ┆ value_1   ┆ label ┆ combined_f │
│ ---   ┆ ---         ┆ ---         ┆ unt        ┆   ┆ ount       ┆ ---       ┆ ---   ┆ eatures    │
│ u32   ┆ str         ┆ list[f64]   ┆ ---        ┆   ┆ ---        ┆ f64       ┆ i32   ┆ ---        │
│       ┆             ┆             ┆ i64        ┆   ┆ i64        ┆           ┆       ┆ list[f64]  │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪═══════════╪═══════╪════════════╡
│ 0     ┆ XLOC_000001 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 1     ┆ XLOC_000003 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 2     ┆ XLOC_000006 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0888452 ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 3     ┆ XLOC_000007 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 4.04743   ┆ 1     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 4     ┆ XLOC_000008 ┆ [0.0, 0.0,  ┆ 6          ┆ … ┆ 0          ┆ 26.7934   ┆ 1     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …     ┆ …          │
│ 22149 ┆ XLOC_030009 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22150 ┆ XLOC_030012 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22151 ┆ XLOC_030014 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22152 ┆ XLOC_030017 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22153 ┆ XLOC_030018 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴───────────┴───────┴────────────┘

In [17]:
# Select only the index, gene_id and the value_1
gene_id_val = gene_features.select(["index", "gene_id", "value_1"])
gene_id_val

shape: (22_154, 3)
┌───────┬─────────────┬───────────┐
│ index ┆ gene_id     ┆ value_1   │
│ ---   ┆ ---         ┆ ---       │
│ u32   ┆ str         ┆ f64       │
╞═══════╪═════════════╪═══════════╡
│ 0     ┆ XLOC_000001 ┆ 0.0       │
│ 1     ┆ XLOC_000003 ┆ 0.0       │
│ 2     ┆ XLOC_000006 ┆ 0.0888452 │
│ 3     ┆ XLOC_000007 ┆ 4.04743   │
│ 4     ┆ XLOC_000008 ┆ 26.7934   │
│ …     ┆ …           ┆ …         │
│ 22149 ┆ XLOC_030009 ┆ 0.0       │
│ 22150 ┆ XLOC_030012 ┆ 0.0       │
│ 22151 ┆ XLOC_030014 ┆ 0.0       │
│ 22152 ┆ XLOC_030017 ┆ 0.0       │
│ 22153 ┆ XLOC_030018 ┆ 0.0       │
└───────┴─────────────┴───────────┘

In [18]:
# Doing the permutation using cross join
permuted_df = gene_id_val.join(gene_id_val, how="cross")

In [19]:
# Create the label
permuted_w_label_df = permuted_df.with_columns(
    pl.when(pl.col("value_1") > pl.col("value_1_right")).then(1)
      .otherwise(0)
      .alias("label")
)

In [20]:
# Check the label distribution
permuted_w_label_df.group_by("label").len()

shape: (2, 2)
┌───────┬───────────┐
│ label ┆ len       │
│ ---   ┆ ---       │
│ i32   ┆ u32       │
╞═══════╪═══════════╡
│ 0     ┆ 258413475 │
│ 1     ┆ 232386241 │
└───────┴───────────┘

In [21]:
# Check the label distribution
permuted_w_label_df[:1_000_000].group_by("label").len()

shape: (2, 2)
┌───────┬────────┐
│ label ┆ len    │
│ ---   ┆ ---    │
│ i32   ┆ u32    │
╞═══════╪════════╡
│ 1     ┆ 494087 │
│ 0     ┆ 505913 │
└───────┴────────┘

In [22]:
# Prepare the X and y
X_df = permuted_w_label_df.select(['index', 'index_right'])
y_df = permuted_w_label_df.select(['label'])

In [23]:
X_df

shape: (490_799_716, 2)
┌───────┬─────────────┐
│ index ┆ index_right │
│ ---   ┆ ---         │
│ u32   ┆ u32         │
╞═══════╪═════════════╡
│ 0     ┆ 0           │
│ 0     ┆ 1           │
│ 0     ┆ 2           │
│ 0     ┆ 3           │
│ 0     ┆ 4           │
│ …     ┆ …           │
│ 22153 ┆ 22149       │
│ 22153 ┆ 22150       │
│ 22153 ┆ 22151       │
│ 22153 ┆ 22152       │
│ 22153 ┆ 22153       │
└───────┴─────────────┘

In [24]:
y_df

shape: (490_799_716, 1)
┌───────┐
│ label │
│ ---   │
│ i32   │
╞═══════╡
│ 0     │
│ 0     │
│ 0     │
│ 0     │
│ 0     │
│ …     │
│ 0     │
│ 0     │
│ 0     │
│ 0     │
│ 0     │
└───────┘

In [25]:
# Select gene_id and its features
gene_id_features_df = gene_features.select(["index", "gene_id", "combined_features"])
gene_id_features_df

shape: (22_154, 3)
┌───────┬─────────────┬───────────────────┐
│ index ┆ gene_id     ┆ combined_features │
│ ---   ┆ ---         ┆ ---               │
│ u32   ┆ str         ┆ list[f64]         │
╞═══════╪═════════════╪═══════════════════╡
│ 0     ┆ XLOC_000001 ┆ [0.0, 0.0, … 0.0] │
│ 1     ┆ XLOC_000003 ┆ [0.0, 0.0, … 0.0] │
│ 2     ┆ XLOC_000006 ┆ [0.0, 0.0, … 0.0] │
│ 3     ┆ XLOC_000007 ┆ [0.0, 0.0, … 0.0] │
│ 4     ┆ XLOC_000008 ┆ [0.0, 0.0, … 0.0] │
│ …     ┆ …           ┆ …                 │
│ 22149 ┆ XLOC_030009 ┆ [0.0, 0.0, … 0.0] │
│ 22150 ┆ XLOC_030012 ┆ [0.0, 0.0, … 0.0] │
│ 22151 ┆ XLOC_030014 ┆ [0.0, 0.0, … 0.0] │
│ 22152 ┆ XLOC_030017 ┆ [0.0, 0.0, … 0.0] │
│ 22153 ┆ XLOC_030018 ┆ [0.0, 0.0, … 0.0] │
└───────┴─────────────┴───────────────────┘

In [26]:
# Save to parquet
X_df.write_parquet(os.path.join(DATASET_DIR, 'X.parquet'))
y_df.write_parquet(os.path.join(DATASET_DIR, 'y.parquet'))
gene_id_features_df.write_parquet(os.path.join(DATASET_DIR, 'gene_id_features.parquet'))