In [15]:
import os

import pandas as pd
import polars as pl
import itertools
import numpy as np

import pyarrow as pa
import pyarrow.parquet as pq

import matplotlib.pyplot as plt

from sklearn.random_projection import GaussianRandomProjection

import torch

In [16]:
# Declare the working directory and dataset directory
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/dataset'

In [17]:
def get_device():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    if device.type == "cuda":
        print(f"Current CUDA device: {torch.cuda.current_device()}")
        print(f"CUDA device name: {torch.cuda.get_device_name(0)}")

    return device

In [18]:
device = get_device()

Using device: cuda
Current CUDA device: 0
CUDA device name: Tesla P100-SXM2-16GB

In [19]:
def reduce_array_columns(df, columns=None, target_dim=20, random_state=42):
    # If no columns specified, use all columns
    if columns is None:
        columns = df.columns
    
    # Initialize random projector
    transformer = GaussianRandomProjection(n_components=target_dim, random_state=random_state)
    
    # Create expressions for all columns to be reduced
    expressions = [
        pl.col(col).map_elements(
            lambda x: transformer.fit_transform(
                np.array(x).reshape(1, -1)
            ).ravel().tolist(),
            return_dtype=pl.List(pl.Float64)
        ).alias(f"{col}_reduced")
        for col in columns
    ]
    
    return df.with_columns(expressions)

In [20]:
# Load dataset
gene_pl = pl.read_parquet(os.path.join(DATASET_DIR, 'gene_w_label_value_1.parquet'))
gene_pl

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i32   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 0     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 1     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 1     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [21]:
# Generate the dataframe index
gene_pl = gene_pl.with_row_index("index")
gene_pl

shape: (22_154, 14)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ index ┆ gene_id     ┆ H3K4me3     ┆ H3K4me3_co ┆ … ┆ H3K27me3   ┆ H3K27me3_c ┆ value_1   ┆ label │
│ ---   ┆ ---         ┆ ---         ┆ unt        ┆   ┆ ---        ┆ ount       ┆ ---       ┆ ---   │
│ u32   ┆ str         ┆ list[f64]   ┆ ---        ┆   ┆ list[f64]  ┆ ---        ┆ f64       ┆ i32   │
│       ┆             ┆             ┆ i64        ┆   ┆            ┆ i64        ┆           ┆       │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ 0     ┆ XLOC_000001 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 1     ┆ XLOC_000003 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 2     ┆ XLOC_000006 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0888452 ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 3     ┆ XLOC_000007 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 4.04743   ┆ 1     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 4     ┆ XLOC_000008 ┆ [0.0, 0.0,  ┆ 6          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 26.7934   ┆ 1     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …     │
│ 22149 ┆ XLOC_030009 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 22150 ┆ XLOC_030012 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 22151 ┆ XLOC_030014 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 22152 ┆ XLOC_030017 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
│ 22153 ┆ XLOC_030018 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ [0.0, 0.0, ┆ 0          ┆ 0.0       ┆ 0     │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆ … 0.0]     ┆            ┆           ┆       │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

In [22]:
# Combine all histones into single features
marker_list = ['H3K4me3', 'H3K9ac', 'H3K9me3', 'H3K27ac', 'H3K27me3']

gene_features = gene_pl.with_columns(
    pl.concat_list(marker_list).alias("all_features")
)

gene_features

shape: (22_154, 15)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬───────────┬───────┬────────────┐
│ index ┆ gene_id     ┆ H3K4me3     ┆ H3K4me3_co ┆ … ┆ H3K27me3_c ┆ value_1   ┆ label ┆ all_featur │
│ ---   ┆ ---         ┆ ---         ┆ unt        ┆   ┆ ount       ┆ ---       ┆ ---   ┆ es         │
│ u32   ┆ str         ┆ list[f64]   ┆ ---        ┆   ┆ ---        ┆ f64       ┆ i32   ┆ ---        │
│       ┆             ┆             ┆ i64        ┆   ┆ i64        ┆           ┆       ┆ list[f64]  │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪═══════════╪═══════╪════════════╡
│ 0     ┆ XLOC_000001 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 1     ┆ XLOC_000003 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 2     ┆ XLOC_000006 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0888452 ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 3     ┆ XLOC_000007 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 4.04743   ┆ 1     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 4     ┆ XLOC_000008 ┆ [0.0, 0.0,  ┆ 6          ┆ … ┆ 0          ┆ 26.7934   ┆ 1     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …     ┆ …          │
│ 22149 ┆ XLOC_030009 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22150 ┆ XLOC_030012 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22151 ┆ XLOC_030014 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22152 ┆ XLOC_030017 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
│ 22153 ┆ XLOC_030018 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ [0.0, 0.0, │
│       ┆             ┆ … 0.0]      ┆            ┆   ┆            ┆           ┆       ┆ … 0.0]     │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴───────────┴───────┴────────────┘

In [26]:
print(len(gene_features["H3K9me3"][0]))

4000

In [27]:
# Do the reduce
gene_features_reduced = reduce_array_columns(gene_features, marker_list, target_dim=20)
gene_features_reduced

shape: (22_154, 20)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ … ┆ H3K9ac_re ┆ H3K9me3_r ┆ H3K27ac_r ┆ H3K27me3_ │
│ ---   ┆ ---        ┆ ---        ┆ unt        ┆   ┆ duced     ┆ educed    ┆ educed    ┆ reduced   │
│ u32   ┆ str        ┆ list[f64]  ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆            ┆ i64        ┆   ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64] │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 1          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 1     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 3          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 2     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 6          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 3     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 7          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 4     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ … ┆ [2.998644 ┆ [0.0,     ┆ [0.837573 ┆ [0.0,     │
│       ┆ 8          ┆ … 0.0]     ┆            ┆   ┆ , -3.2378 ┆ 0.0, …    ┆ , -3.4712 ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 55, …     ┆ 0.0]      ┆ 08, …     ┆ 0.0]      │
│       ┆            ┆            ┆            ┆   ┆ -2.795…   ┆           ┆ -1.538…   ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 22149 ┆ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 9          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22150 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 2          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22151 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 4          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22152 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 7          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22153 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 8          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
print(len(gene_features_reduced["H3K27ac_reduced"][0]))

20

In [29]:
# Combine all reduced histones into single features
marker_list = ['H3K4me3_reduced', 'H3K9ac_reduced', 'H3K9me3_reduced', 'H3K27ac_reduced', 'H3K27me3_reduced']

gene_features_reduced = gene_features_reduced.with_columns(
    pl.concat_list(marker_list).alias("reduced_features")
)

gene_features_reduced

shape: (22_154, 21)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ … ┆ H3K9me3_r ┆ H3K27ac_r ┆ H3K27me3_ ┆ reduced_f │
│ ---   ┆ ---        ┆ ---        ┆ unt        ┆   ┆ educed    ┆ educed    ┆ reduced   ┆ eatures   │
│ u32   ┆ str        ┆ list[f64]  ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆            ┆ i64        ┆   ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64] │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 1          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 1     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 3          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 2     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 6          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 3     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 7          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 4     ┆ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ … ┆ [0.0,     ┆ [0.837573 ┆ [0.0,     ┆ [5.717444 │
│       ┆ 8          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ , -3.4712 ┆ 0.0, …    ┆ , -11.321 │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 08, …     ┆ 0.0]      ┆ 019, …    │
│       ┆            ┆            ┆            ┆   ┆           ┆ -1.538…   ┆           ┆ 0.0]      │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 22149 ┆ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 9          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22150 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 2          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22151 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 4          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22152 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 7          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
│ 22153 ┆ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ … ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     ┆ [0.0,     │
│       ┆ 8          ┆ … 0.0]     ┆            ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 0.0, …    │
│       ┆            ┆            ┆            ┆   ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      ┆ 0.0]      │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
len(gene_features_reduced["reduced_features"][0])

100

In [31]:
gene_features_reduced = gene_features_reduced.select(['index', 'gene_id', 'reduced_features', 'value_1'])
gene_features_reduced

shape: (22_154, 4)
┌───────┬─────────────┬───────────────────────────────┬───────────┐
│ index ┆ gene_id     ┆ reduced_features              ┆ value_1   │
│ ---   ┆ ---         ┆ ---                           ┆ ---       │
│ u32   ┆ str         ┆ list[f64]                     ┆ f64       │
╞═══════╪═════════════╪═══════════════════════════════╪═══════════╡
│ 0     ┆ XLOC_000001 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 1     ┆ XLOC_000003 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 2     ┆ XLOC_000006 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0888452 │
│ 3     ┆ XLOC_000007 ┆ [0.0, 0.0, … 0.0]             ┆ 4.04743   │
│ 4     ┆ XLOC_000008 ┆ [5.717444, -11.321019, … 0.0] ┆ 26.7934   │
│ …     ┆ …           ┆ …                             ┆ …         │
│ 22149 ┆ XLOC_030009 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 22150 ┆ XLOC_030012 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 22151 ┆ XLOC_030014 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 22152 ┆ XLOC_030017 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
│ 22153 ┆ XLOC_030018 ┆ [0.0, 0.0, … 0.0]             ┆ 0.0       │
└───────┴─────────────┴───────────────────────────────┴───────────┘

In [50]:
# Save to file
gene_features_reduced.write_parquet(os.path.join(DATASET_DIR, 'features', 'reduced_features_rp.parquet'))

In [51]:
sample = gene_features_reduced.to_numpy()

In [52]:
sample

array([[0, 'XLOC_000001',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0],
       [1, 'XLOC_000003',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0],
       [2, 'XLOC_000006',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0888452],
       ...,
       [22151, 'XLOC_030014',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0],
       [22152, 'XLOC_030017',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0],
       [22153, 'XLOC_030018',
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])       ,
        0.0]], dtype=object)