In [1]:
import sys

sys.path.insert(0, '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib')
print(sys.path)

['/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib', '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/playground', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python312.zip', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/lib-dynload', '', '/home/amunif/.local/lib/python3.12/site-packages', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/site-packages']

In [2]:
import os
import random
from datetime import datetime

import pandas as pd
import polars as pl
import numpy as np

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
from torch.utils.data import Dataset, DataLoader, TensorDataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc, precision_recall_fscore_support, confusion_matrix, classification_report
from sklearn.metrics import ConfusionMatrixDisplay

import BinaryClassifier as BC
import HepG2Dataset as HG2D
import my_util

In [3]:
device = my_util.get_device()

Using device: cuda
Current CUDA device: 0
CUDA device name: Tesla P100-SXM2-16GB

In [4]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/07_deepchrome/dataset/E066"
markers = ['H3K4me3', 'H3K4me1','H3K36me3',  'H3K9me3', 'H3K27me3']
markers_count = ['H3K4me3_wc', 'H3K4me1_wc','H3K36me3_wc',  'H3K9me3_wc', 'H3K27me3_wc']

In [5]:
E066_w_histone_pl = pl.read_parquet(os.path.join(DATASET_PATH, 'E066_w_histone_pl.parquet'))

In [6]:
# Add index to dataframe
E066_w_histone_pl = E066_w_histone_pl.with_row_index("index")

In [7]:
E066_w_histone_pl

shape: (19_645, 20)
┌───────┬──────────────┬─────────────┬────────────┬───┬─────────────┬────────┬───────┬─────────────┐
│ index ┆ gene_id      ┆ H3K4me3     ┆ H3K4me3_wc ┆ … ┆ H3K27me3_le ┆ E066   ┆ label ┆ all_histone │
│ ---   ┆ ---          ┆ ---         ┆ ---        ┆   ┆ n           ┆ ---    ┆ ---   ┆ ---         │
│ u32   ┆ str          ┆ list[f64]   ┆ u32        ┆   ┆ ---         ┆ f64    ┆ i64   ┆ list[list[f │
│       ┆              ┆             ┆            ┆   ┆ u32         ┆        ┆       ┆ 64]]        │
╞═══════╪══════════════╪═════════════╪════════════╪═══╪═════════════╪════════╪═══════╪═════════════╡
│ 0     ┆ ENSG00000000 ┆ [0.0,       ┆ 19         ┆ … ┆ 100         ┆ 73.205 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 003          ┆ 4.19024, …  ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆ 0.0]        ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 4.19… │
│ 1     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.191  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 005          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 2     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 36         ┆ … ┆ 100         ┆ 52.609 ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 419          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 3     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 35         ┆ … ┆ 100         ┆ 4.733  ┆ 1     ┆ [[0.0, 0.0, │
│       ┆ 457          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 4     ┆ ENSG00000000 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.942  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 460          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ …     ┆ …            ┆ …           ┆ …          ┆ … ┆ …           ┆ …      ┆ …     ┆ …           │
│ 19640 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.212  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 658          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19641 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 664          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19642 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.071  ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 680          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
│ 19643 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 18         ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0,      │
│       ┆ 717          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ 3.18223, …  │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ 0.0], [0.0, │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ …           │
│ 19644 ┆ ENSG00000259 ┆ [0.0, 0.0,  ┆ 0          ┆ … ┆ 100         ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, │
│       ┆ 752          ┆ … 0.0]      ┆            ┆   ┆             ┆        ┆       ┆ … 0.0],     │
│       ┆              ┆             ┆            ┆   ┆             ┆        ┆       ┆ [0.0, 0.0,… │
└───────┴──────────────┴─────────────┴────────────┴───┴─────────────┴────────┴───────┴─────────────┘

# Descriptive statistics

In [8]:
E066_w_histone_pl["E066"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 19645.0    │
│ null_count ┆ 0.0        │
│ mean       ┆ 45.584333  │
│ std        ┆ 913.103491 │
│ min        ┆ 0.0        │
│ 25%        ┆ 0.115      │
│ 50%        ┆ 2.423      │
│ 75%        ┆ 10.843     │
│ max        ┆ 102156.0   │
└────────────┴────────────┘

# Zero gene expression level

In [9]:
zero_count = (E066_w_histone_pl["E066"] == 0.0).sum()
print(zero_count)
print(f"Zero value: {zero_count / len(E066_w_histone_pl) * 100:.2f}%")

2902
Zero value: 14.77%

# Zero histone marker

In [10]:
E066_w_histone_pl = E066_w_histone_pl.with_columns(
    pl.sum_horizontal(markers_count).alias("Total")
)

In [11]:
E066_w_histone_pl

shape: (19_645, 21)
┌───────┬────────────────┬───────────────┬────────────┬───┬────────┬───────┬───────────────┬───────┐
│ index ┆ gene_id        ┆ H3K4me3       ┆ H3K4me3_wc ┆ … ┆ E066   ┆ label ┆ all_histone   ┆ Total │
│ ---   ┆ ---            ┆ ---           ┆ ---        ┆   ┆ ---    ┆ ---   ┆ ---           ┆ ---   │
│ u32   ┆ str            ┆ list[f64]     ┆ u32        ┆   ┆ f64    ┆ i64   ┆ list[list[f64 ┆ u32   │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ ]]            ┆       │
╞═══════╪════════════════╪═══════════════╪════════════╪═══╪════════╪═══════╪═══════════════╪═══════╡
│ 0     ┆ ENSG0000000000 ┆ [0.0,         ┆ 19         ┆ … ┆ 73.205 ┆ 1     ┆ [[0.0, 0.0, … ┆ 29    │
│       ┆ 3              ┆ 4.19024, …    ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 4.19…         ┆       │
│ 1     ┆ ENSG0000000000 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.191  ┆ 0     ┆ [[0.0, 0.0, … ┆ 2     │
│       ┆ 5              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 2     ┆ ENSG0000000041 ┆ [0.0, 0.0, …  ┆ 36         ┆ … ┆ 52.609 ┆ 1     ┆ [[0.0, 0.0, … ┆ 115   │
│       ┆ 9              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 3     ┆ ENSG0000000045 ┆ [0.0, 0.0, …  ┆ 35         ┆ … ┆ 4.733  ┆ 1     ┆ [[0.0, 0.0, … ┆ 70    │
│       ┆ 7              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 4     ┆ ENSG0000000046 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.942  ┆ 0     ┆ [[0.0, 0.0, … ┆ 5     │
│       ┆ 0              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ …     ┆ …              ┆ …             ┆ …          ┆ … ┆ …      ┆ …     ┆ …             ┆ …     │
│ 19640 ┆ ENSG0000025965 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.212  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 8              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19641 ┆ ENSG0000025966 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, … ┆ 5     │
│       ┆ 4              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19642 ┆ ENSG0000025968 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.071  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 0              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19643 ┆ ENSG0000025971 ┆ [0.0, 0.0, …  ┆ 18         ┆ … ┆ 0.0    ┆ 0     ┆ [[0.0,        ┆ 98    │
│       ┆ 7              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 3.18223, …    ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0], [0.0, … ┆       │
│ 19644 ┆ ENSG0000025975 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.0    ┆ 0     ┆ [[0.0, 0.0, … ┆ 13    │
│       ┆ 2              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
└───────┴────────────────┴───────────────┴────────────┴───┴────────┴───────┴───────────────┴───────┘

In [12]:
result = E066_w_histone_pl.group_by("Total").len(name="count")

In [13]:
result.sort("count", descending=True)

shape: (220, 2)
┌───────┬───────┐
│ Total ┆ count │
│ ---   ┆ ---   │
│ u32   ┆ u32   │
╞═══════╪═══════╡
│ 0     ┆ 1487  │
│ 3     ┆ 447   │
│ 6     ┆ 235   │
│ 4     ┆ 214   │
│ 65    ┆ 203   │
│ …     ┆ …     │
│ 190   ┆ 1     │
│ 202   ┆ 1     │
│ 211   ┆ 1     │
│ 235   ┆ 1     │
│ 262   ┆ 1     │
└───────┴───────┘

# Zero histone marker with > 0 gene expression value

In [14]:
filtered_df = E066_w_histone_pl.filter((pl.col('E066') > 0.0) & (pl.col('Total') == 0))
filtered_df

shape: (786, 21)
┌───────┬────────────────┬───────────────┬────────────┬───┬────────┬───────┬───────────────┬───────┐
│ index ┆ gene_id        ┆ H3K4me3       ┆ H3K4me3_wc ┆ … ┆ E066   ┆ label ┆ all_histone   ┆ Total │
│ ---   ┆ ---            ┆ ---           ┆ ---        ┆   ┆ ---    ┆ ---   ┆ ---           ┆ ---   │
│ u32   ┆ str            ┆ list[f64]     ┆ u32        ┆   ┆ f64    ┆ i64   ┆ list[list[f64 ┆ u32   │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ ]]            ┆       │
╞═══════╪════════════════╪═══════════════╪════════════╪═══╪════════╪═══════╪═══════════════╪═══════╡
│ 17    ┆ ENSG0000000163 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 50.076 ┆ 1     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 0              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 66    ┆ ENSG0000000493 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.069  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 9              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 99    ┆ ENSG0000000548 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 52.191 ┆ 1     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 6              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 122   ┆ ENSG0000000607 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.438  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 4              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 143   ┆ ENSG0000000660 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.076  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 6              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ …     ┆ …              ┆ …             ┆ …          ┆ … ┆ …      ┆ …     ┆ …             ┆ …     │
│ 19616 ┆ ENSG0000025928 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.076  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 9              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19620 ┆ ENSG0000025936 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.362  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 3              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19632 ┆ ENSG0000025951 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.431  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 1              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19640 ┆ ENSG0000025965 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.212  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 8              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
│ 19642 ┆ ENSG0000025968 ┆ [0.0, 0.0, …  ┆ 0          ┆ … ┆ 0.071  ┆ 0     ┆ [[0.0, 0.0, … ┆ 0     │
│       ┆ 0              ┆ 0.0]          ┆            ┆   ┆        ┆       ┆ 0.0], [0.0,   ┆       │
│       ┆                ┆               ┆            ┆   ┆        ┆       ┆ 0.0,…         ┆       │
└───────┴────────────────┴───────────────┴────────────┴───┴────────┴───────┴───────────────┴───────┘