In [1]:
import sys

sys.path.insert(0, '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib')
print(sys.path)

['/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/mylib', '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/notebook/playground', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python312.zip', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/lib-dynload', '', '/home/amunif/.local/lib/python3.12/site-packages', '/uwahpc/centos8/python/Anaconda3/2024.06/lib/python3.12/site-packages']

In [2]:
import os
import random
from datetime import datetime

import pandas as pd
import polars as pl
import numpy as np

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
from torch.utils.data import Dataset, DataLoader, TensorDataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc, precision_recall_fscore_support, confusion_matrix, classification_report
from sklearn.metrics import ConfusionMatrixDisplay

import BinaryClassifier as BC
import HepG2Dataset as HG2D
import my_util

In [3]:
device = my_util.get_device()

Using device: cuda
Current CUDA device: 0
CUDA device name: Tesla P100-SXM2-16GB

In [4]:
# Declare  variables, working directory and dataset directory
MODE = 'all_features'
NUM_EPOCHS = 100
START_EPOCH = 0
NUM_ITEMS = 100_000
BATCH_SIZE = 32
DROPOUT_RATE = 0.2

L1_lambda = 0.005
L2_lambda = 0.001
# L1_lambda = 0.0
# L2_lambda = 0.0

hidden1_size=64
hidden2_size=32

WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/dataset'

MODEL_MODE = "dol1l2" # regular (reg), dropout (do), dropout + l1l2 (dol1l2)
PREFIX = f"{MODEL_MODE}-autoencoder-cnn-{hidden1_size}-{hidden2_size}-{DROPOUT_RATE}"
SUFFIX = f"{NUM_ITEMS}-{NUM_EPOCHS}-{BATCH_SIZE}-{L1_lambda}-{L2_lambda}"

CHECKPOINT_NAME = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, 'model', f'{PREFIX}-checkpoint-{SUFFIX}.pt')

IMAGE_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, 'img', 'train', f"{PREFIX}-ranking-{SUFFIX}.png")
TEST_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, 'test', f"{PREFIX}-test-results-{SUFFIX}.txt")
TRAINING_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, "train", f"{PREFIX}-train-validation-metrics-{SUFFIX}.csv")
TEST_RESULT_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, "test", f"{PREFIX}-test-metrics-{SUFFIX}.csv")
ROC_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, 'img', 'roc', f"{PREFIX}-roc-{SUFFIX}.png")
CM_FILE = os.path.join(WORKING_DIR, 'output', 'autoencoder', MODE, 'img', 'cm', f"{PREFIX}-cm-{SUFFIX}.png")

INPUT_SIZE = 256

print(CHECKPOINT_NAME)

/group/pmc021/amunif/epi-thesis/workflow/09_Learning_to_Rank/output/autoencoder/all_features/model/dol1l2-autoencoder-cnn-64-32-0.2-checkpoint-100000-100-32-0.005-0.001.pt

In [10]:
markers = ["H3K4me3_count", "H3K9ac_count", "H3K9me3_count", "H3K27ac_count", "H3K27me3_count"]

In [6]:
# Load dataset
gene_pl = pl.read_parquet(os.path.join(DATASET_DIR, 'gene_w_label_value_1.parquet'))
gene_pl

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i32   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 0     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 1     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 1     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

# Descriptive statistics

In [7]:
gene_pl["value_1"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 22154.0    │
│ null_count ┆ 0.0        │
│ mean       ┆ 21.856847  │
│ std        ┆ 167.605195 │
│ min        ┆ 0.0        │
│ 25%        ┆ 0.0155566  │
│ 50%        ┆ 1.14229    │
│ 75%        ┆ 12.2663    │
│ max        ┆ 12870.9    │
└────────────┴────────────┘

# Zero gene expression level

In [8]:
zero_count = (gene_pl["value_1"] == 0.0).sum()
print(zero_count)
print(f"Zero values: {zero_count / len(gene_pl) * 100:.2f}%")

5100
Zero values: 23.02%

# Zero histone marker

In [11]:
gene_pl = gene_pl.with_columns(
    pl.sum_horizontal(markers).alias("Total")
)

gene_pl

shape: (22_154, 14)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────┬───────┐
│ gene_id     ┆ H3K4me3     ┆ H3K4me3_co ┆ H3K9ac     ┆ … ┆ H3K27me3_c ┆ value_1   ┆ label ┆ Total │
│ ---         ┆ ---         ┆ unt        ┆ ---        ┆   ┆ ount       ┆ ---       ┆ ---   ┆ ---   │
│ str         ┆ list[f64]   ┆ ---        ┆ list[f64]  ┆   ┆ ---        ┆ f64       ┆ i32   ┆ i64   │
│             ┆             ┆ i64        ┆            ┆   ┆ i64        ┆           ┆       ┆       │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════╪═══════╡
│ XLOC_000001 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000003 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000006 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0888452 ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000007 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 4.04743   ┆ 1     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000008 ┆ [0.0, 0.0,  ┆ 6          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 26.7934   ┆ 1     ┆ 11    │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …     ┆ …     │
│ XLOC_030009 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_030012 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_030014 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_030017 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_030018 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0       ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────┴───────┘

In [13]:
result = gene_pl.group_by("Total").len(name="count")

In [16]:
result.sort("count", descending=True)

shape: (50, 2)
┌───────┬───────┐
│ Total ┆ count │
│ ---   ┆ ---   │
│ i64   ┆ u32   │
╞═══════╪═══════╡
│ 0     ┆ 6452  │
│ 1     ┆ 1268  │
│ 13    ┆ 816   │
│ 15    ┆ 774   │
│ 12    ┆ 726   │
│ …     ┆ …     │
│ 48    ┆ 1     │
│ 51    ┆ 1     │
│ 42    ┆ 1     │
│ 47    ┆ 1     │
│ 43    ┆ 1     │
└───────┴───────┘

# Zero histone marker with > 0 gene expression value

In [17]:
filtered_df = gene_pl.filter((pl.col('value_1') > 0.0) & (pl.col('Total') == 0))
filtered_df

shape: (3_322, 14)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────┬───────┐
│ gene_id     ┆ H3K4me3     ┆ H3K4me3_co ┆ H3K9ac     ┆ … ┆ H3K27me3_c ┆ value_1   ┆ label ┆ Total │
│ ---         ┆ ---         ┆ unt        ┆ ---        ┆   ┆ ount       ┆ ---       ┆ ---   ┆ ---   │
│ str         ┆ list[f64]   ┆ ---        ┆ list[f64]  ┆   ┆ ---        ┆ f64       ┆ i32   ┆ i64   │
│             ┆             ┆ i64        ┆            ┆   ┆ i64        ┆           ┆       ┆       │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════╪═══════╡
│ XLOC_000006 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0888452 ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000007 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 4.04743   ┆ 1     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000017 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.120855  ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000027 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 1.24157   ┆ 1     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_000036 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.0174318 ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …     ┆ …     │
│ XLOC_029789 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 7.90053   ┆ 1     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_029812 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.428552  ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_029843 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.132486  ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_029897 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.176318  ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
│ XLOC_029941 ┆ [0.0, 0.0,  ┆ 0          ┆ [0.0, 0.0, ┆ … ┆ 0          ┆ 0.219854  ┆ 0     ┆ 0     │
│             ┆ … 0.0]      ┆            ┆ … 0.0]     ┆   ┆            ┆           ┆       ┆       │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────┴───────┘