In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/13_Healthy liver with manual preprocessing/dataset/donor_4/"
OUTPUT_PATH  = "/group/pmc021/amunif/epi-thesis/workflow/13_Healthy liver with manual preprocessing/output/donor_4/"

In [3]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(os.path.join(OUTPUT_PATH, 'test', "*.csv"))

In [4]:
pl_df

shape: (31, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_accur ┆ val_auc_a ┆ test_accu ┆ test_auc │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ acy_avg   ┆ vg        ┆ racy      ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K4me3   ┆ 0.5572    ┆ 73.6468   ┆ 0.7365    ┆ … ┆ 73.9421   ┆ 0.7383    ┆ 73.59     ┆ 0.7346   │
│ H3K9ac    ┆ 0.5633    ┆ 72.9983   ┆ 0.7291    ┆ … ┆ 73.6093   ┆ 0.7346    ┆ 73.97     ┆ 0.7368   │
│ H3K9me3   ┆ 0.7141    ┆ 51.6652   ┆ 0.5086    ┆ … ┆ 52.0026   ┆ 0.5095    ┆ 53.09     ┆ 0.5107   │
│ H3K27ac   ┆ 0.5545    ┆ 74.0157   ┆ 0.7395    ┆ … ┆ 74.4799   ┆ 0.7428    ┆ 75.52     ┆ 0.7536   │
│ H3K27me3  ┆ 0.7109    ┆ 51.965    ┆ 0.5091    ┆ … ┆ 52.1455   ┆ 0.5089    ┆ 52.44     ┆ 0.509    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K4me3-H ┆ 0.54      ┆ 74.5499   ┆ 0.7437    ┆ … ┆ 75.2497   ┆ 0.7504    ┆ 74.66     ┆ 0.7459   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5268    ┆ 75.3453   ┆ 0.7501    ┆ … ┆ 75.8514   ┆ 0.7575    ┆ 76.71     ┆ 0.7662   │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5258    ┆ 75.3661   ┆ 0.7504    ┆ … ┆ 75.8033   ┆ 0.757     ┆ 76.56     ┆ 0.7646   │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9ac-H3 ┆ 0.5336    ┆ 74.8738   ┆ 0.7487    ┆ … ┆ 75.584    ┆ 0.7543    ┆ 75.76     ┆ 0.7552   │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K4me3-H ┆ 0.5229    ┆ 75.5369   ┆ 0.7551    ┆ … ┆ 76.1653   ┆ 0.7609    ┆ 75.27     ┆ 0.752    │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Add the histone number column
pl_df = pl_df.with_columns(
     (pl.col("histone_marker").str.count_matches("-") + 1).alias("number_of_histones")
)

In [6]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3   ┆ 0.5572    ┆ 73.6468   ┆ 0.7365    ┆ … ┆ 0.7383    ┆ 73.59     ┆ 0.7346   ┆ 1         │
│ H3K9ac    ┆ 0.5633    ┆ 72.9983   ┆ 0.7291    ┆ … ┆ 0.7346    ┆ 73.97     ┆ 0.7368   ┆ 1         │
│ H3K9me3   ┆ 0.7141    ┆ 51.6652   ┆ 0.5086    ┆ … ┆ 0.5095    ┆ 53.09     ┆ 0.5107   ┆ 1         │
│ H3K27ac   ┆ 0.5545    ┆ 74.0157   ┆ 0.7395    ┆ … ┆ 0.7428    ┆ 75.52     ┆ 0.7536   ┆ 1         │
│ H3K27me3  ┆ 0.7109    ┆ 51.965    ┆ 0.5091    ┆ … ┆ 0.5089    ┆ 52.44     ┆ 0.509    ┆ 1         │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K4me3-H ┆ 0.54      ┆ 74.5499   ┆ 0.7437    ┆ … ┆ 0.7504    ┆ 74.66     ┆ 0.7459   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5268    ┆ 75.3453   ┆ 0.7501    ┆ … ┆ 0.7575    ┆ 76.71     ┆ 0.7662   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5258    ┆ 75.3661   ┆ 0.7504    ┆ … ┆ 0.757     ┆ 76.56     ┆ 0.7646   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K9ac-H3 ┆ 0.5336    ┆ 74.8738   ┆ 0.7487    ┆ … ┆ 0.7543    ┆ 75.76     ┆ 0.7552   ┆ 4         │
│ K9me3-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5229    ┆ 75.5369   ┆ 0.7551    ┆ … ┆ 0.7609    ┆ 75.27     ┆ 0.752    ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [7]:
# Sort by number_of_histones (desc) and histone_marker (asc)
pl_df = pl_df.sort(
    by=["number_of_histones", "histone_marker"],
    descending=[True, False]
)

In [8]:
pl_df

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ val_auc_a ┆ test_accu ┆ test_auc ┆ number_of │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ vg        ┆ racy      ┆ ---      ┆ _histones │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆          ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5229    ┆ 75.5369   ┆ 0.7551    ┆ … ┆ 0.7609    ┆ 75.27     ┆ 0.752    ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5268    ┆ 75.3453   ┆ 0.7501    ┆ … ┆ 0.7575    ┆ 76.71     ┆ 0.7662   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5265    ┆ 75.4713   ┆ 0.7522    ┆ … ┆ 0.7595    ┆ 76.01     ┆ 0.7596   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.54      ┆ 74.5499   ┆ 0.7437    ┆ … ┆ 0.7504    ┆ 74.66     ┆ 0.7459   ┆ 4         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ H3K4me3-H ┆ 0.5258    ┆ 75.3661   ┆ 0.7504    ┆ … ┆ 0.757     ┆ 76.56     ┆ 0.7646   ┆ 4         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ H3K27ac   ┆ 0.5545    ┆ 74.0157   ┆ 0.7395    ┆ … ┆ 0.7428    ┆ 75.52     ┆ 0.7536   ┆ 1         │
│ H3K27me3  ┆ 0.7109    ┆ 51.965    ┆ 0.5091    ┆ … ┆ 0.5089    ┆ 52.44     ┆ 0.509    ┆ 1         │
│ H3K4me3   ┆ 0.5572    ┆ 73.6468   ┆ 0.7365    ┆ … ┆ 0.7383    ┆ 73.59     ┆ 0.7346   ┆ 1         │
│ H3K9ac    ┆ 0.5633    ┆ 72.9983   ┆ 0.7291    ┆ … ┆ 0.7346    ┆ 73.97     ┆ 0.7368   ┆ 1         │
│ H3K9me3   ┆ 0.7141    ┆ 51.6652   ┆ 0.5086    ┆ … ┆ 0.5095    ┆ 53.09     ┆ 0.5107   ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
# Add the rank column
pl_df = pl_df.with_columns(
    pl.col('test_accuracy').rank(method='ordinal', descending=True).alias('order_by_test_acc')
)

pl_df

shape: (31, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ histone_m ┆ train_los ┆ train_acc ┆ train_auc ┆ … ┆ test_accu ┆ test_auc ┆ number_of ┆ order_by_ │
│ arker     ┆ s_avg     ┆ uracy_avg ┆ _avg      ┆   ┆ racy      ┆ ---      ┆ _histones ┆ test_acc  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆          ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ H3K4me3-H ┆ 0.5229    ┆ 75.5369   ┆ 0.7551    ┆ … ┆ 75.27     ┆ 0.752    ┆ 5         ┆ 16        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5268    ┆ 75.3453   ┆ 0.7501    ┆ … ┆ 76.71     ┆ 0.7662   ┆ 4         ┆ 1         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27ac-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5265    ┆ 75.4713   ┆ 0.7522    ┆ … ┆ 76.01     ┆ 0.7596   ┆ 4         ┆ 5         │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7ac       ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.54      ┆ 74.5499   ┆ 0.7437    ┆ … ┆ 74.66     ┆ 0.7459   ┆ 4         ┆ 18        │
│ 3K9ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 9me3-H3K2 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 7me…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ H3K4me3-H ┆ 0.5258    ┆ 75.3661   ┆ 0.7504    ┆ … ┆ 76.56     ┆ 0.7646   ┆ 4         ┆ 2         │
│ 3K9me3-H3 ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ K27ac-H3K ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 27m…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ H3K27ac   ┆ 0.5545    ┆ 74.0157   ┆ 0.7395    ┆ … ┆ 75.52     ┆ 0.7536   ┆ 1         ┆ 13        │
│ H3K27me3  ┆ 0.7109    ┆ 51.965    ┆ 0.5091    ┆ … ┆ 52.44     ┆ 0.509    ┆ 1         ┆ 31        │
│ H3K4me3   ┆ 0.5572    ┆ 73.6468   ┆ 0.7365    ┆ … ┆ 73.59     ┆ 0.7346   ┆ 1         ┆ 26        │
│ H3K9ac    ┆ 0.5633    ┆ 72.9983   ┆ 0.7291    ┆ … ┆ 73.97     ┆ 0.7368   ┆ 1         ┆ 24        │
│ H3K9me3   ┆ 0.7141    ┆ 51.6652   ┆ 0.5086    ┆ … ┆ 53.09     ┆ 0.5107   ┆ 1         ┆ 30        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
# Save the dataframe as CSV
pl_df.write_csv(os.path.join("Donor 4 ranking.csv"))